### ISSUE TITLE
Краш расширения при установке

### ISSUE THREAD

**Issue by DrakeXGames** [anticensority/runet-censorship-bypass#100]
Случайно в настройках браузера выключил расширение, через какое-то время включил его, оно выбило по ссылке "browser://extensions/?id=npgcnondjocldhldegnakemclmfkngch" и ничего больше не работало, когда нажимаю установить, оно само удаляется, по центру вылазит пустое окошко:
![image](https://user-images.githubusercontent.com/92822116/137974797-b2bd1e55-f1a0-4f96-b2a9-0a9c3f5d019d.png)
Я пытался и расширение переустанавливать, и комп перезагружать, и браузер обновить (яндекс браузер) и даже полностью снести со всеми его настройками и заново установить. Ничего не работает. Так же в хроме показало похожее расширение "FastProxy", так оно тоже не работало, однако обычный впн, который "отправляет" меня в Нидерланды работает. Так же я зашел в браузер Edge, и там это расширение нормально установилось и работало

**Comment by ilyaigpetrov** [comment]
См. https://ntc.party/t/21-9-1-546/1392.
Я попробую разобраться, в чём проблема, но это займёт время.

**Comment by abramaqabra** [comment]
наблюдение: на Chrome Canary 97.0.4680.1 сегодня тоже отваливалось, но в районе 10 вечера по Москве все обратно заработало.

**Comment by stabbul** [comment]
В браузере Yandex beta 21.9.1.600 beta (64-bit) ОС Linux Mint, крашится при клике мышью на значек, появляется по центру сообщение как на скриншоте и в правом нижнем углу "Произошел сбой приложения Обход блокировок Рунета. Нажмите на это сообщение, чтобы загрузить его ещё раз." И так по кругу.

**Comment by stabbul** [comment]
То есть проблема с меню дополнения. Меню крашит. При этом, если не открывать меню, все работает - сайты открываются.

**Comment by DrakeXGames** [comment]
проблема уже решилась сама сабой, просто подождал 2 недели и оно установилось. Читал, что это просто яндекс сломал браузер, вот и не давало установить расширение
