### ISSUE TITLE
Расширение не собирается из-за старой версии `gulp`

### ISSUE THREAD

**Issue by rakleed** [anticensority/runet-censorship-bypass#102]
Расширение не собирается (после ввода `npm start`) из-за ошибки `ReferenceError: primordials is not defined`, по крайне мере на macOS. Я погуглил, и помогло [решение](https://stackoverflow.com/questions/67815947/getting-error-referenceerror-primordials-is-not-defined) использовать `gulp` версии 4.x.x. При этом проблем при использовании расширения в Chrome не заметил. Можете обновить эту зависимость, а также другие зависимости? Так как в старых версиях довольно много уязвимостей.

**Comment by ilyaigpetrov** [comment]
Нужно использовать package.json из [1].
Вы использовали из [2]?

[1]:
https://github.com/anticensority/runet-censorship-bypass/blob/development/extensions/chromium/runet-censorship-bypass/
[2]: https://github.com/anticensority/runet-censorship-bypass

**Comment by ilyaigpetrov** [comment]
В [1] gulp версии ^4.0.2.

**Comment by ilyaigpetrov** [comment]
> Так как в старых версиях довольно много уязвимостей.

Эти уязвимости можно эксплуатировать только во время сборки проекта (фаза build, которая генерирует расширение для браузера). Не спорю, риск скачать вирус будет меньше, если обновить зависимости.

__UPD__
* Пакеты, используемые не для сборки, а, к примеру, для формирования DOM страницы (infernoJS), могут быть эксплуатированы во время работы расширения.

**Comment by ilyaigpetrov** [comment]
> по крайне мере на macOS

Я тестировал только под bash/linux. В windows можно использовать https://git.io/ilyaigpetrov-wsl.

**Comment by rakleed** [comment]
Может быть я действительно не https://github.com/anticensority/runet-censorship-bypass/blob/development/extensions/chromium/runet-censorship-bypass/ использовал, но сейчас заново клонировал репозиторий, и теперь всё собралось без ошибок.
