### ISSUE TITLE
Добавить Simkl.com

### ISSUE THREAD

**Issue by Phoenomenal** [anticensority/runet-censorship-bypass#108]
Администрация  сайта Simkl.com заблокировала всех посетителей с русскими IP адресами в связи с последними событиями. 

![image](https://user-images.githubusercontent.com/68902338/155610304-0d282cca-0c82-49c4-a269-c7cc9430de24.png)

Возможно ли будет добавить данный сайт для обхода блокировки ?

**Comment by ilyaigpetrov** [comment]
Наши решения работают только по реестру (https://reestr.rublacklist.net).
Внереестровые адреса не добавляются, можно лишь добавить их в проксируемые
в расширении (иконка синей ленты -> Исключения -> да, проксировать), но для
этого нужны свои прокси или тор.

Тор:
https://github.com/anticensority/runet-censorship-bypass/wiki/Расширение-и-TOR
.
Свои прокси:
https://github.com/anticensority/runet-censorship-bypass/wiki/Свои-прокси-в-расширении
.
Обход блокировок Тора:
https://github.com/anticensority/runet-censorship-bypass/wiki/Как-подключиться-к-Tor,-когда-его-пытаются-
заблокировать%3F.
