### ISSUE TITLE
проксировать замедленые сайты

### ISSUE THREAD

**Issue by whoizit** [anticensority/runet-censorship-bypass#111]
они говорят facebook замедляют. Но у меня он вообще не открывается. Нужно создать отдельный список не заблокированых, но замедленных сайтов и добавить в интерфейс приложения галку чтоб подобные сайты тоже проксировались. Либо добавить их в список как заблокированный в россии

**Comment by ilyaigpetrov** [comment]
Вот список от РосКомСвободы, редактируется вручную: https://registry.censortracker.org/registry-api/domains/?countryCode=ru.

Я добавил этот список в PAC-скрипт "Антицензорити", но пока не публикую новую версию, т.к. мне не удаётся проксировать замедленные сайты через Тор. Какой смысл мне публиковаться, если у большинства пользователей функция работать всё равно не будет.

Проксировать на АнтиЗапрете twitter и facebook мы не можем, т.к. админисратор прокси опасается перегрузки серверов из-за возросшего трафика к этим сайтам.

**Comment by whoizit** [comment]
у меня свой прокси

**Comment by whoizit** [comment]
список не валидный. фейсбук не открывается (СПБ/Ростелеком) без проксирования fbcdn.net

**Comment by ilyaigpetrov** [comment]
Предложить добавить в этот список РКС домены можно в этом канале: https://t.me/CensorTracker_feedback.

**Comment by ilyaigpetrov** [comment]
Я добавил адреса из этого списка в Антицензорити. Proxy-сервер у вас уже должен быть прописан, остаётся лишь обновить PAC-скрипт: иконка синей ленты -> вкладка PAC-скрипт -> нажать "[обновить]" рядом с Антицензорити.

**Comment by whoizit** [comment]
работает только если я вручную добавляю facebook.com, fbcdn.net в список проксирования. Не понятно как парсить файл anticensority.pac чтоб проверить есть ли в нём эти домены. grep/ripgrep не подсвечивает, less вешается

**Comment by ilyaigpetrov** [comment]
> Не понятно как парсить файл anticensority.pac чтоб проверить есть ли в нём эти домены.

Иконка синей летны -> Проблемы? -> Отладка PAC-скрипта -> READ -> Ctrl+F -> facebook.com.

**Comment by ilyaigpetrov** [comment]
Те адреса, что были добавлены в список РосКомСвободы недавно, не сразу попадут к вам в расширение. Чаще обновляйтесь и проверяйте.

**Comment by ilyaigpetrov** [comment]
Всё, я форсировал обновление скрипта на GitHub. Facebook.com и twitter.com теперь проксируются в расширении.

**Comment by ilyaigpetrov** [comment]
Опубликовал новость о добавлении нового списка: https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-1056970638.

**Comment by whoizit** [comment]
Работает. Своевременно. Благодарю за вашу работу!
