### ISSUE TITLE
не работает твиттер

### ISSUE THREAD

**Issue by yo8z6gv** [anticensority/runet-censorship-bypass#113]
у меня вот так выглядит сайт:
![2022-03-05 00_36_33-Главная _ Твиттер](https://user-images.githubusercontent.com/62700253/156844997-df357fc8-a524-47d0-9305-bf6f38e00371.jpg)

**Comment by yo8z6gv** [comment]
и facebook тоже. очень долго грузит и потом:
![2022-03-05 00_45_45-www facebook com](https://user-images.githubusercontent.com/62700253/156846121-e388a678-c263-49d8-a96c-b66be84ea45d.jpg)

**Comment by ilyaigpetrov** [comment]
От админа АнтиЗапрета:
> [...]в реестре есть только facebook.com и twitter.com, а ресурсы загружаются с fbcdn.net, twimg.com, их нет в реестре, но они заблокированы на ТСПУ.

Либо переключитесь на Антицензорити или останьтесь на АнтиЗапрете, но добавьте исключения (в обоих случаях нужны тор или свои прокси), либо подождите, пока автор АнтиЗапрета вручную добавит эти дополнительные адреса в проксируемые (но гарантии, что это произойдёт, я не даю).

**Comment by genrihx2** [comment]
screenshots  facebook   
![image](https://user-images.githubusercontent.com/3043207/156909839-bd03ee05-a8b7-45ab-a8bd-3f20eb94c203.png)

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-1059950965.
