### ISSUE TITLE
Поддержка OpenVPN

### ISSUE THREAD

**Issue by izzqz** [anticensority/runet-censorship-bypass#116]
Я активно использую OpenVPN с радостью использовал бы с этим прекрасным расширением как свои "прокси"

**Comment by ilyaigpetrov** [comment]
Если OpenVPN может предоставлять прокси для пропускания трафика через настроенный VPN, то в расширении адрес этого прокси можно прописать здесь: иконка синей ленты -> свои прокси -> "Подменять DIRECT на".

**Comment by ilyaigpetrov** [comment]
Неверно вас проинформировал.
DIRECT подменяют, если незаблокированные сайты нужно пропускать через прокси (в том числе от VPN-клиента). ~Это нужно, если в организации подключение к интернету (ко всем сайтам, заблокированным или нет) возможно лишь через прокси или VPN.~ Это нужно, если доступ к корпроративным ресурсам возможен лишь через прокси.

Если же есть VPN с торчащими наружу прокси для обхода блокировок, то такие прокси можно добавить в расширении на вкладке "Свои прокси" -- см. https://rebrand.ly/ac-own-proxies.

**Comment by ofry** [comment]
Есть рабочий OpenVPN сервер (свой). К нему можно подключиться через OpenVPN клиент. Все будет работать - но это проксирует ВСЕ соединения на компе. А если я хочу подключаться через него лишь только для определенных сайтов? Добавьте, пожалуйста, такую функциональность.

**Comment by ilyaigpetrov** [comment]
Я не пользовался OpenVPN, но знакомый сказал, что в нём нет такой функциональности (предоставлять прокси пользователю).

**Comment by ofry** [comment]
Но ведь как-то работает https://antizapret.prostovpn.org/

Если установить такое VPN соединение именно с этим сервером, то соединения с "открытыми" сайтами будут идти напрямую, что можно проверить через 2IP.

Но в "списки" сайтов попадает лишь то, что заблокировано РКН, а не самим владельцем сайта (что стало актуально после 24 февраля)

**Comment by ofry** [comment]
https://www.google.com/search?newwindow=1&sxsrf=APq-WBuZzv4qqybOgPqLhEaCXFCrEmHNZQ:1647964960550&q=OpenVPN+%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C+%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE+%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5+%D1%81%D0%B0%D0%B9%D1%82%D1%8B&spell=1&sa=X&ved=2ahUKEwjGj83wi9r2AhXqQ_EDHUtLBBMQBSgAegQIARA3&biw=1280&bih=838&dpr=1

Вот кой-какая информация
