### ISSUE TITLE
chrome 59.0.3071.86 64bit : Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by pult** [anticensority/runet-censorship-bypass#12]
К этой ошибке приводит следующая последовательность действий:
1. chrome 59.0.3071.86 64bit
2. вызываем диалог настроек плагина

https://anticensority.tk/error/0.0.0.17/?json=%7B%22ext-error%22%3A%7B%22message%22%3A%22Uncaught+TypeError%3A+Cannot+read+property+%27split%27+of+undefined%22%2C%22filename%22%3A%22chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F11-error-handlers-api.js%22%2C%22lineno%22%3A207%2C%22colno%22%3A9%2C%22error%22%3A%7B%22stack%22%3A%22TypeError%3A+Cannot+read+property+%27split%27+of+undefined%5Cn++++at+splitBySemi.map+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A4391%3A38%29%5Cn++++at+Array.map+%28native%29%5Cn++++at+TabledEditor.render+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A4388%3A53%29%5Cn++++at+Object.createClassComponentInstance+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A154%3A26%29%5Cn++++at+mountComponent+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A1760%3A32%29%5Cn++++at+mount+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A1633%3A16%29%5Cn++++at+mountComponent+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A1763%3A27%29%5Cn++++at+mount+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A1633%3A16%29%5Cn++++at+mountElement+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A1698%3A13%29%5Cn++++at+mount+%28chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2Fpages%2Foptions%2Fdist%2Fbundle.min.js%3A1630%3A16%29%22%2C%22message%22%3A%22Cannot+read+property+%27split%27+of+undefined%22%2C%22name%22%3A%22TypeError%22%7D%2C%22type%22%3A%22error%22%7D%7D&type=ext-error&version=0.0.1.0

**Comment by ilyaigpetrov** [comment]
Откройте настройки и, проигнорировав ошибку, покажите, пожалуйста, что у вас в:
1. Свои прокси > Использовать свои прокси
2. Свои прокси > Использовать свои прокси > ⇄

**Comment by pult** [comment]
Проигнорировать нет возможности. Сразу выбрасывает диалог (с иконкой ext-error-128.png) перенаправляющий на страницу со ссылкой. В 58.0.3029.110 то-же самое выползло. Т.к. это девелоперские версии chrome , то возможно скоро новшество доползёт и до боевого chrome. В настройках (по памяти) - исп. свои прокси (там https). Плагин работает нормально но настройка теперь недоступна :)

**Comment by ilyaigpetrov** [comment]
Предполагаю, что у вас в свих прокси прописаны сервера без портов.
Как вы это сделали, я не знаю, по сути вы не должны были пройти валидацию.
Как вариант, вы прописали беспортовые прокси в старой версии, и они наследовались при обновлении.

Вы можете переустановить расширение и тогда свои прокси сбросятся до пустых значений.

**Comment by ilyaigpetrov** [comment]
Или прокси без типа, не уверен про порты, просто запись должна быть невалидная.

**Comment by pult** [comment]
Да, там раньше была строка типа:
HTTPS proxy1:3128; PROXY proxy2:3128; DIRECT
Из-за DIRECT явно ...

**Comment by ilyaigpetrov** [comment]
Вы можете достать адреса старых прокси из памяти:
1. Открыть chrome://extensions
2. Вверху отметить галку Developer mode/Режим разработчика
3. Найти расширение, под ним background page/фоновая страница
4. Откроется Developer Tools, откройте вкладку console
5. В поле для ввода внизу вставить `window.apis.pacKitchen.getPacMods().customProxyStringRaw` и нажать Enter

**Comment by pult** [comment]
Пасибки. Можно закрывать :)

**Comment by ilyaigpetrov** [comment]
При наличии DIRECT Хром заносит другие прокси в чёрные списки при отказе проксировать какой-либо адрес. Прокси может отказать по разным причинам, например, по соображениям безопасности. Чтобы избавиться от чёрных списков, временно прерывющих работу прокси и расширения, мы вырезаем DIRECT при включенной настройке _"Проксируй или умри"_ (в модификаторах, вкл. по умолчанию).

Я ещё подумаю, стоит ли давать пользователям возможность добавлят DIRECT в список своих прокси.  Спасибо за идею.

**Comment by pult** [comment]
Я таким образом(DIRECT) думал/хотел заставить игнорировать системные/виндовые настройки прокси.

**Comment by ilyaigpetrov** [comment]
В версии 0.0.1.1 DIRECT вырезается при миграции.
