### ISSUE TITLE
Добавить сайт Intel.com в список обходов

### ISSUE THREAD

**Issue by Kenya-West** [anticensority/runet-censorship-bypass#123]
Сайт Intel повесил заглушку-редирект для пользователей из России.

Иногда требуется скачать драйверы или скачать даташиты, желательно не прибегая к помощи тяжеловесного VPN и чтобы этим занималось более легковесное расширение, которое маршрутизирует трафик автоматически.

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.

**Comment by PukPukov** [comment]
>Сайты, которые по собственной инициативе блокируют доступ из РФ, в список [проекта "АнтиЗапрет"](https://antizapret.prostovpn.org/) не добавляются

Это получается правильная цензура?

**Comment by ilyaigpetrov** [comment]
Не особо силён в теории, но, думаю, это частная дискриминация по признаку страны. Возможно, это также и самоцензура.

Мы не берём на себя задачу вести реестр сайтов, блокирующих доступ из РФ по собственной инициативе. Просто потому, что это технически затратно. Если бы  затраты времени, усилий и др. ресурсов кто-то восполнил, то остаётся морально-идеологическая сторона вопроса, которую я не анализировал.
