### ISSUE TITLE
Забанены картинки аватаров Ютуба опять!

### ISSUE THREAD

**Issue by flagshipbowtie** [anticensority/runet-censorship-bypass#124]
Даешь фикс!

**Comment by ilyaigpetrov** [comment]
Подтвердите, что проблема всё ещё актуальная здесь: https://ntc.party/t/topic/2299.

**Comment by flagshipbowtie** [comment]
> Подтвердите, что проблема всё ещё актуальная здесь: https://ntc.party/t/topic/2299.

Не понимаю зачем это делать. Я об это говорю здесь. Прям как Кремлевская бюрократия какая то.

**Comment by ilyaigpetrov** [comment]
Я отвечаю за расширение. В расширении используется PAC-скрипт проекта "АнтиЗапрет", за которое отвечает другой человек. Он не подписан на этот репозиторий и не увидит вашей жалобы, если только вы не подтвердите проблему на форуме по приведённой мной ссылке.

**Comment by flagshipbowtie** [comment]
Уже включено. Отлично можно закрывать
