### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by Kozlov-AE** [anticensority/runet-censorship-bypass#127]
https://anticensority.github.io/error/0.0.0.17/?json=%7B%22ext-error%22%3A%7B%22message%22%3A%22TypeError%3A%20can%27t%20access%20dead%20object%22,%22filename%22%3A%22moz-extension%3A%2F%2F73387754-c850-49b6-aaa9-60c3fff895ba%2F37-sync-pac-script-with-pac-provider-api.js%22,%22lineno%22%3A57,%22colno%22%3A9,%22error%22%3A%7B%22fileName%22%3A%22moz-extension%3A%2F%2F73387754-c850-49b6-aaa9-60c3fff895ba%2F37-sync-pac-script-with-pac-provider-api.js%22,%22lineNumber%22%3A57,%22columnNumber%22%3A9,%22message%22%3A%22can%27t%20access%20dead%20object%22,%22name%22%3A%22TypeError%22%7D,%22type%22%3A%22error%22%7D%7D&type=ext-error&version=0.0.1.56&useragent=Mozilla%2F5.0%20(Windows%20NT%2010.0;%20Win64;%20x64;%20rv%3A100.0)%20Gecko%2F20100101%20Firefox%2F100.0&platform=Win32

**Comment by ilyaigpetrov** [comment]
Дубликат #91.
