### ISSUE TITLE
Не работает streamlabs.com (сайт за CloudFlare)

### ISSUE THREAD

**Issue by CortexReaver** [anticensority/runet-censorship-bypass#128]
![06-06-2022 183237](https://user-images.githubusercontent.com/34350690/172193768-7a127961-9f26-4edf-961b-324f2ac3cc62.png)

**Comment by CortexReaver** [comment]
Also https://nightdev.com/ doesn't work. Returns exactly the same error.

**Comment by ilyaigpetrov** [comment]
Попробуйте прописать в /etc/hosts:
104.16.132.0 [streamlabs.com](http://streamlabs.com/)

Вот вам пара изображений в помощь:
![etc-hosts-win-cmd](https://user-images.githubusercontent.com/1090811/172203206-76e35a09-10f6-4988-a973-7e9bfe78d2ed.png)
![etc-hosts-win-notepad](https://user-images.githubusercontent.com/1090811/172203209-ad84c5ed-01a1-411f-9e9a-94e616a159d8.png)

**Comment by ilyaigpetrov** [comment]
Нужно запустить командную строку от имени администратора.
Например, так: https://support.kaspersky.ru/common/windows/14637#block0.
Далее через notepad.exe открыть файл C:\Windows\System32\drivers\etc\hosts
и внести изменения.

**Comment by ilyaigpetrov** [comment]
Нужна помощь? Спрашивайте.

**Comment by CortexReaver** [comment]
Не, я разобрался :) Всё работает, спасибо (с той лишь разницей, что я по старинке правлю hosts блокнотом). Только как я понял, это какая-то пробелма с cloudflare и блокировки Роскомпозора тут вообще ни при чём.

**Comment by ilyaigpetrov** [comment]
РКН блочит некоторые IP, принадлежащие CloudFlare: см. https://ntc.party/t/cloudflare-cdn/2245.
