### ISSUE TITLE
Firefox DNS leak

### ISSUE THREAD

**Issue by koloved** [anticensority/runet-censorship-bypass#130]
https://2ip.ru/privacy/  - замечает утечку днс при включенном расширении в фаерфокс 
в edge не течет

**Comment by ilyaigpetrov** [comment]
В FireFox используется API proxy.settings [1]. Я не вижу в нём никаких
способов повлиять на утечку DNS.
SOCKS в АнтиЗапрете не используется, используются HTTP/PROXY и HTTPS.
Возможно, вам удастся предотвратить утечку через настройки браузера или ОС.
Стоит также напомнить, что расширение не предназначено для анонимного
сёрфинга (см. https://rebrand.ly/ac-security#user-content-Анонимность).

[1]:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings#:~:text=autoConfigUrl

**Comment by ValdikSS** [comment]
@koloved, что вы понимаете под утечкой DNS?

**Comment by Erghel** [comment]
> https://2ip.ru/privacy/ - замечает утечку днс при включенном расширении в фаерфокс в edge не течет

Как правильно подметил @ilyaigpetrov, в Firefox нельзя повлиять на утечку DNS. Если вы хотите обезопасить себя от данной проблемы, то вы самостоятельно можете зайти в настройки браузера > далее в настройки сети и выбрать режим DNS-over-HTTPS (Cloudflare) или использовать иного провайдера (AdGuard, Mullvad, Proton, Google и т.д)

**Comment by ValdikSS** [comment]
Браузер делает DNS-запрос как с расширением, так и без расширения, как и положено. Что подразумевается под _утечкой_ DNS? Почему вы считаете, что браузер не должен делать DNS-запросы?
Ни из сообщения @koloved, ни из @Erghel непонятны детали.

**Comment by Erghel** [comment]
> Браузер делает DNS-запрос как с расширением, так и без расширения, как и положено. Что подразумевается под _утечкой_ DNS? Почему вы считаете, что браузер не должен делать DNS-запросы? Ни из сообщения @koloved, ни из @Erghel непонятны детали.

Как я понял смысл этого запроса - пользователь спрашивает про то, что без вмешательства пользователя DNS запросы перадаются в открытую, можно увидеть провайдера, IP адрес и другие вещи. С помощью вмешательства пользователя DNS запросы можно спрятать за Clouflare или у иных провайдеров данной услуг. ИЛИ в настройках сети можно включить передачу запросов через SOCKS, так вот, я думаю, что пользователь хотел или передавать DNS запросы через ваш прокси или что-то иное. Тут только мои догадки.

**Comment by ilyaigpetrov** [comment]
Можно ещё настроить расширение так, чтобы на один запрос к DNS стало меньше:
![ac-prohibit-dns](https://user-images.githubusercontent.com/1090811/181042947-de5543dc-3d6e-4089-9034-c8f9a8715b0a.png).
