### ISSUE TITLE
Не работает со Steam: "Данный товар недоступен в вашем регионе"

### ISSUE THREAD

**Issue by vovkkk** [anticensority/runet-censorship-bypass#131]
Некоторые страницы не открываются с ошибкой «Данный товар недоступен в вашем регионе», например, Forza Horizon 5, Minecraft Dungeons, Fallout 4, Skyrim.
Через Hide my IP открываются.

**Comment by ilyaigpetrov** [comment]
К сожалению, с сайтами, которые по собственной инициативе блокируют доступ
для россиян, всё немножко сложнее: см. https://rebrand.ly/ac-own-sites.
