### ISSUE TITLE
Не работает bestbuy.com

### ISSUE THREAD

**Issue by CortexReaver** [anticensority/runet-censorship-bypass#134]
![Скриншот 20-07-2022 001211](https://user-images.githubusercontent.com/34350690/179849385-7e9d1e63-bdc0-4fd7-9bb2-c3099f211b50.png)

**Comment by ilyaigpetrov** [comment]
Скорее всего, они самостоятельно заблокировали сайт для пользователей из РФ.
Такую самоцензуру, идущую вне официального реестра, мы не обходим.
См. https://rebrand.ly/ac-own-sites.
