### ISSUE TITLE
Блокировка поисковика Google

### ISSUE THREAD

**Issue by DecartSystem** [anticensority/runet-censorship-bypass#136]
Властями моего региона заблокирован поисковик гугл. Через ваш плагин также не открывается

**Comment by vukitoso** [comment]
А вы откуда? Это где интересно заблокировали гугл?

**Comment by ilyaigpetrov** [comment]
> А вы откуда? Это где интересно заблокировали гугл?

@vebmaster, думаю, что это захваченные украинские территории. См. https://ntc.party/t/google/2874.

@DecartSystem, просить добавить что-либо нужно не у меня, а у создателя и админа "АнтиЗапрета" (адреса см. на https://antizapret.prostovpn.org). Вот его ответ по Google: https://ntc.party/t/google/2874/2.
