### ISSUE TITLE
Отдельный прокси для инстаграма

### ISSUE THREAD

**Issue by stlr00** [anticensority/runet-censorship-bypass#137]
Здравствуйте.
Я дабы не нагружать ваши сервера, я поднял себе свой самописынй прокси на nodeJS. Я беру список сайтов РКН, и проксирую его через .pac.
Я увидел в вашем скрипте отдельный прокси для инстаграма, фейсбука и т д.
И вот в чём вопрос. У меня на моём прокси наглухо отказывается работать instagram cdn. Сайт загружается, а фотки, видео и т д нет.
Хотел бы спросить у вас, раз вы используйте для инсты другой прокси, значит там немного другая логика, мб хендшейк  какой-то, как я в теории могу починить для своего прокси, по аналогии с вашим?

**Comment by stlr00** [comment]
https://scontent-hel3-1.cdninstagram.com/
Вот это конкретно никак не проксируется

**Comment by ilyaigpetrov** [comment]
https://reestr.rublacklist.net/search/?q=cdninstagram.com нужно проксировать со всеми поддоменами. У вас не так?

**Comment by stlr00** [comment]
> https://reestr.rublacklist.net/search/?q=cdninstagram.com нужно проксировать со всеми поддоменами. У вас не так?

У меня так. Как я вычитал из одного комментария на хабре, инстаграмм не работает с http прокси, впрочем если я просто поставлю сертификат на nodeJS, ничего не изменится. Там как-то хитро надо это делать. Как-то wild-cart сертификат ставить.

**Comment by ilyaigpetrov** [comment]
В расширении используются прокси и PAC-скрипт "АнтиЗапрета", их администратор не подписан на сообщения в данном репозитории. Я ему переслал ссылку на данное обсуждение пару дней назад. В дальнейшем вопросы по специфике работы прокси проекта "АнтиЗапрет" направляйте по адресам с https://antizapret.prostovpn.org.

**Comment by ilyaigpetrov** [comment]
Обсуждение продолжено здесь: https://ntc.party/t/proxy-instagram-cdn/2935.
