### ISSUE TITLE
Не работает на Яндекс.Браузере

### ISSUE THREAD

**Issue by Alex-00000** [anticensority/runet-censorship-bypass#138]
С середины дня 22 июля скрипт внезапно самовыключился. Утверждает, что "другое приложение контролирует настройки прокси". Однако ничего нового не устанавливалось, какие-либо настройки не производились. Windows 10, Яндекс.Браузер.

**Comment by ilyaigpetrov** [comment]
Попробуйте переустановить расширение, если ещё им пользуетесь.
