### ISSUE TITLE
Обновление ссылок на .onion сайты в Wiki

### ISSUE THREAD

**Issue by Erghel** [anticensority/runet-censorship-bypass#139]
Недавно заглянул в раздел Wiki и в [**пункте**](https://github.com/anticensority/runet-censorship-bypass/wiki/.onion,-.i2p,-OpenNIC#onion) заметил, что указаны ссылки V2, но относительно недавно был произведен переход на V3 домены. 

```
www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion

flibustaongezhld6dibs2dps6vm4nvqg2kp7vgowbu76tzopgnhazqd.onion
```
Вот корректные ссылки на 2/3 указанных (простите, про 3 ресурс впервые слышал, поэтому домена у меня нет)

**Comment by ilyaigpetrov** [comment]
Спасибо, заменил.

**Comment by Erghel** [comment]
> Спасибо, заменил.

Вам спасибо огромное!
