### ISSUE TITLE
Firefox 56

### ISSUE THREAD

**Issue by Alexey71** [anticensority/runet-censorship-bypass#14]
Привет. Вчера все работало с вашим https://github.com/anticensority/chromium-extension/wiki/PAC-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82-%C2%AB%D0%90%D0%BD%D1%82%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%BE%D1%80%D0%B8%D1%82%D0%B8%C2%BB-%D0%B4%D0%BB%D1%8F-FireFox-%D0%B8-Chrome
Сегодня не работает, на firefox android и frirefox pc
При нажатии на https://rebrand.ly/ac-anticensority-pac
![2017-09-08 12_23_19](https://user-images.githubusercontent.com/10572914/30205161-b430092c-9490-11e7-858e-be269bd54217.png)

**Comment by Alexey71** [comment]
А такая ссылка работает! https://github.com/anticensority/generated-pac-scripts/raw/master/anticensority.pac

**Comment by ilyaigpetrov** [comment]
Наш домен anticensority.tk просто взял и пропал с сервера freenom.com, остался только на cloudflare. Аренда истекала лишь в 2018, не могу понять из-за чего это могло произойти.
Rebrandly-ссылку поправил, спасибо за информирование.
