### ISSUE TITLE
Перестали открываться сайты

### ISSUE THREAD

**Issue by Ddesusama** [anticensority/runet-censorship-bypass#140]
Сегодня все перетсало работать (

**Comment by ghost** [comment]
same

**Comment by Teasin** [comment]
upd заработало

**Comment by Quaterberg** [comment]
> upd заработало

увы, не заработало, либо не для всех сайтов

UPD вроде да, заработало.

**Comment by Ddesusama** [comment]
Неа, не работает.

**Comment by ilyaigpetrov** [comment]
@Ddesusama, несколько часов назад была устранена неполадка, сейчас всё дложно работать. Если у вас не работает, то предоставьте больше информации о проблеме. Перед проверкой работоспособности не забывайте обновить PAC-скрипт.

**Comment by ilyaigpetrov** [comment]
Также перед проверкой стоит очистить кэш браузера: https://rebrand.ly/ac-clear-cache.

**Comment by vk282** [comment]
Не открывается инстаграм. Не могу обновить PAC-скрипты. Пишет:
 🔥 Ошибка!
Не удалось скачать PAC-скрипт с адресов: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ]. > Что-то не так с сетью, проверьте соединение. > Failed to fetch

Хотя с сетью все в порядке. Кеш чистил как указано по ссылке: https://rebrand.ly/ac-clear-cache.
Вот подробнее: 
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.55",
  "pup-ext-err": {
    "message": "Не удалось скачать PAC-скрипт с адресов: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:222:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:19",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  
вот лог:
_generated_background_page.html:1 Access to fetch at 'https://antizapret.prostovpn.org/proxy.pac' from origin 'chrome-extension://npgcnondjocldhldegnakemclmfkngch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
antizapret.prostovpn.org/proxy.pac:1          Failed to load resource: net::ERR_FAILED
_generated_background_page.html:1 Access to fetch at 'https://rebrand.ly/ac-antizapret-pac' from origin 'chrome-extension://npgcnondjocldhldegnakemclmfkngch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
rebrand.ly/ac-antizapret-pac:1          Failed to load resource: net::ERR_FAILED
237-sync-pac-script-with-pac-provider-api.js:56

Вот ссылка на скрин лога:
![Лог 1](https://user-images.githubusercontent.com/110788291/183310490-0a04e410-a119-44f9-b406-c896e776b4e1.jpg)

**Comment by ilyaigpetrov** [comment]
Попробуйте переустановить расширение, если это несложно.

**Comment by vk282** [comment]
Помогло, большое спасибо!
