### ISSUE TITLE
Не удается открыть эту страницу  adguard.com

### ISSUE THREAD

**Issue by genrihx2** [anticensority/runet-censorship-bypass#141]
Не удается открыть эту страницу  adguard.com   

![image](https://user-images.githubusercontent.com/3043207/182906389-58197d4e-d004-41df-9c23-008e3b641a48.png)

**Comment by ilyaigpetrov** [comment]
При первой проверке у меня тоже вадавал ошибку RESET, но сейчас adguard.com открывается без проблем.
Если у вас всё ещё RESET -- узнавайте причину ошибки у провайдера; сайта [нет в реестре](https://reestr.rublacklist.net/search/?q=adguard.com) и потому он нашими серверами не проксируется.

**Comment by genrihx2** [comment]
всем    работает vpn

**Comment by genrihx2** [comment]
Без  vpn  не  работает

**Comment by ilyaigpetrov** [comment]
Какой у вас провайдер?

**Comment by genrihx2** [comment]
провайдер  mgts  МТС HOME

**Comment by genrihx2** [comment]
![image](https://user-images.githubusercontent.com/3043207/183334762-3b50611f-760c-43ab-8a1c-1361dfa36a2e.png)

  всем блочить    domain

**Comment by ilyaigpetrov** [comment]
Обратитесь в службу поддержки провайдера и узнайте причину неработоспособности сайта. В реестре его [нет](https://reestr.rublacklist.net/search/?q=adguard.com). У меня в данный момент сайт работает без средств обхода блокировок.

**Comment by genrihx2** [comment]
всем работает     

![image](https://user-images.githubusercontent.com/3043207/183457625-fd0bdb23-3521-448f-bf71-d45922d0f53e.png)

**Comment by genrihx2** [comment]
я Обратитесь   adguard  службу поддержки

**Comment by ilyaigpetrov** [comment]
Насколько я понял, вы написали письмо в поддержку провайдера, и проблема была разрешена.
Если проблема возникнет снова, обратитесь к провайдеру вновь или, если это не поможет, то сюда.
