### ISSUE TITLE
Не удалось скачать PAC-скрипт с адресов:

### ISSUE THREAD

**Issue by Elhaina** [anticensority/runet-censorship-bypass#142]
К этой ошибке приводит следующая последовательность действий:
1. ...открываю браузер
2. ...🔥 Ошибка!
Не удалось скачать PAC-скрипт с адресов: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ]. > Получен ответ с неудачным HTTP-кодом 403. [Техн.детали]

картинки:
https://drive.google.com/file/d/18lZGmfXnG636vogEogFUVctlcTgvmWIt/view?usp=sharing
https://drive.google.com/file/d/1Q2scbY6_xX6XVyyhlTiIZ1uzHMNLEWZW/view?usp=sharing

я ничего не понимаю, просто вылезает и раздражает ошибка

**Comment by ilyaigpetrov** [comment]
Эта ошибка возникает из-за того, что вы используете PAC-скрипт "АнтиЗапрет" не с российского IP-адреса.
Действительно ли это так? Действительно ли вам нужно ипользовать нероссийский IP при работе с расширением?

**Comment by Elhaina** [comment]
да, я сейчас в Беларуси. Это получается выключать расширение?

**Comment by ilyaigpetrov** [comment]
Да.
