### ISSUE TITLE
Перестал работать антизапрет в Firefox

### ISSUE THREAD

**Issue by drozdov71** [anticensority/runet-censorship-bypass#143]
Уже несколько дней не работает антизапрет в Firefox.

Не получается ни с помощью ссылки  https://antizapret.prostovpn.org/proxy.pac

Ни с помощью расширения

Расширение дает следующую ошибку.  [https://anticensority.github.io/error/0.0.0.17/?json=%7B%22pup-ext-err%22%3A%7B%22message%22%3A%22Failed%20to%20download%20PAC-script%20from%20addresses%3A%20%5B%20https%3A%2F%2Fantizapret.prostovpn.org%2Fproxy.pac%20,%20https%3A%2F%2Frebrand.ly%2Fac-antizapret-pac%20%5D.%22,%22wrapped%22%3A%7B%22message%22%3A%22%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%20%D0%BE%D1%82%D0%B2%D0%B5%D1%82%20%D1%81%20%D0%BD%D0%B5%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%BC%20HTTP-%D0%BA%D0%BE%D0%B4%D0%BE%D0%BC%20403.%22,%22wrapped%22%3A%7B%7D%7D%7D%7D&type=pup-ext-err&version=0.0.1.56&useragent=Mozilla%2F5.0%20(Windows%20NT%2010.0;%20Win64;%20x64;%20rv%3A103.0)%20Gecko%2F20100101%20Firefox%2F103.0&platform=Win32](url)

Самое интересное, что на другом пк (mac) ссылка и расширение работают прекрасно.

**Comment by ilyaigpetrov** [comment]
Администратор АнтиЗапрета ввёл ограничение на локацию IP-адреса -- теперь
PAC-скрипт АнтиЗапрет работает и скачивается только для пользователей с
российскими IP.
