### ISSUE TITLE
Невозможно переключиться обратно на скрипт "Антизапрета"

### ISSUE THREAD

**Issue by mayorovp** [anticensority/runet-censorship-bypass#144]
К этой ошибке приводит следующая последовательность действий:
1. Открыть настройки PAC-скрипта
2. Переключиться на любой скрипт, кроме "Антизапрета" (например, "Отключить")
3. Попробовать переключиться обратно на "Антизапрет"

Браузер - Google Chrome 104.0.5112.81
ОС WIndows 10

Напрямую ссылка на PAC-скрипт в браузере открывается без проблем.

Детали ошибки:

```
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.55",
  "pup-ext-err": {
    "message": "Не удалось скачать PAC-скрипт с адресов: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:222:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:19",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  }
}
```

**Comment by ilyaigpetrov** [comment]
Несколько дней назад администратор АнтиЗапрета ввёл ограничение на локацию IP-адреса пользователя: работать с сервисом сейчас можно только с российского IP. Возможно, в этом причина. Если я ошибаюсь, то сообщите.

**Comment by DemitrixQ** [comment]
Странно, но при такой последовательности даже при включенном VPN (не Россия) у меня работает без проблем.Скорее всего ошибка из-за попытки блокировки сервиса.У вас случаем не включен фильтр наподобие NetPolice самим провайдером? Подключен ли ваш браузер к cloudflare в настройках сети

**Comment by mayorovp** [comment]
@ilyaigpetrov IP адрес у меня определённо российский. Причём, повторюсь, в браузере скрипт открывается.

@DemitrixQ фильтр бы заблокировал сам и открытие скрипта в браузере. Про cloudflare я не понял вопроса.

**Comment by ilyaigpetrov** [comment]
Пробовали переустановить расширение?

**Comment by mayorovp** [comment]
@ilyaigpetrov разумеется пробовал, помогло. То есть по умолчанию настройки работают и PAC-скрипт скачивается, проблема возникает если поменять настройку, а потом попытаться поменять обратно.

**Comment by ilyaigpetrov** [comment]
Можете через devtools получить код ошибки скачивания PAC-скрипта?

**Comment by ilyaigpetrov** [comment]
Или в логах поищите красные записи (ошибки): см. https://rebrand.ly/ac-logs.

**Comment by mayorovp** [comment]
Access to fetch at 'https://antizapret.prostovpn.org/proxy.pac' from origin 'chrome-extension://npgcnondjocldhldegnakemclmfkngch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Failed to load resource: net::ERR_FAILED

Access to fetch at 'https://rebrand.ly/ac-antizapret-pac' from origin 'chrome-extension://npgcnondjocldhldegnakemclmfkngch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Failed to load resource: net::ERR_FAILED

**Comment by ilyaigpetrov** [comment]
Вы используете ограничения на набор сайтов, с которым может работать расширение: см. https://rebrand.ly/ac-site-access?

**Comment by mayorovp** [comment]
@ilyaigpetrov да, использую

**Comment by ilyaigpetrov** [comment]
Либо отключите этот функционал, либо попробуйте добавить в список разрешённых antizapret.prostovpn.org.

**Comment by ilyaigpetrov** [comment]
А, там ещё перенаправление с antizapret.prostovpn.org на другие домены (ipfs-шлюзы, подсмотрите в https://rebrand.ly/ac-problems#user-content-Не-удалось-скачать-pac-скрипт-с-адресов--httpsantizapretprostovpnorgproxypac-). Я их не контролирую, админ АнтиЗапрета может изменить их в любое время по своему усмотрению.

**Comment by ilyaigpetrov** [comment]
Если что, в расширении есть функциональность белого списка: см. на вкладке "Исключения".

**Comment by ilyaigpetrov** [comment]
Насколько мне известно, эти ограничения применяются не ко всему расширению. Какой бы список в браузере вы не задали, он не влияет на работу PAC-скрипта, т.е. сайты из списка всё равно будут проксироваться.
