### ISSUE TITLE
Не удалось скачать PAC-скрипт с адресов

### ISSUE THREAD

**Issue by AveAcVale** [anticensority/runet-censorship-bypass#145]
Расширение приказало долго жить. Выдаёт ошибку
> Не удалось скачать PAC-скрипт с адресов: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ]. > Получен ответ с неудачным HTTP-кодом 403. 

При переходе по ссылке выдаёт ошибку "Your geoip is not RU, contact antizapret@prostovpn.org if you believe this is an error."

Всё бы ничего, но я живу во Владивостоке и я понятия не имею, как это IP не Российский. Тот же 2ip.ru говорит что всё норм - Россия, Владивосток.

**Comment by Monoblade** [comment]
Такая же проблема появилась в Vivaldi после того, как я его обновил вчера. Может и совпадение, но на двух других браузерах ссылки работают и скрипт качается.

**Comment by ilyaigpetrov** [comment]
@AveAcVale, пришлите ссылку на этот билет и ваш IP администратору АнтиЗапрета: antizapret@prostovpn.org.

**Comment by AveAcVale** [comment]
> @AveAcVale, пришлите ссылку на этот билет и ваш IP администратору АнтиЗапрета: [antizapret@prostovpn.org](mailto:antizapret@prostovpn.org).

Благодарю, я им уже писал, но ответа после IP не поступило, может как-то не так ответил, т.к. ответ на первое сообщение содержал некий OpenPGP_signature. Возможно мне тоже что-то было нужно прикрепить. Попробую ещё раз.
