### ISSUE TITLE
Error Failed to download PAC-script from addresses

### ISSUE THREAD

**Issue by weir1** [anticensority/runet-censorship-bypass#148]
I am getting this error for the last few weeks
tried uninstalling & installing it many times

Failed to download PAC-script from addresses: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ]. > Получен ответ с неудачным HTTP-кодом 403

**Comment by ilyaigpetrov** [comment]
It's because the administrator of the AntiZapret project restricted access
to his resources to requests from Russia only.
If you believe your ip address is Russian then send it to us via some
private channel (see email at antizapret.prostovpn.org).

**Comment by weir1** [comment]
Thanks for reply
I am not from Russia ...so it means I cant use it

**Comment by ilyaigpetrov** [comment]
You still can integrate the extension with tor or add your own proxies to
it and use a PAC-script different from AntiZapret, e.g. fatty Anticensority
or "Only own sites and only own proxies".
