### ISSUE TITLE
Ошибки при загрузке twitter.com

### ISSUE THREAD

**Issue by sofiered** [anticensority/runet-censorship-bypass#149]
Платформа win10, браузеры brave и vivaldi, провайдер билайн.

Виджет РКС считает, что страница не заблокирована, и разблокировать адрес не нужно, но некоторые критичные файлы не скачиваются и вместо них отдается 403 на русском языке с текстом "доступ к файлу запрещен".

Пример "заблокированного" файла с 403 ошибкой: https://twitter.com/i/api/1.1/account/settings.json?include_mention_filter=true&include_nsfw_user_flag=true&include_nsfw_admin_flag=true&include_ranked_timeline=true&include_alt_text_compose=true&ext=ssoConnections&include_country_code=true&include_ext_dm_nsfw_media_filter=true&include_ext_sharing_audiospaces_listening_data_with_followers=true

**Comment by ValdikSS** [comment]
Вы ошиблись расширением.

**Comment by ilyaigpetrov** [comment]
> Виджет РКС считает[...]

https://github.com/roskomsvoboda/censortracker ?
