### ISSUE TITLE
Добавите ли вы методы для обхода блокировок телеграм?

### ISSUE THREAD

**Issue by P4EJIA** [anticensority/runet-censorship-bypass#15]

**Comment by ilyaigpetrov** [comment]
Веб-версия Телеграм — да, если её занесут в список
https://github.com/zapret-info/z-i
Даже если не занесут в этот список, то можем занести в особый собственный
список.
Про десктопный клиент не скажу.

**Comment by P4EJIA** [comment]
Именно про десктоп и андроид версии интересно. 
Нельзя как-то узнать какие прокси использует расширение и вбить их в телегу?

**Comment by ilyaigpetrov** [comment]
Для Android можете установить как VPN или как PAC-скрипт: https://antizapret.prostovpn.org
Для десктопа, наверно, можно использовать тот же файл конфигурации `.ovpn`.

Также я отдельно переговорю про Telegram с владельцем прокси и сообщю, если будет отдельное решение (в виде прокси, например).

**Comment by ilyaigpetrov** [comment]
Отдельного решения для мессенджеров или Телеграм не планируется.
