### ISSUE TITLE
Error: TypeError: can't access dead object

### ISSUE THREAD

**Issue by pixpnd** [anticensority/runet-censorship-bypass#150]
![изображение](https://user-images.githubusercontent.com/24830656/188282559-0974d64e-0c21-4c56-a47d-7052aa3b0838.png)
При попытке обновить PAC скрипты, уходит в бесконечную петлю, периодически выдавая ошибку. Переустановка аддона ни к чему не привела, удаление выключенного ВПН аддона тоже. Прикладываю логи с ошибкой

**Comment by pixpnd** [comment]
UPD: обновился, но непонятно как долго проживет...

**Comment by ilyaigpetrov** [comment]
Это случается, если закрыть окно расширения до завершения запущенного вручную обновления PAC-скрипта.
Это ваш случай?

**Comment by pixpnd** [comment]
Внезапно, и да и нет. Проверил, ошибку выдает, логи вот такие. Но в таком случае расширение не падает, а успешно обновляет скрипт. Но вот изначальную ошибку воспроизвести сейчас не получается.
![изображение](https://user-images.githubusercontent.com/24830656/188282976-f5df666e-cada-4fb9-9613-2289ec2350b3.png)

**Comment by ilyaigpetrov** [comment]
Закрываю как дубликат #91.
