### ISSUE TITLE
Нет расширения фаерфокс андроид 

### ISSUE THREAD

**Issue by GODIMONGO** [anticensority/runet-censorship-bypass#151]
Расширение для фаерфокс нету под андроид:(

**Comment by GODIMONGO** [comment]
+ хотел запустить с помощью расширения магазин приложений хром к сожалению чот не пошло. Не подскажите в чем проблема магазина расширений хром? У вас работает он или нет? :(

**Comment by ilyaigpetrov** [comment]
Дубликат https://github.com/anticensority/runet-censorship-bypass/issues/86 ("Дополнение для Firefox на Android").
