### ISSUE TITLE
Ошибка "Другое расширение контролирует настройки прокси!"

### ISSUE THREAD

**Issue by Mavrein7** [anticensority/runet-censorship-bypass#154]
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.86",
  "platform": "Win32",
  "version": "0.0.1.55",
  "pup-ext-err": {
    "stack": "Error: Другое расширение контролирует настройки прокси! <a href=\"chrome://settings/?search=прокси\">\n            Какое?\n          </a>\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:156:13\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/11-error-handlers-api.js:154:13\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/00-init-apis.js:63:44",
    "message": "Другое расширение контролирует настройки прокси! <a href=\"chrome://settings/?search=прокси\">\n            Какое?\n          </a>",
    "name": "Error"
  }
}

К этой ошибке приводит следующая последовательность действий:
1. Включение антизапрета в PAC-скрипте
У меня нет никаких других включенных расширений контролирующих прокси :о
Ещё вчера всё работало

**Comment by ilyaigpetrov** [comment]
1) Можно ли игнорировать это сообщение и переключать PAC-скрипт (сначала отключить, затем включить "АнтиЗапрет")?
2) Попробуйте переустановить расширение. В данный момент скачивание и установка расширений с WebStore может сбоить или не работать вовсе, потому запаситесь каким-нибудь VPN для целей переустановки (можно бесплатный, но только не в виде расширения для браузера). Возможно, окажется полезной следующая страница: https://rebrand.ly/ac-alternatives.
3) Другим подходом будет очищение настройки PAC-скрипта. Для этого: иконка синей ленты -> Проблемы? -> Отладка PAC-скрипта -> Нажать CLEAR (очистить).

**Comment by Mavrein7** [comment]
Проблема сегодня решилась сама собой, вчера, по крайней мере, переустановка не дала никаких результатов

**Comment by nouret** [comment]
возникла аналогичная проблема, ещё и запрашивается логин/пароль к прокси серверу. Понять какое ещё расширение "создаёт" прокси невозможно.
