### ISSUE TITLE
Почему скрипт не обновляется при использовании VPN?

### ISSUE THREAD

**Issue by dodedov** [anticensority/runet-censorship-bypass#156]
Заметил, что скрипт удается обновить, только при отключении VPN. В чем причина блокировки обновления при использовании VPN?

**Comment by ilyaigpetrov** [comment]
Администратор antizapret.prostovpn.org решил ограничить действие его PAC-скрипта до России. Если у вас нероссийский IP, то сервер отдаёт ошибку 403.

**Comment by dodedov** [comment]
> Администратор antizapret.prostovpn.org решил ограничить действие его PAC-скрипта до России. Если у вас нероссийский IP, то сервер отдаёт ошибку 403.

Сервер выдает ошибку 403, но сервер VPN российский с российским IP. Может еще какие-то ограничения ведены, чисто под использование VPN или других подозрительных соединений?

Существуют настройка, чтобы например через свое прокси обновлять скрипт? Тор? Если предположить, что провайдер начнет блокировать обновление скрипта, то достучаться для обновления С VPN и без него будет сложно.

**Comment by ilyaigpetrov** [comment]
проверьте доступны ли следующие сайты/файлы:
   1. Сайт https://antizapret.prostovpn.org
   2. Сайт http://antizapret.prostovpn.org
   3. Файл https://antizapret.prostovpn.org/proxy.pac
   4. Файл https://cloudflare-ipfs.com/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about
   5. Файл https://gateway.ipfs.io/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about

**Comment by ilyaigpetrov** [comment]
> [...]сервер VPN российский с российским IP.

Проверьте доступны ли следующие сайты/файлы:
   1. Сайт https://antizapret.prostovpn.org
   2. Сайт http://antizapret.prostovpn.org
   3. Файл https://antizapret.prostovpn.org/proxy.pac
   4. Файл https://cloudflare-ipfs.com/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about
   5. Файл https://gateway.ipfs.io/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about

Напишите какие сайты/файлы у вас не открываются, какие открываются, какие ошибки возникают при попытке открытия.

Также убедитесь, что вы не используете прокси/VPN/туннели IPv6.

**Comment by dodedov** [comment]
> > [...]сервер VPN российский с российским IP.
> 
> Проверьте доступны ли следующие сайты/файлы:
> 
>     1. Сайт https://antizapret.prostovpn.org
> 
>     2. Сайт http://antizapret.prostovpn.org
> 
>     3. Файл https://antizapret.prostovpn.org/proxy.pac
> 
>     4. Файл https://cloudflare-ipfs.com/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about
> 
>     5. Файл https://gateway.ipfs.io/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about
> 
> 
> Напишите какие сайты/файлы у вас не открываются, какие открываются, какие ошибки возникают при попытке открытия.
> 
> Также убедитесь, что вы не используете прокси/VPN/туннели IPv6.

Не открывается только 3, с ошибкой:
`Your geoip is not RU, contact antizapret@prostovpn.org if you believe this is an error. Send your IP address in the message!!`

**Comment by ilyaigpetrov** [comment]
Какую страну показвает https://ifconfig.co для вашего российского VPN?

**Comment by dodedov** [comment]
![изображение](https://user-images.githubusercontent.com/76861384/190459364-cfcf5963-a031-4445-aa9b-8c4c016d15d6.png)

**Comment by ilyaigpetrov** [comment]
Пришлите IP вашего российского VPN администратору АнтиЗапрета: antizapret@prostovpn.org. Также добавьте в тело письма ссылку на данное обсуждение.
