### ISSUE TITLE
### Сокращатель ссылок https://rebrand.ly внереестрово заблочен

### ISSUE THREAD

**Issue by DemitrixQ** [anticensority/runet-censorship-bypass#157]
### Сокращатель ссылок https://rebrand.ly внереестрово заблочен

14.09.2022

Сокращатель ссылок https://rebrand.ly (https://rebrandly.com) заблочен вне реестра (на ТСПУ).
Мы использовали/используем их сервис, и из-за этой блокировки в расширении могут перестать работать многие ссылки (вы получите ошибку типа RESET_ERROR).

_Originally posted by @ilyaigpetrov in the news (https://rebrand.ly/ac-news)_

**Comment by DemitrixQ** [comment]
Не работает только https://rebrand.ly (Редирект). Основной сайт https://rebrandly.com запускается без проблем. Похоже на то что его  зацепило путем ковровой блокировки другого ресурса.

**Comment by ilyaigpetrov** [comment]
Добавили rebrand.ly в исключения PAC-скрипта АнтиЗапрет.
Обновите скрипт и попробуйте открыть https://rebrand.ly/ac-news, например.

**Comment by DemitrixQ** [comment]
Открывается  rebrand.ly теперь без всякой сложности.Думаю что можно закрывать данное обсуждение по данной теме.Проблема решена
