### ISSUE TITLE
Не работает больше на Chromium v.105

### ISSUE THREAD

**Issue by Flashwalker** [anticensority/runet-censorship-bypass#158]
На **Chromium** версии **105** расширение устанавливается и делает вид, что всё ok, но блокировки больше не обходит.
На **Chromium** версии **98** всё ещё обходит.

**Comment by ilyaigpetrov** [comment]
У меня на 105.0.5195.125 работает.
Попробуйте создать чистый профиль пользователя на 105 и установить у него
одно лишь наше расширение -- будет ли так работать?

**Comment by Flashwalker** [comment]
> У меня на 105.0.5195.125 работает. Попробуйте создать чистый профиль пользователя...

Попробовал, не помогло. Может дело в том, что я использую ungoogled-chromium
`ungoogled-chromium --user-data-dir=/tmp/tmp-chr-flt-dir`
[Peek 2022-09-20 10-25.webm](https://user-images.githubusercontent.com/2188215/191194031-a203d107-2454-49e6-9d09-b235706b9ecc.webm)

**Comment by Flashwalker** [comment]
В общем протестил, на **Ungoogle-Chromium** версии 105 и 106 официальной **Flatpak** сборки это расширение **не** проксирует.  
Проверил на неофициальных сборках **AppImage** и **.deb** пакет - там проксирует ok.  
Версии 106 и 100.

**Comment by Flashwalker** [comment]
https://github.com/ungoogled-software/ungoogled-chromium/issues/2102

**Comment by Flashwalker** [comment]
Короче [Ungoogle-Chromium flatpak версии не переваривает .pac файл почему-то](https://github.com/ungoogled-software/ungoogled-chromium/issues/2102#issuecomment-1312199538)

**Comment by Flashwalker** [comment]
Кароч эти рукожопы не осилили прокси во Flatpak
