### ISSUE TITLE
Перестала работать авторизация в Instagram

### ISSUE THREAD

**Issue by rex1q** [anticensority/runet-censorship-bypass#159]
Перестала работать авторизация в Instagram. Что-то можно с этим сделать? Скриншот прилагается.

![inst](https://user-images.githubusercontent.com/79162457/192144142-ff6e1de9-c44d-4b10-afbd-21bea48ad8f1.png)

**Comment by stanislawru** [comment]
Ну это ведь явно не только у @rex1q, почему все молчат? :-(

У меня вот тоже, только сообщение об ошибке конкретнее: “CSRF token missing or incorrect”. (?)

**Comment by ilyaigpetrov** [comment]
Попробуйте поискать на https://ntc.party: см. https://ntc.party/t/instagram/3312/6.
Это не проблема расширения, это ближе к проекту https://antizapret.prostovpn.org.
Администратор АнтиЗапрета не подписан на сообщения в этом репозитории.

**Comment by stanislawru** [comment]
@ilyaigpetrov, там нет решения. 🙁 Так нравится использовать расширение «Обход блокировок Рунета» в Chrome 🙏, а для Instagram'а он никак не работает 🙁, приходится только из-за этого держать Firefox с расширением ZenMate. 🤔

**Comment by ilyaigpetrov** [comment]
Возможно, это поможет: см. https://ntc.party/t/instagram/3647/15.

**Comment by stanislawru** [comment]
@ilyaigpetrov, спасибо за наводку. Это, конечно, чистое совпадение, но я только что вошёл в Instagram через Ваше расширение без каких-либо дополнительных манипуляций. 🤔

**Comment by ilyaigpetrov** [comment]
По ошибке CSRF попробуйте этот совет: https://ntc.party/t/instagram/3647/15.

**Comment by stanislawru** [comment]
@ilyaigpetrov, предложенное Вами решение действительно работает, спасибо! 🙏 Для своего удобства я сделал из него закладурку (bookmarklet):
`javascript:(function(){n=new Date;t=n.getTime();et=t+36E9;n.setTime(et);document.cookie='csrftoken='+document.body.innerHTML.split('csrf_token')[1].split('\\"')[2]+';path=\;domain=.instagram.com;expires='+n.toUTCString();})();`
но совсем идеально было бы, если бы Ваше разрешение делало это само. 🙏
