### ISSUE TITLE
Авторизация на прокси требуется!

### ISSUE THREAD

**Issue by iaandr** [anticensority/runet-censorship-bypass#16]
Добрый день,
При указании своего прокси, что очень полезно и нужно, нет настройки авторизации на прокси и я не могу использовать свой прокси (с включенной авторизацией для защиты от посторонних)!
Прошу доработать эту часть настроек так, чтобы можно было указывать пользователя и пароль для прокси авторизации (в том числе и для SOCKS5 прокси).
Это хорошо бы сделать до 1 ноября, когда публичные прокси начнут блокировать и придется переходить на частные закрытые с авторизацией.
Заранее спасибо.
--------
Good afternoon,
When I specify my personal proxy, which is very useful and necessary, there is no authorization setting for the proxy and I can not use my proxy (with authorization enabled to protect against outsiders)).
Please update this part of the settings so that we can specify the user and password for the proxy authorification (including for the SOCKS5 proxy).
It would be good to do this until November 1, when the public proxies start blocking and will have to switch to private closed proxies with authorization.
Thank you in advance.

**Comment by ilyaigpetrov** [comment]
Запароленные прокси работают, начиная с 1.6.
