### ISSUE TITLE
Не обновляется пак скрипт на новом ПК

### ISSUE THREAD

**Issue by kotik876554** [anticensority/runet-censorship-bypass#161]
[Ошибка](https://anticensority.github.io/error/0.0.0.17/?json=%7B%22pup-ext-err%22%3A%7B%22message%22%3A%22%D0%9D%D0%B5%20%D1%83%D0%B4%D0%B0%D0%BB%D0%BE%D1%81%D1%8C%20%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C%20PAC-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%20%D1%81%20%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%BE%D0%B2%3A%20%5B%20https%3A%2F%2Fantizapret.prostovpn.org%2Fproxy.pac%20,%20https%3A%2F%2Frebrand.ly%2Fac-antizapret-pac%20%5D.%22,%22wrapped%22%3A%7B%22message%22%3A%22%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%20%D0%BE%D1%82%D0%B2%D0%B5%D1%82%20%D1%81%20%D0%BD%D0%B5%D1%83%D0%B4%D0%B0%D1%87%D0%BD%D1%8B%D0%BC%20HTTP-%D0%BA%D0%BE%D0%B4%D0%BE%D0%BC%20403.%22,%22wrapped%22%3A%7B%7D%7D%7D%7D&type=pup-ext-err&version=0.0.1.55&useragent=Mozilla%2F5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit%2F537.36%20(KHTML,%20like%20Gecko)%20Chrome%2F106.0.0.0%20Safari%2F537.36&platform=Win32)

**Comment by ilyaigpetrov** [comment]
Вы должны находиться в РФ, чтобы использовать расширение.
Свою страну можно посмотреть на ifconfig.co, например.

**Comment by ilyaigpetrov** [comment]
Вам удалось решить проблему? В чём была причина?
