### ISSUE TITLE
не работает  animerus.xyz 

### ISSUE THREAD

**Issue by genrihx2** [anticensority/runet-censorship-bypass#162]
не работает    https://animerus.xyz
![image](https://user-images.githubusercontent.com/3043207/197027865-7e6223a0-1813-430f-8ff6-84277c1957ea.png)

**Comment by ilyaigpetrov** [comment]
В данный момент у меня сайт открывается и проксируется.
Если у вас всё ещё возникают проблемы с открытием этого сайта, то переоткройти данный билет.
