### ISSUE TITLE
Не удалось скачать PAC-скрипт с адресов.

### ISSUE THREAD

**Issue by TheAlive55** [anticensority/runet-censorship-bypass#166]
Сегодня появилась ошибка "Не удалось скачать PAC-скрипт с адресов". Как можно исправить? Пользуюсь не так давно Вашим плагином. Заранее спасибо за ответ!

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-1329973853.
