### ISSUE TITLE
pleer.net: The requested URL could not be retrieved (проблема на стороне сайта)

### ISSUE THREAD

**Issue by merdzd** [anticensority/runet-censorship-bypass#17]
http://pleer.net/
ERROR
The requested URL could not be retrieved
The following error was encountered while trying to retrieve the URL: http://pleer.net/
Connection to 8.8.8.8 failed.
The system returned: (110) Connection timed out
The remote host or network may be down. Please try the request again.
Your cache administrator is antizapret@prostovpn.org.
Generated Thu, 26 Oct 2017 11:55:55 GMT by proxy-fr2-ssl.antizapret.prostovpn.org (squid/3.5.20)

"userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.5"
+ 
FFox 

ОШИБКА
Запрошенный URL не может быть получен
При получении URL http://pleer.net/news/13 произошла следующая ошибка
    Соединение с 8.8.8.8 не удалось
Система вернула: (110) Connection timed out
Удаленный узел или сеть недоступен. Повторите запрос позднее
Администратор Вашего кэша: webmaster.
Создано Thu, 26 Oct 2017 11:55:42 GMT на gw1 (squid/3.5.24)

**Comment by ilyaigpetrov** [comment]
Я думаю, что кто-то сменил IP-адрес pleer.net на 8.8.8.8, который принадлежит Google. Напишите автору pleer.net, спросите, почему так произошло. Вряд ли я чем-то тут могу помочь, проблема на стороне сайта.
