### ISSUE TITLE
TypeError: Can't Access Dead Object и Error! Failed to download PAC-script from addresses 

### ISSUE THREAD

**Issue by SladkiyKolobok** [anticensority/runet-censorship-bypass#178]
Столкнулся сегодня с такой вот проблемой, не работает скрипт, при нажатии на расширение открывает стандартное окно с PAC-скриптами и пишет, что оно обновляется, но через некоторое время в браузере просто выдаётся ошибка TypeError: Can't Access Dead Object. Через меню браузера с расширениями при обновлении пишет Error! Failed to download PAC-script from addresses.

Что я пробовал:
1. Переустановка расширения не помогла.
2. Установка расширения в другом браузере не помогла, выдаются аналогичные ошибки.
3. Пробовал установить альтернативный обход для браузера, который не смог разблокировать сайты.

Не знаю, что мне нужно сделать, чтобы всё заработало. Прикрепляю картинки с тем, как это у меня выглядит
![image](https://user-images.githubusercontent.com/77969192/230877695-45266a70-0676-4c54-9546-fe8038b3fe47.png)
![image](https://user-images.githubusercontent.com/77969192/230877780-16ba926f-d801-4a54-9bf2-28c968a5bda5.png)

**Comment by ilyaigpetrov** [comment]
У нас поломка -- следите за
https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-1501501105
.
