### ISSUE TITLE
Поддержка Firefox 60+

### ISSUE THREAD

**Issue by Object905** [anticensority/runet-censorship-bypass#18]
Firefox 57 вышел в stable и перешел на Web Extension. Все довольно просто, proxy API PAC скрипты поддерживает. Изменения в основном коснутся неймспейсов.

Подробнее https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

Будет время займусь сам (не очень скоро), если никто не заинтересуется.

**Comment by ilyaigpetrov** [comment]
Если бы не нависшая угроза забанить наши сервера, то однозначно отдался бы портированию. А так ещё неясно -- ты его портируешь, а на следующий день нас забанят.

**Comment by ilyaigpetrov** [comment]
По любым вопросам -- пишите на почту, можете деже мессенджер взять, помогу разобраться в коде.

**Comment by ilyaigpetrov** [comment]
https://github.com/anticensority/chromium-extension/tree/firefox-port
Сюда можно pull-request сделать.

**Comment by ilyaigpetrov** [comment]
Нужен аналог `chrome.proxy.settings.set`, вот есть `proxy.register(url)`:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy/register:
> url -- URL pointing to the PAC file to load. PAC files must be bundled with the extension, and url must be relative to the extension's manifest.json file.

У нас PAC-файлы постоянно обновляются с сервера и паковать их вместе с расширением мы не можем.

**Comment by ilyaigpetrov** [comment]
Первый рабочий порт, но всё равно лучше, чем на хроме работать не будет по ряду причин.

**Comment by ilyaigpetrov** [comment]
Альфа: https://addons.mozilla.org/en-US/firefox/addon/%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%BA-%D1%80%D1%83%D0%BD%D0%B5%D1%82%D0%B0-%D0%B0%D0%BB%D1%8C%D1%84%D0%B0/

**Comment by ilyaigpetrov** [comment]
Баг с неоткрыванием опций при установке зависит от этого билета: https://bugzilla.mozilla.org/show_bug.cgi?id=1420606
Происходит из-за того, что `window.location.hash` присваивается значение.

**Comment by ilyaigpetrov** [comment]
Они сняли расширение с магазина, т.к. у них появились подоздрения к безопасности кода.

**Comment by ilyaigpetrov** [comment]
Firefox-порта не будет, т.к. по мерам безопасности нелокальные PAC-скрипты запрещены:
> Using remote PAC files is not allowed.
https://wiki.mozilla.org/Add-ons/Reviewers/Guide/Reviewing#Policies_and_Actions_3

**Comment by ilyaigpetrov** [comment]
Чтобы сделать расширение для Firefox, придётся написать серверные скрипты, подготавливающие данные с https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv в каком-то виде, употребляемые Firefox-расширением. Это всё равно, что новое расширение написать. Я этого делать пока не хочу.

**Comment by sergeevabc** [comment]
Прошёл год. Может быть, что-то изменилось к лучшему?

**Comment by ilyaigpetrov** [comment]
В документации чётко сказано, что PAC-скрипт должен устанавливаться через URL к локальному файлу:
> URL pointing to the PAC file to load. PAC files must be bundled with the extension, and url must be relative to the extension's manifest.json file.  

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/register#Parameters

Так что установить один из наших PAC-скриптов выходит только через хаки типа `eval`, что противоречит политикам безопасности магазина FireFox.

**Comment by ilyaigpetrov** [comment]
2018-05-09 выпустили Firefox 60 -- в нём есть [proxy.settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/settings) и параметр `autoConfigUrl`. Работает так:
```js
chrome.proxy.settings.set({
  value: {
    proxyType: 'autoConfig',
    autoConfigUrl: 'https://antizapret.prostovpn.org/proxy.pac',
  }
}, console.log);
```
Жаль, что я раньше не заметил.

**Comment by ilyaigpetrov** [comment]
Первая тестовая версия для самых нетерпеливых: https://github.com/anticensority/runet-censorship-bypass/releases/tag/0.0.1.43-test1. Об ошибках и неисправностях лучше сообщать не сюда, а в новосозданный билет.

**Comment by ilyaigpetrov** [comment]
Прошёл проверку и опубликовал версию для тестирования 0.0.1.45 в магазине: https://addons.mozilla.org/addon/обход-блокировок-рунета (короткая ссылка: https://rebrand.ly/rcb-firefox).

В ней распирает интерфейс --, думаю, что это связано с этим багом: https://bugzilla.mozilla.org/show_bug.cgi?id=1671778.
Также в ней что-то не так с размером шрифта.

**Comment by ilyaigpetrov** [comment]
Предлагаю всем заинтересованным проголосовать за исправление бага, из-за которого распирает интерфейс расширения.
Для этого нужно:
1) Зайти на https://bugzilla.mozilla.org/show_bug.cgi?id=1671778.
2) Авторизоваться.
3) В разделе "Details" нажать на кнопку "Vote", поставить галочку и нажать "Change My Votes".
![bugzilla-vote-for-bug](https://user-images.githubusercontent.com/1090811/97027228-f27ce780-1549-11eb-89fe-83fd5ee6559a.png)

Возможно, это будет не единственный баг, который мешает нормальной работе расширения -- новые баги я буду публиковать в этой переписке.

**Comment by ilyaigpetrov** [comment]
Я опубликовал список багов и ограничений, мешающих нормальной работе расширения, здесь: https://github.com/anticensority/runet-censorship-bypass/issues/76.
Вдруг вы пропустили.
Благодарю за содействие.

**Comment by ilyaigpetrov** [comment]
В опубликованной версии 0.0.1.49 заработал PAC-скрипт "Антицензорити".
Билет для обсуждения: https://github.com/anticensority/runet-censorship-bypass/issues/77.

**Comment by macktab** [comment]
Спасибо, товарищи.

**Comment by ilyaigpetrov** [comment]
В опубликованной только что версии 0.0.1.52 окно расширения больше не распирается.
Также с расширения сната метка "экспериментельное".
https://rebrand.ly/ac-firefox
