### ISSUE TITLE
Что делать с новостями о блокировке?

### ISSUE THREAD

**Issue by lynrayy** [anticensority/runet-censorship-bypass#180]
Спасибо за инфу, она прикольная конечно. Но что с этим делать?
![image](https://user-images.githubusercontent.com/59417884/230932769-d2f4f5a8-1e25-40b5-8526-8b4a7663db67.png)

**Comment by ilyaigpetrov** [comment]
Наше решение не работает.
Я довожу эту информацию до пользователей, чтобы они не тратили время в
поисках причины поломки самостоятельно и не писали нам кучу писем.
За этой информацией нужно просто наблюдать и ждать, пока проблема
разрешится (успехом или провалом).
