### ISSUE TITLE
Пропадает бейджик на иконке в тулбаре (и информация о проксируемом сайте во всплывающей подсказке)

### ISSUE THREAD

**Issue by artquest** [anticensority/runet-censorship-bypass#181]
Иногда пропадает бейджик с количеством разблокированных сайтов, и во всплывающей подсказке нет указания, что сайт (сайты) проксируются. Вот сейчас бейджиков и информации о проксировании нет, хотя само проксирование (и через скрипт, например, [Лостфильм](https://www.lostfilm.tv/), и через свои прокси, например, [ChatGPT](https://chat.openai.com/)) идет исправно. Через какое-то время бейджик и информация появятся снова.
Не подскажете, с чем это может быть связано?

**Comment by ilyaigpetrov** [comment]
Дубликат / Dupes https://github.com/anticensority/runet-censorship-bypass/issues/75.

**Comment by ilyaigpetrov** [comment]
Duplicate of https://github.com/anticensority/runet-censorship-bypass/issues/75.

**Comment by ilyaigpetrov** [comment]
Duplicate of https://github.com/anticensority/runet-censorship-bypass/issues/75.
