### ISSUE TITLE
не  load  Изображения 

### ISSUE THREAD

**Issue by genrihx2** [anticensority/runet-censorship-bypass#185]
не  load Изображения

https://steamcommunity.com/app/4000/workshop/?l=russian 

![image](https://user-images.githubusercontent.com/3043207/235363180-efc4d641-2b00-4b40-bc42-0ccc25b3e553.png)

![image](https://user-images.githubusercontent.com/3043207/235363214-1d74964e-b6dc-43bd-b7bf-431a07883c60.png)

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/issues/175.

**Comment by ilyaigpetrov** [comment]
Duplicate of #175
