### ISSUE TITLE
В приватном окне нет меню!

### ISSUE THREAD

**Issue by PhoenixIndigo** [anticensority/runet-censorship-bypass#186]
В приватном окне не работает окно расширения!
<details><summary>Details</summary>
<p>

![изображение](https://user-images.githubusercontent.com/107413021/235665963-417ebf90-dcf8-4a87-8ea5-348aac8fb399.png)

</p>
</details>

**Comment by ilyaigpetrov** [comment]
Спасибо, совсем забыл про этот баг: #169.

**Comment by ilyaigpetrov** [comment]
Duplicate of #169
