### ISSUE TITLE
Microsoft Edge начал блокировать расширение.  

### ISSUE THREAD

**Issue by stasink** [anticensority/runet-censorship-bypass#189]
**Microsoft Edge** начал блокировать расширение.  Теперь оно устанавливается но включить **Его** невозможно.

**Comment by ilyaigpetrov** [comment]
Что происходит при попытке включения?
Пришлите снимок экрана, если на нём видна неисправность.

**Comment by Andrei030x** [comment]
Самое простое и универсальное решение:
Снести мусор от мелкомягких и поставить нормальный браузер, вроде:
[Brave](https://brave.com/ru/) (как chrome, но без [троянов](https://habr.com/ru/articles/411251/))
[LibreWolf](https://librewolf.net/) (форк firefox, без телеметрии)
