### ISSUE TITLE
Соединение с nnm-club.name не удалось, ошибка с синим спрутом

### ISSUE THREAD

**Issue by maxvlas** [anticensority/runet-censorship-bypass#19]
Не знаю куда лучше писать, решил здесь, если что удалите.
С сайтом проблема или с расширением не пойму (скорее всего с расширением).
При включенном расширении **Обход блокировок Рунета**  иногда нормально работает сайт http://nnm-club.name/ , но спустя время появляется такое
![2017-11-18_182230](https://user-images.githubusercontent.com/11572859/32982003-73b3bc00-cc8e-11e7-9e9c-f9f7df49e9cb.png)
Включаю другое расширение для интереса [https://chrome.google.com/webstore/detail/skyzip-proxy/hbgknjagaclofapkgkeapamhmglnbphi](url)
начинает работать.
Сегодня много раз так было, то нормально, то не показывает.
Когда начал писать письмо не работал , сейчас обновил сайт опять заработал

**Comment by ValdikSS** [comment]
Проблема с nnm-club. У меня и без использования серверов антизапрета он частенько не отвечает. Попробую написать администраторам, но они и так об этом, скорее всего, знают.

**Comment by maxvlas** [comment]
Да может быть и с nnm-club.
Заметил еще с многими сайтами (nnm-club.name/ , rutracker.nl , qiqru.org ) на значке расширения ничего не отображает (как будто они не заблокированны)

**Comment by ilyaigpetrov** [comment]
__Запросы по проблемам сайтов лучше всего присылать сюда: https://rebrand.ly/ac-contact.__
