### ISSUE TITLE
Soundcloud.com

### ISSUE THREAD

**Issue by 25hz** [anticensority/runet-censorship-bypass#192]
Не удается отправить комментарии,через сторонний впн все спокойно отправляется
Ошибка 400
![изображение](https://github.com/anticensority/runet-censorship-bypass/assets/104431049/29cd0cf9-930c-42cd-b74b-5d6603ccbdaf)

**Comment by ilyaigpetrov** [comment]
Ошибка 400 (плохой запрос / bad request) -- это когда серверу soundcloud не нравится ваш запрос.
Попробуйте написать в поддержку сервиса, 1) объяснив, что вы используете прокси, 2) предоставив ссылку [1] с информацией о нашх прокси, 3) предоставив скриншот ошибки, а лучше -- ещё и HAR-архив с записью ломающегося запроса (записывается через devtools браузера).

[1]: https://antizapret.prostovpn.org/do-not-block-this-proxy/

**Comment by ilyaigpetrov** [comment]
См. https://ntc.party/t/403-soundcloud/4787.
