### ISSUE TITLE
Не удаляется расширение

### ISSUE THREAD

**Issue by manulove** [anticensority/runet-censorship-bypass#195]
После удаления продолжает работать

**Comment by ilyaigpetrov** [comment]
Попробуйте очистить кэш: https://github.com/anticensority/runet-censorship-bypass/wiki/Как-очистить-кэш-в-Хроме-через-DevTools%3F.

Иконка расширения на chrome://extensions у вас пропала после удаления?

**Comment by manulove** [comment]
> Попробуйте очистить кэш: [https://github.com/anticensority/runet-censorship-bypass/wiki/Как-очистить-кэш-в-Хроме-через-DevTools%3F](https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%9A%D0%B0%D0%BA-%D0%BE%D1%87%D0%B8%D1%81%D1%82%D0%B8%D1%82%D1%8C-%D0%BA%D1%8D%D1%88-%D0%B2-%D0%A5%D1%80%D0%BE%D0%BC%D0%B5-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-DevTools%3F).
> 
> Иконка расширения на chrome://extensions у вас пропала после удаления?

Очистка кэша не помогала. Иконки нигде нет. Расширение удалялось полностью. Помог только полный сброс настроек браузера
