### ISSUE TITLE
Не работает прокси rutracker.org

### ISSUE THREAD

**Issue by NikKovIos** [anticensority/runet-censorship-bypass#199]
Шаги воспроизведения:

1) Установить расширение в chrome Версия 101.0.4951.64 (Официальная сборка), (x86_64)
2) Ограничить доступ расширению для всех сайтов
3) Зайти на http://rutracker.org/
4) Тап правым кликом на расширение - "расширение может получать доступ к данным сайта и изменять их" - "rutracker: вкл"
5) перезагрузить страницу rutracker

На выходе не грузится
Ожидается что будет грузится

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Доступ-к-сайтам-только-%22При-нажатии%22-|-Site-access-only-%22On-click%22.
Вы можете использовать белые списки для проксирования только выбранных
сайтов -- см. вклудку "Исключения / Exceptions".
