### ISSUE TITLE
Угроза блокировки серверов

### ISSUE THREAD

**Issue by ghost** [anticensority/runet-censorship-bypass#20]
Привет. Сразу сообщу, что я не программист и не понимаю как это все работает.
Считаю что РКН рано или поздно закроет доспут к серверам. Но куда еще более серьезная угроза - удалят расширения из Магазина расширений (для РФ).
Поэтому как юзер технологии, интересуюсь планами и видением ситуации.
Ваши прокси шикарны, очень стабильны, но если заблокируют прямой доступ?
Вы опытные ребята, посоветуйте дешевые прокси (на всякий случай) или где можно купить.
Использую только 4-5 заблокированных сайтов, веб-серфинг (тяжелого контента нету, рутрекер, кинозал, оппозиционные сайты для новостей)
Или может есть способ получше как покупка прокси.

**Comment by ilyaigpetrov** [comment]
Некоторое (длительное) время можно будет пользоваться VPN (есть
бесплатные), пока их тоже не перезакрывают. Например,
https://www.cyberghostvpn.com (уже платный)
Tor будет работать очень долго и для него всегда будут обходные пути.
