### ISSUE TITLE
добавьте, пожалуйста, обход блокировки Coursera

### ISSUE THREAD

**Issue by vitaemagistra** [anticensority/runet-censorship-bypass#200]
Не знаю, возможно ли, но было бы круто, если бы на Coursera можно было заходить без впн, получать финансовую помощь и проходить потом курсы без впн. Просто предложение.

**Comment by ilyaigpetrov** [comment]
Ваш провайдер блокирует coursera.org или какие-то другие адреса? Какие именно?

**Comment by vitaemagistra** [comment]
Курсера заблокировала россиянам получение финансовой помощи (бесплатное прохождение курса), возможность оплаты курсов и доступ к контенту как тесты, задания и т.д. С оплатой, наверное, ничего не поделать, но остальное можно получить через Тор, но он едва грузит.
--
Отправлено из Mail.ru для Android четверг, 31 августа 2023г., 13:43 +08:00 от ilyaigpetrov  ***@***.*** :

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.
