### ISSUE TITLE
Сделайте так чтобы при включении Проксировать .onion, .i2p для .onion and .i2p адресов использовались порты 9050 и 4444

### ISSUE THREAD

**Issue by kotenok2000** [anticensority/runet-censorship-bypass#201]

**Comment by ilyaigpetrov** [comment]
Для .onion должно быть достаточно выставить "использовать СВОЙ локальный Tor" на вкладке "Свои прокси".
Для .i2p попробуйте добавить в расширение свой прокси на localhost с нужными вам типом и портом.
