### ISSUE TITLE
omv wiki to pac list

### ISSUE THREAD

**Issue by mcgr0g** [anticensority/runet-censorship-bypass#203]
у OpenMediaVault обновились экстра плагины, решили отказаться от Portainter и свою балалайку Compose написать.
Были куцие мануалы на форуме, но говорят более полноценный мануал живет у них на вики:
https://wiki.omv-extras.org/doku.php?id=omv6:omv6_plugins:docker_compose
А хост как раз уходит в самоблокировку по национальному признаку.
Пока не под Antizapret ни под Anticenzority PAC листом не открыть. Можете добавить вкуда-нибудь?

P.S. А задумка отказаться от портейнера у них стремная, их балалайка умеет только базовые вещи. Не сказал бы что проще дебажить павшие контейнеры стало.

**Comment by ilyaigpetrov** [comment]
Из Тор-браузера открывается?
Можно Тор интегрировать в расширение и прописать исключение на вкладке "Исключения / Exceptions"
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.

**Comment by mcgr0g** [comment]
При должном усердии смогу поднять tor или найти free proxy.
Я верно понял, что ресурсы с нацсамоблокивкой - не будут добавляться в Anticenzority PAC лист?

**Comment by ilyaigpetrov** [comment]
Не будут, но вы можете добавить их вручную на вкладке "Исключения".

**Comment by mcgr0g** [comment]
Принято. Давайте закроем issue.
