### ISSUE TITLE
Не работает bbc.co.uk

### ISSUE THREAD

**Issue by glow12121** [anticensority/runet-censorship-bypass#208]
Добрый вечер! Не работает сайт bbc.co.uk, плагин на него не реагирует. Хотя остальные заблокированные сайты открываются.

Использую браузер "Вивальди" (на базе "Хрома").

**Comment by ilyaigpetrov** [comment]
bbc.co.uk блокируется на ТСПУ, в реестре его нет.
PAC-скрипт "АнтиЗапрет" не обходит ТСПУ-блокировки.
Вы можете либо переключиться на PAC-скрипт "АнтиЦензорити" и использовать его с тором или своими проксями,
либо остаться на АнтиЗапрете, но добавить сайт в проксируемые на вкладке исключений, но свои прокси или тор здесь тоже понадобятся.
