### ISSUE TITLE
Обход внешних блокировок

### ISSUE THREAD

**Issue by glow12121** [anticensority/runet-censorship-bypass#209]
Почему бы не включить в список разблокируемых сайтов те, которые сами блокируют Россию? Например, хотел зайти на фанатский сайт музыканта [www.muslimgauze.org](http://www.muslimgauze.org), но он недоступен русским пользователям.

**Comment by ilyaigpetrov** [comment]
1) Кто-то должен содержать реестр таких сайтов в актуальном состоянии.
2) Заблоченных РКН сайтов и без того втиснуто в скрипты по полной: АнтиЗапрет старается быть меньше 1MB для более широкой работоспособности в старом ПО, а АнтиЦензорти без того довольно пухлый и тормознутее.
3) Идеологические конфликты. Станет ли гугл удалять такие расширения из WebStore, как это планируется сейчас с блокировщиками рекламы.
