### ISSUE TITLE
Касперский ругается

### ISSUE THREAD

**Issue by Snacus1** [anticensority/runet-censorship-bypass#21]
Добрый день, установил ваше расширение для Хрома, и при попытке посещения заблокированного сайта у меня постоянно ругается касперский:

Название объекта
HEUR:Trojan.Script.lframer
Объект
hhtp://metrka.com/d/libs/jquery.min.js

Можете как-то прокомментировать? Это касперыч в очередной раз пытается перебдеть?

**Comment by ilyaigpetrov** [comment]
Заблокированный сайт пытается загрузить `http://metrka.com/d/libs/jquery.min.js`, на что ругается Касперский. Думаю, так.
