### ISSUE TITLE
Не обходит PAC-скриптом сайт https://natours.dev/

### ISSUE THREAD

**Issue by Gennady-G** [anticensority/runet-censorship-bypass#210]
Добрый день!

Собственно сабж:
не открывает сайт https://natours.dev/ 

(сам сайт работает, тк через первый онлайн прокси из гугла он открывается..)

![ы-2023-12-12_200656](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/f45903a0-1059-4c75-a669-b25079a6a859)

С уважением

**Comment by ilyaigpetrov** [comment]
А ping-admin говорит, что сайт не работает для всего Интернета:
см.
https://ping-admin.com/free_test/result/170239734155jn75764i3xy3gh5507c.html
.

**Comment by Gennady-G** [comment]
Очень интересно оО. Днём он открывался.
но сейчас у меня и сам croxyproxy.com не открывается, через который сегодня получалось..

и что странно он пингуется 🤷‍♀️
![err-2023-12-13_012912](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/30de91a6-a020-4e6a-bc60-fdbea5fca049)

**Comment by Gennady-G** [comment]
Перепроверил сегодня, ничё не поменялось.. 

![2023-12-13_165704](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/4ece73db-cdb0-40ae-8be5-4275e96d8a6c)

Ну раз получается что не подтверждается то тогда закрываю.
Извините что отвлёк)

**Comment by Gennady-G** [comment]
Вроде обдуплился 🙆‍♀️
https://ping-admin.com/free_test/result/1703088676jsw739mgee4p438c0tf102.html

![nat-2023-12-20_201354](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/1d8ff773-da97-46b4-85bc-fcb4ccae69f7)

открывается через сайт CroxyProxy, но не через антизапрет/антизапрет мини

Mini при этом не обновляет Antizapret:

![prob-2023-12-20_201749](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/d4cbc89a-6c55-468e-bbe4-563639ff7576)

**Comment by ilyaigpetrov** [comment]
А что в технических деталях ошибки обновления на mini?
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Частые-проблемы#не-удалось-скачать-pac-скрипт-с-адресов--httpsantizapretprostovpnorgproxypac%2D.

> Вроде обдуплился 🙆‍♀️

Вы добавили "www": www.natours.dev.
У меня по этому адресу ошибка Timeout.
http://www.natours.dev при этом открывается через curl, но не httpS.
Последний узел в трассировке принадлежит Amazon.

Пока не знаю, что с этим делать. Нужно понять, где происходит блокировка: на провайдерском ТСПУ или сам сайт отказывает запросам с российских IP.

**Comment by Gennady-G** [comment]
Сам сайт впринцыпе не так важен - это демо сайт с видекурсов. Просто странно..

Покурил ваш сайт - на чистом профиле Антизапрет мини апдейтится.. 👀

А как понять "нечистый профиль" - получается какие-то баги накопились в самом Chrom-е?..

![err-2023-12-21_174221](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/bd7fa0cc-ce2a-4635-b91f-caa3ab2d7967)

Сам лог такой:

![log-2023-12-21_173551](https://github.com/anticensority/runet-censorship-bypass/assets/5569346/3119f82c-6df2-4c77-acff-d3552a123712)

**Comment by ilyaigpetrov** [comment]
> [...]получается какие-то баги накопились в самом Chrom-е?

Да. И непонятно, как их воспроизвести, чтобы билет в багтрэкере открыть.

**Comment by Gennady-G** [comment]
Понял. Спасибо!
Тогда получается я пошёл грохать профиль/перставлять хром, и накатывать все екстеншены сызнова..
