### ISSUE TITLE
Сломался постинг на 4chan

### ISSUE THREAD

**Issue by sanscriptum** [anticensority/runet-censorship-bypass#212]
В связи с закрытием второстепенного домена 4channel, 4chan теперь отправляет ошибку про заблокированный IP range при попытке постинга, что означет что расширение пытается проксировать их бакэнд для постинга. Прошу добавить их в список исключений. До этого все работало и постинг шел из моего реального IP адреса. Постинг так же работает если расширение отключено.

**Comment by ilyaigpetrov** [comment]
Вам нужно узнать адрес, используемый для постинга, и добавить его в исключения: иконка синей ленты -> Исключения -> Ввести адрес -> Выбрать "нет" (не проксировать). Справитесь?

Не совсем соответствующая вашей цели статья, которая всё же может пригодиться для выявления адреса: https://github.com/anticensority/runet-censorship-bypass/wiki/Чиним-сайты-со-сломанными-элементами.

Также можно попробовать так: иконка синей ленты -> Исключения -> Собирать последние ошибки сайтов -> Запостить и получить ошибку -> Посмотреть в последних ошибках адрес.

**Comment by sanscriptum** [comment]
Я перепробовал различные варианты:

```
*.4chan.*
*.boards.4channel.org
sys.4channel.org
4chan.org
*.boards.4chan.org
4cdn.org
*.4cdn.org
```  

Ни один не работал пока я не включил логи и не узнал что надо добавить sys.4chan.org в список (`*.4chan.*` похоже его не отловил). Вроде все теперь работает, спасибо.
