### ISSUE TITLE
knowyourmeme.com

### ISSUE THREAD

**Issue by Barmem** [anticensority/runet-censorship-bypass#213]
knowyourmeme.com and its cdn: kym-cdn.com are blocked

**Comment by ilyaigpetrov** [comment]
https://knowyourmeme.com/ у меня работает.
С какой ошибкой у вас не открываются оба адреса?

**Comment by Barmem** [comment]
хмм, действительно работает, странно, с утра выдавало экран заблокированного ресурса у йоты
