### ISSUE TITLE
Превышение размера файла PAC-скрипта для Chromium-браузеров

### ISSUE THREAD

**Issue by bananakid** [anticensority/runet-censorship-bypass#215]
_Прежде всего я хочу поблагодарить автора этого замечательного проекта за многолетнюю поддержку. Благодаря этому проекту я и мои родители можем свободно знакомиться с информацией из независимых СМИ._

Я предпочитаю использовать Microsoft Edge в связке с PAC-скриптом `https://antizapret.prostovpn.org:18443/proxy.pac` в Windows 10, который задан в `Settings → Network & Internet → Proxy`, т.е. без расширения `Runet Censorship Bypass` (по какой-то причине файл с порта `8443` никогда не загружался, но сейчас не об этом).

К сожалению, пару дней назад моя конфиграция перестала работать, в то время как ping и tracert из Command Prompt имеют 0% потерь пинга/трассировки до необходимых адресов. Прежде чем написать это сообщение, я попробовал безуспешно также задать PAC-скрипт через политики в Microsoft Edge (с последующим Reload на edge://policy):
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"ProxyMode"="pac_script"
"ProxyPacUrl"="https://antizapret.prostovpn.org:18443/proxy.pac"
```

К счастью, расширение Runet Censorship Bypass работает. Я подозреваю, что проблема моей конфигурации может быть в том, что текущий размер PAC-файла 1 064 960 байт, что больше 1 МБ, в то время как в [этом обсуждении](https://bugs.chromium.org/p/chromium/issues/detail?id=678022) было указано, что предельный размер файла для обработки Chromium-браузерами составляет около 1 048 576 байт.

Уточните, пожалуйста, верно ли я определил проблему.

**Comment by ilyaigpetrov** [comment]
Да, если ставить PAC-скрипт через настройки Windows, то действует ограничение в 1MB (`2**20`). Сейчас PAC-скрипт АнтиЗапрета превышает этот порог. Такое же ограничение действует и в Хромоподобных браузерах, если указать URL PAC-скрипта через аргумент командной строки при запуске или через соответствующее API для браузерных расширений. К счастью, в этом API есть другой способ установки PAC-скрипта, который не учитывает ограничение в 1MB, что и используется в нашем расширении.

С политиками не работал, потому по их ограничениям не могу подсказать.

**Comment by bananakid** [comment]
Выражаю признательность за оперативное подтверждение подозрений и за развёрнутый ответ, @ilyaigpetrov! К сожалению, в настоящее время политики для Edge также не позволят обойти указанное ограничение.
