### ISSUE TITLE
Не проксируется amedia.online

### ISSUE THREAD

**Issue by genrihx2** [anticensority/runet-censorship-bypass#217]
роскомнадзор блочить amedia.online 

![image](https://github.com/anticensority/runet-censorship-bypass/assets/3043207/7dcc0f83-1957-4df5-a355-efb3ac942aa1)

**Comment by ilyaigpetrov** [comment]
Проблема всё ещё проявляется?

**Comment by genrihx2** [comment]
нет Проблема   спасибо   работает
