### ISSUE TITLE
Единый дополнительный список

### ISSUE THREAD

**Issue by ilyaigpetrov** [anticensority/runet-censorship-bypass#22]
Дополнительно к единой базе заблокированных сайтов предлагаю содержать один единственный список сайтов, которые мы также будем проксировать, несмотря на то, что их нет в реестре.

Список будет пополняться из жалоб пользователей и храниться в отдельном репозитории как JSON-объект (`true` -- проксировать, `false` -- исключить из проксирования).*
Генераторы будут его скачивать перед генерацией.

Список необходим, т.к. провайдеры самовольно блокируют некоторые ресурсы не из реестра. Пользователь такого провайдера не в состоянии исправить ситуацию, т.к. написанное им провайдеру письмо не имеет никакой силы, а до судебного разбирательства никто дело доводить не будет.

Добавлю, что ведение такого списка нам особо не мешает, архитектура не становится уродливей, продукт решает больше проблемных ситуаций.

С уважением,
Илья.

__UPD__

*Формат может быть упрощён до обычных списков для административных утилит Linux

P.S. По сути такие списки уже есть, но их нужно лишь легализовать в один, т.к. @ValdikSS грозился запретить проксировать сайты вне единой базы, и весь этот билет создан, чтобы убедить его в необходимости дополнительного списка.

**Comment by DmitriyK-CPKIO** [comment]
Поддерживаю. Только что столкнулся с тем, что duckduckgo.com заблокирован (на уровне выше моего провайдера, как сказали сотрудники последнего). В реестре не значится, но тем не менее.

**Comment by ilyaigpetrov** [comment]
Содержать отдельный список будет слишком затратно.
Я больше не думаю, что оно того стоит.
Лучше написать претензию (просьбу) провайдеру, чтобы он перестал блокировать ресурс вне реестра.
Насколько мне известно, блокировать сайт по собственной инициативе для провайдера незаконно.
