### ISSUE TITLE
https://rezka.ag/

### ISSUE THREAD

**Issue by rassadnikovkg** [anticensority/runet-censorship-bypass#220]
Перестали загружаться видео на сайте, постоянно выбивает ошибку загрузки, но при этом на сам сайт пускает, у самого сайта проблем нет, если зайти через зеркало все работает, но зеркало работает от силы 2 дня, прошу помочь в данном вопросе

**Comment by ilyaigpetrov** [comment]
1) [https://github.com/anticensority/runet-censorship-bypass/wiki/Проблемные-сайты#rezkaag-hdrezkaag](https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BD%D1%8B%D0%B5-%D1%81%D0%B0%D0%B9%D1%82%D1%8B#rezkaag-hdrezkaag)
2) Если видео и страница с проигрывателем открываются с разных IP-адресов, то срабатвает защита от плагиата.
К примеру, страница может проксироваться через наши сервера, а видео -- нет.

В PAC-скрипт АнтиЗапрет сайты не добавляются: см. [https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F](https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%9A%D0%B0%D0%BA-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D0%B2%D0%BE%D0%B9-%D1%81%D0%B0%D0%B9%D1%82%3F).

Если вы готовы использовать тор или свои прокси, то вам пригодится эта статья: [https://github.com/anticensority/runet-censorship-bypass/wiki/Чиним-сайты-со-сломанными-элементами](https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%A7%D0%B8%D0%BD%D0%B8%D0%BC-%D1%81%D0%B0%D0%B9%D1%82%D1%8B-%D1%81%D0%BE-%D1%81%D0%BB%D0%BE%D0%BC%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%D0%B8).
