### ISSUE TITLE
Невозможность загрузить расширение (ошибка Default locale is defined but default data couldn't be loaded)

### ISSUE THREAD

**Issue by Verity-Freedom** [anticensority/runet-censorship-bypass#221]
На некоторых (трудно судить на каких, но столкнулся с ошибкой на 360 security browser 14.1, интернет пестрит сообщениями о том, что в целом ошибка популярна) браузерах существует ошибка из-за того что они не понимают локаль ru в манифесте. Без каких-либо больших последствий исправляется заменой локали ru на en в файле манифеста.

**Comment by ghost** [comment]
Возможно, браузер по какой-то причине не может прочитать папку `_locales` в корне расширения.

**Comment by Verity-Freedom** [comment]
> Возможно, браузер по какой-то причине не может прочитать папку `_locales` в корне расширения.

Ошибка была исправлена заменой двух символов - default locale ru на default locale en. Язык расширения это не поменяло.

На 360 security 15 ошибки нет, но он так и не вышел из беты, поэтому я хочу с него пересесть на 14-ю версию, ибо в ней нет некоторых критических багов. Особенность браузеров в том, что они поддерживают флэш на хромиумах сильно выше сотого, поэтому уникальны в своём роде, но конкретно на эту ошибку в интернете жаловались часто и много.

**Comment by Verity-Freedom** [comment]
Если стоит цель именно воспроизвести проблему, то вот ссылка на используемый браузер. Я смог с него загрузить без проблем 15 расширений, кроме Обхода, из-за того что в нём используется default locale ru, а не en, как в остальных расширениях, что, в общем-то, насколько я понимаю, ни на что не влияет.
https://disk.yandex.ru/d/EKYOqmd5__5WJA

**Comment by Verity-Freedom** [comment]
Изначально браузер писался как одноязычный (разработан китайцами для внутреннего рынка, поддерживает оба манифеста, флэш и кучу всего), поэтому ничего удивительного нет в том, что он не понимает какие-то локали. Если загуглить ошибку Default locale is defined but default data couldn't be loaded, то видно, что она много где встречалась в разные времена.

**Comment by Verity-Freedom** [comment]
Знаете я думаю что это баг конкретно браузера (даже не так, конкретной его версии), сам браузер очень специфичный, так что можно закрыть тему, но если у кого-то другого возникнет такая проблема, то фикс для неё я предоставил - сменить язык локали в манифесте.
