### ISSUE TITLE
http://rutor.info

### ISSUE THREAD

**Issue by dymn** [anticensority/runet-censorship-bypass#222]
Примерно неделю не грузятся, предположительно, стили и js при заходе на http://rutor.info.
Инфа так то видна, но чисто текстовый вариант без оформления.
Зашел просто через VPN - все норм.
Firefox-124, Linux. Пробовал на чистом профиле - все также.

**Comment by VerTigoNTxvii** [comment]
это из-за [http://cdnbunny.org/](url). его надо проксировать тоже

**Comment by ghost** [comment]
У меня [cdnbunny.org](https://cdnbunny.org/) не блочится, и в реестре его нет.
Узнавайте причину блокировки у провайдера, если дело действительно в этом адресе.
Вы можете самостоятельно выявить проблемные адреса через devtools вашего браузера, на вкладке "Сеть", примерно как в этой статье: https://github.com/anticensority/runet-censorship-bypass/wiki/Чиним-сайты-со-сломанными-элементами.

**Comment by dymn** [comment]
Поколдовал - проблема была в DNS, которые выдавал роутер. Стоял "Quad9 - обеспечение безопасности". Перешел на DNS от Google - все заработало.
