### ISSUE TITLE
Ошибка тестовой версии 1.63

### ISSUE THREAD

**Issue by Verity-Freedom** [anticensority/runet-censorship-bypass#228]
"browser_specific_settings": {
    "gecko": {
      "strict_min_version": "91.1.0"
    }
  },
  
  Unrecognized manifest key 'browser_specific_settings'.
  
  На функционал не влияет.

**Comment by Verity-Freedom** [comment]
В версии 1.61 из магазина Хром ошибки нет. В 1.62 не помню есть или нет, не замечал.

**Comment by ilyaigpetrov** [comment]
Это предупреждения, я бы не хотел на них заморачиваться.

**Comment by Verity-Freedom** [comment]
Хорошо.

**Comment by Verity-Freedom** [comment]
Функционально идентичен версии 1.62 - тор работает, антизапрет работает. Но антизапрет у меня и не ломался, так что пусть проверяют те, у кого он сломался, я отрапортовал о том, что заметил.

**Comment by Verity-Freedom** [comment]
Вопрос, а старые адреса там ведь тоже сохранились, или их вырезали за ненадобностью?

Просто у меня расширение и по старым адресам работать продолжает.

На мой взгляд чем больше зеркал для скачивания pac-скрипта, чтобы он скачался хоть откуда-то, тем лучше.

**Comment by Verity-Freedom** [comment]
@ilyaigpetrov

**Comment by ilyaigpetrov** [comment]
Да, старые остались, но их приоритет ниже новых.
Вот что может пойти не так:
1) При обновлении не добавилось новых адресов.
2) При свежей установке, несмотря на приоритеты, используются старые адреса.

**Comment by Verity-Freedom** [comment]
К счастью мне это далеко ибо каким-то чудом меня это не коснулось.

Бог меня пощадил за то что за день до блокировки я "купил" софт, а негоже человеку мешать пользоваться тем, за что он реальные деньги заплатил)

**Comment by hada1987** [comment]
такие ошибки, и стало медленней работать_
{
  "manifest_version": 2,

  "name": "__MSG_extName__",
  "default_locale": "ru",
  "description": "__MSG_extDesc__",
  "version": "0.0.1.63",
  "icons": {
    "128": "icons/default-128.png"
  },
  "author": "anticensority+owners@googlegroups.com",

  "permissions": [
      "proxy"
    , "alarms"
    , "storage"
    , "unlimitedStorage"
    , "<all_urls>"
    , "tabs"
    , "contextMenus"
    , "notifications"
    , "webRequest", "webRequestBlocking", "webNavigation"
  ],
  "minimum_chrome_version": "55.0.0.0",
  "browser_specific_settings": {
    "gecko": {
      "strict_min_version": "91.1.0"
    }
  },

**Comment by Verity-Freedom** [comment]
> {
> "manifest_version": 2,

На это можно не смотреть, это не ошибка. Манифест v2 пока что нужен для того чтобы расширение работало на старых браузерах.



> и стало медленней работать

Скорость работы может измениться в связи с включённым режимом антицензорити.

**Comment by Verity-Freedom** [comment]
Фикс:
https://github.com/anticensority/runet-censorship-bypass/issues/233
