### ISSUE TITLE
OpenAI

### ISSUE THREAD

**Issue by The-Doctor-What** [anticensority/runet-censorship-bypass#248]
Добрый день хотелось бы что бы расширение включало прокси так же на сайте OpenAI Chat GPT и Gemini

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.

Автор https://antizapret.prostovpn.org:8443 в довольно редких случаях добавляет адреса в исключения. Я не знаю его политики относительно OpenAI. Он не подписан на обсуждения в этом репозитории, но я ему передал.

**Comment by ilyaigpetrov** [comment]
По поводу редких исключений в следующий раз пишите на адрес в подвале https://antizapret.prostovpn.org:8443.
