### ISSUE TITLE
Crunchyroll proxing

### ISSUE THREAD

**Issue by nockiee** [anticensority/runet-censorship-bypass#249]
Crunchyroll приостановил работу в рф, хотелось бы чтобы кранчрол работал через ваш сервис)

**Comment by ilyaigpetrov** [comment]
Наши решения работают по реестру РКН, мы не берём на себя задачу ведения собственного реестра.
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.
