### ISSUE TITLE
Медленный запуск в хромиум браузерах / Chromium Launches Very Slowly With This Extension

### ISSUE THREAD

**Issue by creativ33** [anticensority/runet-censorship-bypass#25]
Что бы повторить проблему установите  этот браузер https://www.centbrowser.com/ установите pac лист в настройках прокси, перезапустите браузер иногда вы сможете увидеть как начальная страница гугл или какая-либо другая может грузиться минуту и дольше. Это происходит и в обычном chrome браузере от гугл.

**Comment by ilyaigpetrov** [comment]
@creativ33 Вас не затруднит отключить все табы и расширения, кроме нашего, засечь время запуска оригинального Хрома и доложить результат на ингле (Windows такой-то, Chrome такой-то, 30s vs 2s without extension)? Также укажите выбранный PAC-скрипт. Переписку давайте вести здесь и желательно на английском (хотя бы результаты).

**Comment by ilyaigpetrov** [comment]
Linux (Xenial 16.04), Chrome 64.0.3282.119,
Launch time with the extension: 5s,
PAC-script: Anticensority

You may get Chrome version at `chrome://help`, you may get Windows build from `cmd.exe`.

**Comment by creativ33** [comment]
windows 10 pro 64x
chrome 64.0.3282.119,
PAC-script: Antizapret 
I'm not talking about the extension, I'm talking about adding a pac sheet to the proxy server settings

so with the proxy list enabled, go to the site https://getpocket.com/ the site visit is 44.14 s against
9.79 without him

**Comment by ilyaigpetrov** [comment]
@ValdikSS (he is the author of Antizapret), please, take a look.

**Comment by ilyaigpetrov** [comment]
1. I don't know what is "pac sheet". Did you mean PAC-script?
2. So you don't even use our extension? How do you use Antizapret PAC-script with official Chrome then? (Do you launch `chrome.exe` with some flag?)

**Comment by ilyaigpetrov** [comment]
Antizapret PAC-script is experiencing some problems at the moment, author is working on this. You may try https://rebrand.ly/ac-anticensority PAC-script if you haven't tried it yet, but don't use it in Windows system settings, instead use some chrome extension.

**Comment by ValdikSS** [comment]
Mail.ru Game Center has been generating enormous amount of HTTP requests to PAC file. Seems like they are initializing winsock for every request. I've banned it, -60 mbit/s of bandwidth. Seems fine now.
