### ISSUE TITLE
Не работает soundcloud

### ISSUE THREAD

**Issue by oVEsoleVaLaR** [anticensority/runet-censorship-bypass#250]
![Снимок экрана 2024-05-26 140155](https://github.com/anticensority/runet-censorship-bypass/assets/170859783/12a036d6-33d7-4e7a-9ed6-33d75fa204ff)

на против значка расширения появляются три точки

**Comment by oVEsoleVaLaR** [comment]
![Снимок экрана 2024-05-26 140657](https://github.com/anticensority/runet-censorship-bypass/assets/170859783/83087d6a-53dd-4592-984d-0fd80cc573f2)

Вот такой

**Comment by ilyaigpetrov** [comment]
Попробуйте отключить антивирус. Были замечены конфликты с Касперским.

**Comment by oVEsoleVaLaR** [comment]
отключал, не помогло, раньше с ним работал сейчас нет

**Comment by KeNNYDiViNE** [comment]
Да, у меня такая же проблема появилась(( вчера только заметил
Ни твиттер ни инстаграм не работают..
да вообще вообще большинство сайтов не работает теперь почему то(
Но проверяя на трекере.. он работает но не грузится полностью, только текст, оболочки нет.
Я честно говоря думал это наши провайдеры что то сделали потому что пару дней назад они меняли у нас оборудование на крыше и вот так совпало.. но раз не я один значит скорее всего не они виноваты.
ОЙ! и ещё! большинство ВПН тоже перестали работать, они почти все пишут нет соединения с сервером.
Так же говорили что майкрософт выпустили какое то обновление в этом месяце мешающие работать впн..

**Comment by ilyaigpetrov** [comment]
@KeNNYDiViNE, у вас та же ошибка `TUNNEL_CONNECTION_FAILED` при открытии, например, https://meduza.io ?
Пришлите скриншот ошибки, захватив также адресную строку и иконку расширения.

**Comment by KeNNYDiViNE** [comment]
![image](https://github.com/anticensority/runet-censorship-bypass/assets/121106568/4e6b4b82-cbd7-40a5-bbba-6996acfa0acf)

**Comment by ilyaigpetrov** [comment]
@KeNNYDiViNE:
1) Откройте новую вкладку браузера.
2) Нажмите F12 -- откроется devtools, выберите вкладку Network / Сеть.
3) Вбейте в адресную строку meduza.io, нажмите Enter.
4) В devtools запечатлите на снимке красную запись и обозначение ошибки (возможно, придётся расширить столбец в таблице, чтобы увидеть название ошибки).

**Comment by KeNNYDiViNE** [comment]
Я не совсем понимаю.. эта ли вкладка?
![image](https://github.com/anticensority/runet-censorship-bypass/assets/121106568/c3a69226-6a59-42a5-a561-49ba6110f2e4)

**Comment by ilyaigpetrov** [comment]
Вот [пример](https://user-images.githubusercontent.com/1090811/230708036-87debcf3-e79e-44a9-97d8-bef44d542726.png), на нём видна ошибка `ERR_CONNECTION_RESET`. Ваша ошибка может отличаться, но будет начинаться на `ERR_`.

**Comment by KeNNYDiViNE** [comment]
![image](https://github.com/anticensority/runet-censorship-bypass/assets/121106568/fa47452f-4547-41b0-a19f-79b6153f55a8)
у меня как то пустовато там

**Comment by ilyaigpetrov** [comment]
@KeNNYDiViNE, предполагаю, вы пробовали отключить антивирус или у вас его нет.

**Comment by KeNNYDiViNE** [comment]
касперский но он отключён, хотя раньше и с ним работало

**Comment by ValdikSS** [comment]
Запишите трафик к прокси-серверам.

1. Скачать и установить [Wireshark](https://www.wireshark.org/). Нужна полная версия, портативная не подойдет.
2. Выбрать сетевой интерфейс, ввести в поле "…using this filter" строку:
    `host 217.182.205.176 or host 137.74.1.183 or host 51.15.104.199 or host 51.38.124.100 or host 149.202.68.178 or host 51.68.220.147 or host 37.187.27.57 or host 92.222.181.158 or host 137.74.1.203 or host 217.182.79.244 or host 51.38.124.173 or host 51.15.104.135 or host 51.158.184.96 or host 51.159.195.39`
3. Попробовать зайти на заблокированный сайт (лучше несколько раз и на разные).
4. Остановить захват трафика кнопкой с иконкой красного квадрата на панели. Нажать file → save as, сохранить в файл.
5. Отправить файл сюда.

**Comment by KeNNYDiViNE** [comment]
[54.zip](https://github.com/anticensority/runet-censorship-bypass/files/15491623/54.zip)
Вот, получилось архивом только, может я что то не то сделал но вроде он записал всё с 2 сайтов, один ваш, другой инстаграм

**Comment by ValdikSS** [comment]
Проблема в Касперском.
https://forum.kaspersky.com/topic/%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D0%B5%D1%82%D1%81%D1%8F-%D1%88%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F-vpn-%D0%B2-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5-edge-kaspersky-2117-41810/?page=2#comment-173179

**Comment by KeNNYDiViNE** [comment]
Да. проблема и правда была в нём, но это очень странно так как я все время же пользовался обходом и антивирусу было всё равно, что выключай что нет, а сейчас вот такое произошло..
Причём теперь эта функция работает ведь с выключенным антивирусом, как же достал этот касперский((
Спасибо большое за помощь, извините что потратил ваше время(
