### ISSUE TITLE
Опечатки, орфография, пунктуация

### ISSUE THREAD

**Issue by SanBest93** [anticensority/runet-censorship-bypass#251]
за такое расстреливать надо :(
я в такие йгры не йграю

https://github.com/anticensority/runet-censorship-bypass/wiki/Различные-версии-расширения
![image](https://github.com/anticensority/runet-censorship-bypass/assets/35857449/df60f7f8-37bb-49c5-aa51-0b22c3f3bb5e)

**Comment by ilyaigpetrov** [comment]
Исправил, спасибо.
