### ISSUE TITLE
не работает patreon.com

### ISSUE THREAD

**Issue by katelesss** [anticensority/runet-censorship-bypass#254]
Остальные заблокированные сайты открваются (rutracker), а patreon перестал загружаться

**Comment by ilyaigpetrov** [comment]
С выключенным расширением работает?

**Comment by katelesss** [comment]
нет

**Comment by ilyaigpetrov** [comment]
Сейчас работает?

**Comment by Verity-Freedom** [comment]
У Патреона лежит бан на Торе. Таким образом он должен открываться только с серверов антизапрета. Из режима антицензорити, из портативного Тора не откроется. Я сейчас не могу проверить (нахожусь не в России) работоспособность Патреона в режиме антизапрета.
