### ISSUE TITLE
не работает furaffinity.net

### ISSUE THREAD

**Issue by LinaLin-qq** [anticensority/runet-censorship-bypass#255]
рутрекер и тд открываются

**Comment by ilyaigpetrov** [comment]
С какой ошибкой не открывается?
Пришлите снимок ошибки, не забыв захватить в кадр адресную строку и иконку расширения.

**Comment by LinaLin-qq** [comment]
> С какой ошибкой не открывается? Пришлите снимок ошибки, не забыв захватить в кадр адресную строку и иконку расширения.

К счастью, в комментариях к проблемам с другим сайтом нашлось только что решение и для меня: убрала в настройках безопасности сети Касперского галки, поставила на "не проверять защищенные соединения", и всё заработало. Странно, до этого Касперский не шалил так. Спасибо за оперативную реакцию в любом случае!
