### ISSUE TITLE
Не удалось скачать PAC-скрипт

### ISSUE THREAD

**Issue by w0rl3x** [anticensority/runet-censorship-bypass#258]
Добрый день, только сегодня появилась подобная ошибка:
`Не удалось скачать PAC-скрипт с адресов: [ https://e.cen.rodeo:8443/proxy.pac , https://antizapret.prostovpn.org:8443/proxy.pac , https://antizapret.prostovpn.org:18443/proxy.pac , https://antizapret.prostovpn.org/proxy.pac ]. > Что-то не так с сетью, проверьте соединение. > Failed to fetch`
Мой провайдер - Дом.ру
Почитал подобные баг-репорты других пользователей, советовали посмотреть, открываются ли ссылки из логов. Заходя на ссылку https://e.cen.rodeo:8443/proxy.pac и ей подобные ссылки на домене e.cen.rodeo, высвечивается ошибка:
504 Gateway timeout
The gateway is taking too long to fetch your content. This could be due to several reasons:

The CID does not exist in the IPFS network
The host that contains the CID has gone offline, is on a slow network connection or overloaded
что делать в данной ситуации? АВ нет, расширения так же не работает и в других профилях Chrome (то есть, при использовании только одного расширения АнтиЗапрета, без всяких впнов и прочего)
![image](https://github.com/anticensority/runet-censorship-bypass/assets/54393998/17f671e8-4a37-4366-98c7-dea5ddcc811f)

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-2165617597.
