### ISSUE TITLE
Не удалось скачать PAC-скрипт

### ISSUE THREAD

**Issue by genrihx2** [anticensority/runet-censorship-bypass#259]
![image](https://github.com/anticensority/runet-censorship-bypass/assets/3043207/bef61cd6-5f4c-4fd0-a8e9-d6d0d7fe9376)

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-2165617597.

**Comment by genrihx2** [comment]
![image](https://github.com/anticensority/runet-censorship-bypass/assets/3043207/232e96d7-a0c6-40b2-bf67-91554e63119c)

A

**Comment by ilyaigpetrov** [comment]
Видимо, кто-то распространяет фишинговые материалы через шлюз IPFS. За всеми не уследишь, океан не отфильтруешь. Попробуйте добавить этот ресурс в исключения антивируса.

**Comment by genrihx2** [comment]
![image](https://github.com/anticensority/runet-censorship-bypass/assets/3043207/f5dfa634-27a6-4a73-a323-9ba2abfaed84)

ошибка  504 Gateway timeout

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-2165617597.

**Comment by genrihx2** [comment]
спасибо

**Comment by ilyaigpetrov** [comment]
Исправлено, см. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-2166133389.
