### ISSUE TITLE
antizapret.prostovpn.org/proxy.pac недоступен (наши IP попали в блок)

### ISSUE THREAD

**Issue by anankasma** [anticensority/runet-censorship-bypass#26]
расширение некорректно работает на яндекс браузере. виснет на обновлении и выдаёт ошибку. лог прикрепляю
![browser_2018-02-18_05-21-07](https://user-images.githubusercontent.com/36580431/36347603-3bbede4e-146c-11e8-8125-1e6821762704.jpg)
![browser_2018-02-18_05-29-27](https://user-images.githubusercontent.com/36580431/36347626-bb99345c-146c-11e8-99c5-2b34c0e659a2.jpg)

**Comment by ilyaigpetrov** [comment]
Проверьте, что этот файл у вас в браузере доступен для скачивания: https://antizapret.prostovpn.org/proxy.pac

**Comment by ilyaigpetrov** [comment]
Мы внесли кое-какие поправки, попробуйте ещё раз и сообщите нам о результате.

**Comment by anankasma** [comment]
скрипт для скачивания в браузере доступен, а так же расширение теперь полностью рабочее. спасибо вам огромное!

**Comment by ilyaigpetrov** [comment]
04.04.2018, ошибка снова появляется у провайдеров, которые блокируют по IP адресу (все сайты на IP заодно с виновным сайтом).
Возникает из-за того, что мы используем сервера Cloudflare, которые используются также и блокируемыми сайтами.
@ValdikSS, как скоро сможем починить?

**Comment by ValdikSS** [comment]
Перенес antizapret.download на другой аккаунт Cloudflare, из-за чего домен сменил адреса. Новые адреса не числятся в реестре.
