### ISSUE TITLE
Не удалось скачать PAC-скрипт с адресов, https://e.cen.rodeo:8443/proxy.pac

### ISSUE THREAD

**Issue by by-tndy** [anticensority/runet-censorship-bypass#262]
https://anticensority.github.io/error/0.0.0.17/?json=%7B%22pup-ext-err%22%3A%7B%22message%22%3A%22Не%20удалось%20скачать%20PAC-скрипт%20с%20адресов%3A%20%5B%20https%3A%2F%2Fe.cen.rodeo%3A8443%2Fproxy.pac%20%2C%20https%3A%2F%2Fantizapret.prostovpn.org%3A8443%2Fproxy.pac%20%2C%20https%3A%2F%2Fantizapret.prostovpn.org%3A18443%2Fproxy.pac%20%2C%20https%3A%2F%2Fantizapret.prostovpn.org%2Fproxy.pac%20%5D.%22%2C%22wrapped%22%3A%7B%22message%22%3A%22Что-то%20не%20так%20с%20сетью%2C%20проверьте%20соединение.%22%2C%22wrapped%22%3A%7B%22stack%22%3A%22TypeError%3A%20Failed%20to%20fetch%5Cn%20%20%20%20at%20Object.get%20(chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F13-http-lib.js%3A45%3A7)%5Cn%20%20%20%20at%20chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F37-sync-pac-script-with-pac-provider-api.js%3A221%3A44%5Cn%20%20%20%20at%20new%20Promise%20(%3Canonymous%3E)%5Cn%20%20%20%20at%20chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F37-sync-pac-script-with-pac-provider-api.js%3A220%3A19%22%2C%22message%22%3A%22Failed%20to%20fetch%22%2C%22name%22%3A%22TypeError%22%7D%7D%7D%7D&type=pup-ext-err&version=0.0.1.63&useragent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F122.0.0.0%20YaBrowser%2F24.4.0.0%20Safari%2F537.36&platform=Win32

**Comment by ilyaigpetrov** [comment]
См.
https://github.com/anticensority/runet-censorship-bypass/wiki/Частые-проблемы#не-удалось-скачать-pac-скрипт-с-адресов--httpsantizapretprostovpnorgproxypac%2D
.

**Comment by by-tndy** [comment]
Буквально часа 2 назад работало штатно, соединение у меня не менялось за эти 2 часа.

**Comment by by-tndy** [comment]
Способы не помогают

**Comment by ilyaigpetrov** [comment]
Какую ошибку выдаёт при открытии https://e.cen.rodeo:8443/proxy.pac в браузере?
Можно прислать скриншотом.

**Comment by by-tndy** [comment]
> Какую ошибку выдаёт при открытии https://e.cen.rodeo:8443/proxy.pac в браузере? Можно прислать скриншотом.

![image](https://github.com/anticensority/runet-censorship-bypass/assets/163456754/066c073b-eac1-4100-a123-6e097bd99da3)

**Comment by by-tndy** [comment]
> Какую ошибку выдаёт при открытии https://e.cen.rodeo:8443/proxy.pac в браузере? Можно прислать скриншотом.

поставил мини версию, теперь выдает 504. 
![image](https://github.com/anticensority/runet-censorship-bypass/assets/163456754/982c59bb-c947-4f82-af03-3a6070039e0b)

**Comment by by-tndy** [comment]
> > Какую ошибку выдаёт при открытии https://e.cen.rodeo:8443/proxy.pac в браузере? Можно прислать скриншотом.
> 
> ![image](https://private-user-images.githubusercontent.com/163456754/340783084-066c073b-eac1-4100-a123-6e097bd99da3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzQ4NDAsIm5iZiI6MTcxODczNDU0MCwicGF0aCI6Ii8xNjM0NTY3NTQvMzQwNzgzMDg0LTA2NmMwNzNiLWVhYzEtNDEwMC1hMTIzLTZlMDk3YmQ5OWRhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxODE1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDI2MDYwZDkwM2UyZjNkZjY4ZDdhZDQ3OGIyZmE3YTg3ZDM4ZWQ3NjM5OTZkODk5NmIyZjM2YWM3NmRiNDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xlHOMJNKt28X0TWEqdqNPlhtWDXsPjcRjn2tlABK5Qo)

**Comment by by-tndy** [comment]
Заработало, отбой тревоги. 
![image](https://github.com/anticensority/runet-censorship-bypass/assets/163456754/fe7610c2-c886-4227-b90c-372f18b94b17)
