### ISSUE TITLE
таже проблема

### ISSUE THREAD

**Issue by baronanikin999** [anticensority/runet-censorship-bypass#263]
Информация об ошибках
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.63",
  "pup-ext-err": {
    "message": "Не удалось скачать PAC-скрипт с адресов: [ https://e.cen.rodeo:8443/proxy.pac , https://antizapret.prostovpn.org:8443/proxy.pac , https://antizapret.prostovpn.org:18443/proxy.pac , https://antizapret.prostovpn.org/proxy.pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:220:19",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  }
}

**Comment by baronanikin999** [comment]
все нормально извините за беспокойство проблема была в блокировке рекламы

**Comment by ilyaigpetrov** [comment]
Верно, см. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-2178981548.
