### ISSUE TITLE
Не могу пользоваться сайтом Intel

### ISSUE THREAD

**Issue by TRAD80** [anticensority/runet-censorship-bypass#267]
Добрый день заходя на сайт Intel пишет "Мы немедленно остановили все деловые операции в России. Это следует за нашей стратегией — прекратить все поставки клиентам в России и на территории Беларуси." вот ссылка https://www.intel.com/content/www/us/en/support/ru-banner-inside.html Вы сможете это исправить? У FastProxy работает, но я с него ушёл к вам. Браузер Chrome

**Comment by TRAD80** [comment]
![Снимок экрана 2024-07-06 115743](https://github.com/anticensority/runet-censorship-bypass/assets/174864026/ffb9ad00-feb0-46ff-b9c5-eb7cb6d7b1b1)

**Comment by ilyaigpetrov** [comment]
РКН этот адрес не блокировал и потому его нет в реестре блокировок, на котором основаны наши решения. Мы не берём на себя задачу ведения дополнительного реестра адресов, заблоченных не по решению РКН.

**Comment by ilyaigpetrov** [comment]
В расширение можно интегрировать свои прокси или Тор: см. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.

**Comment by TRAD80** [comment]
Спасибо. Хорошего дня.

  
>Суббота, 6 июля 2024, 12:10 +03:00 от ilyaigpetrov ***@***.***>:
> 
> 
>В расширение можно интегрировать свои прокси или Тор: см.  https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F .
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <anticensority/runet-censorship-bypass/issues/267/2211715317 @ github . com> 
 
 
__________________________________________________

С уважением, Чернов Дмитрий
