### ISSUE TITLE
Опечатка в вики.

### ISSUE THREAD

**Issue by V01DZ3R0** [anticensority/runet-censorship-bypass#269]
https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D1%8B-%D1%8D%D1%82%D0%BE-%D0%B4%D0%B5%D0%BB%D0%B0%D0%B5%D0%BC%3F-%D0%90%D1%80%D0%B3%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D1%80%D0%BE%D1%82%D0%B8%D0%B2-%D1%86%D0%B5%D0%BD%D0%B7%D1%83%D1%80%D1%8B

> Пункты 1 и 2 справделивы и для секса, но секс – это лишь "выйгрыш", а порно – это уже "джекпот".

выйгрыш -> выигрыш

**Comment by ilyaigpetrov** [comment]
Fixed
