### ISSUE TITLE
Не работает на Фаерфоксе для Андроида

### ISSUE THREAD

**Issue by glow12121** [anticensority/runet-censorship-bypass#271]
Спасибо за плагин! Пользуюсь им на компьютере. Но для Фаерфокса на Андроиде он не работает. Можно ли портировать его?

![Screenshot_20240715-213405](https://github.com/user-attachments/assets/7e6db524-5109-4ae0-81bd-f80a01111dd7)

**Comment by ilyaigpetrov** [comment]
Следите за https://github.com/anticensority/runet-censorship-bypass/discussions/261.
