### ISSUE TITLE
Перестало работать расширение

### ISSUE THREAD

**Issue by IGORb96** [anticensority/runet-censorship-bypass#274]
В яндекс браузере перестало работать расширение хотя в хроме работает. почистил кэш, переустановил расширение выключал адблок но проблема осталась

Информация об ошибках
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 YaBrowser/24.6.0.0 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.63",
  "pup-ext-err": {
    "message": "Не удалось скачать PAC-скрипт с адресов: [ https://e.cen.rodeo:8443/proxy.pac , https://antizapret.prostovpn.org:8443/proxy.pac , https://antizapret.prostovpn.org:18443/proxy.pac , https://antizapret.prostovpn.org/proxy.pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:220:19",
        "message": "Failed to fetch",
        "name": "TypeError"

**Comment by ilyaigpetrov** [comment]
Попробуйте откыть следующие ссылки в новых вкладках яндекс-браузера:
1) https://gateway.pinata.cloud/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about
2) https://e.cen.rodeo:8443/proxy.pac

В ответ можно прислать снимки ошибок, если такие возникнут.

**Comment by IGORb96** [comment]
при открытии обоих ссылок 
![image](https://github.com/user-attachments/assets/2b640b2f-2f36-4b8d-a290-e924407a04de)

**Comment by ilyaigpetrov** [comment]
Проверьте сетевые ошибки при открытии ссылки на пинату.
Примерно как это делается здесь: https://github.com/anticensority/runet-censorship-bypass/wiki/Чиним-сайты-со-сломанными-элементами#через-инструменты-разработчика-в-браузере-devtools.

**Comment by IGORb96** [comment]
![image](https://github.com/user-attachments/assets/84ffbfa0-49d7-4cca-b9cc-87f00101179c)

**Comment by IGORb96** [comment]
Расширение заработало возможно проблема была не во мне и просто нужно было время. Спасибо за помощь в поиске решения.
