### ISSUE TITLE
Сделал переезд, сайт перестал открывать

### ISSUE THREAD

**Issue by Dengger87** [anticensority/runet-censorship-bypass#276]
Добрый день.
Сделал переезд домена на [kinokong.bz](http://kinokong.bz/) , сайт попал 19.07 в реестр, но так и не заработал через Антизапрет! помогите, что делать? кому писать? Возможно за доп оплату могли бы добавить его в список?
Другие сайты работают как и раньше.

**Comment by ilyaigpetrov** [comment]
Ответил здесь: https://ntc.party/t/сделал-переезд-домена-и-сайт-перестал-открываться/8150/10.
