### ISSUE TITLE
Обход замедления YouTube

### ISSUE THREAD

**Issue by GoPetr** [anticensority/runet-censorship-bypass#281]
Добрый день.
Возможно YouTube не будут блочить на территории РФ, но урежут доступ к ресурсу, снизив скорость.
Поможет ли расширение убрать ограничения в скорости?

**Comment by Verity-Freedom** [comment]
Оно уже замедлено и уже (судя по моему опыту) помогает обходить замедление, ибо я его у себя не наблюдаю, а многие другие наблюдают.

**Comment by Trergfirestorm** [comment]
А как на Андроиде пользоваться подскажите

**Comment by Verity-Freedom** [comment]
На андроиде замедления вроде и не было(?)

**Comment by Trergfirestorm** [comment]
Есть. Ютьюб же и на планшетах с телефонами работает) для опенвпн раньше был файлик

**Comment by Verity-Freedom** [comment]
Ну смотрите там я сам в телефоне редко сижу расширением этим не пользуюсь.

**Comment by ilyaigpetrov** [comment]
> для опенвпн раньше был файлик

@Trergfirestorm, вероятно, речь о файле с https://antizapret.prostovpn.org:8443.

**Comment by GoPetr** [comment]
> Оно уже замедлено и уже (судя по моему опыту) помогает обходить замедление, ибо я его у себя не наблюдаю, а многие другие наблюдают.

Не помогает обходить замедлени! YouTube прекрасно рабоет с использованием VPN. 
@ilyaigpetrov Мне кажется сложно реализовать подмену для того, что бы скорость нерезалась, но я профан.

**Comment by ilyaigpetrov** [comment]
[chromium-test.zip](https://github.com/user-attachments/files/16434098/chromium-test.zip) -- протестируйте на замедленных видео, пожалуйста. У меня ютуб не замедлялся -- не могу проверить самостоятельно.

Способ установки через .crx-файл (для Chromium/Chrome)

1) Скачайте zip-архив и распакуйте .crx-файл.
2) В Хроме откройте chrome://extensions.
3) Включите режим разработчика (developer mode).
4) Перетащите скачанный .crx-файл в окно chrome://extensions -- расширение сразу установится.
5) Откройте замедленное видео, начните проигрывать.
6) Если видео стало проигрываться быстрее, то временно отключите расширение и убедитесь, что без него видео тормозит.
7) Напишите о результате в эту тему.

**Comment by ilyaigpetrov** [comment]
Забыл важное: Хром запускать с параметрами типа `chrome.exe --ignore-certificate-errors --disable-web-security --disable-gpu --user-data-dir=C:\chromeTemp`, где `chromeTemp` -- какая-нибудь директория для временного размещения файлов, которую можно удалить после завершения теста.

**Comment by GoPetr** [comment]
На данный момент YouTube снова грузится нормально. Как только начнет лагать протестирую прогу. 
Считаю, что проблема серьезная и нужно найти людей для теста у кого замедленный YouTube.

**Comment by ilyaigpetrov** [comment]
Почистил и опубликовал здесь: https://github.com/anticensority/decrab-youtube. Обратная связь приветствуется. Пока только для Хрома.

**Comment by SnowFurakesu** [comment]
К сожалению новое расширение не работает на Яндекс браузере и на Хроме, видео не загружается. Скачал чистый хром, отключил CORS и скачал расширение, все равно не работает.

**Comment by LavaCreeperYT** [comment]
> Добрый день. Возможно YouTube не будут блочить на территории РФ, но урежут доступ к ресурсу, снизив скорость. Поможет ли расширение убрать ограничения в скорости?

01.08.24 - уже заблокировали видимо, см. тему выше

**Comment by sava911** [comment]
не работает 25,06,25
