### ISSUE TITLE
С 1 августа ютуб умер

### ISSUE THREAD

**Issue by LavaCreeperYT** [anticensority/runet-censorship-bypass#282]
ИЗМЕНЕНО 01.08.24 13:18 - Сейчас ютуб проперделся, но будто бы тормозит.

До 1 августа всё работало хорошо, замедления не замечал, но сегодня сам сайт прекрасно работает, а видео не грузят. С телефона всё нормально, как и при просмотре через embed'ы к примеру в Discord
Похоже роскомпозорные доигрались, с интернетом всё нормально.
![Screenshot_1](https://github.com/user-attachments/assets/6ad9336d-a7a9-4d95-8239-82be9e5e62fa)

**Comment by ingraveman** [comment]
Тоже все, хоть отпевай. 
Надеюсь соорудят расширение какое, чтобы как и прежде, пускай и с ограничениями, но продолжать пользоваться.

**Comment by TheSketty** [comment]
Пока не выпустили обнову, можно использовать GoodbyeDPI. Как раз вчера вышло обновление, чтобы обойти блокировку ютуба

**Comment by ARGAMX** [comment]
У меня в Google Chrome такая же картина. А в Safari на этом же компе отлично работает. Причем в Safari никаких расширений не установлено.

**Comment by GoPetr** [comment]
> У меня в Google Chrome такая же картина. А в Safari на этом же компе отлично работает. Причем в Safari никаких расширений не установлено.

Chrome - не работает
Mozilla - работает

**Comment by LavaCreeperYT** [comment]
> > У меня в Google Chrome такая же картина. А в Safari на этом же компе отлично работает. Причем в Safari никаких расширений не установлено.
> 
> Chrome - не работает Mozilla - работает

ясно, переходим на лису дружно

**Comment by ilyaigpetrov** [comment]
Расширение по задумке не должно проксировать видео на youtube.
Аватарки -- да. Видео -- нет.
Наших мощностей не хватит на видео.
Возможно, разные браузеры используют разные версии HTTP/QUIC и все ощущения размедления проистекают от этого.

**Comment by ilyaigpetrov** [comment]
Для YouTube вышло наше новое расширение: https://github.com/anticensority/decrab-youtube. Декрабизация YouTube не конфликтует с ОБР -- можно держать оба расширения включенными одновременно.

**Comment by LavaCreeperYT** [comment]
в общем, можете закрывать тему, люди могут пользоваться декрабизацией, VPN или Goodbye DPI

**Comment by Prottok** [comment]
Решения кроме сомнительного Goodbye DPI ещё нет?

**Comment by LavaCreeperYT** [comment]
> Решения кроме сомнительного Goodbye DPI ещё нет?

Есть ещё одно расширение от этих же разработчиков: Декрабизация Youtube, правда устанавливается оно не по нажатию кнопки в магазине расширений, а посложнее. https://github.com/anticensority/decrab-youtube
Также можно прошить роутер и поставить туда прокси
Ну или, пока границы окончательно не закрыли, - свалить куда подальше

Тема закрыта.
