### ISSUE TITLE
В Chrome перестали открываться ВСЕ страницы

### ISSUE THREAD

**Issue by zalessky** [anticensority/runet-censorship-bypass#29]
В Chrome перестали открываться ВСЕ страницы, не только заблокированные.
Версия хрома 65.0.3325.181
Версия расширения 0.0.1.20
Полный снос Хрома ничего не дал - через пару часов снова то же самое. Бесконечная загрузка и ни байта трафика не приходит. 
При попытке отключить прокси из меню расширения - ошибка Uncaught TypeError: Cannot read property 'conduct' of undefined
Отключить удается лишь через меню расширений. После чего страницы начинают загружаться как ни в чём ни бывало

**Comment by ilyaigpetrov** [comment]
1) Хром при этом подтормаживает?  
Если да, то откройте Chrome Task Manager (Shift + Esc) и найдите "Utility: V8 Proxy Resolver" (в русской версии назван по-другому), сделайте и пришлите сюда скриншот. Информация будет важной, если этот процесс ест много ресурсов.

2) Чтобы воспроизвести такое состояние на моей машине, что нужно делать пару часов: смотреть много видео, слушать музыку, посещать какие-то конкретные сайты, или это всё неважно?

3) Также будет интересно какая у вас операционная система.

**Comment by zalessky** [comment]
1. Напротив, он освобождает память (во всяком случае, мне так показалось - у меня одновременно открыто не менее 50 вкладок и память он жрет в три горла). Однако, в его собственном диспетчере задач процесс "Утилита: Прокси сервер V8" потребляет более 100% ресурсов процессора. Хотя, суммарно все процессы жрут не более 30%. Странная математика :)
2. Первый раз это произошло после открытия нескольких (более 5) различных вкладок интернет-магазина https://www.rosegal.com/
Потом был отлов процесса, убивающего хром, попытки реанимировать, снос расширения, снос хрома. 
Вроде бы во второй раз причиной послужил тот же сайт, однако, не уверен. Во всяком случае, вкладки этого магазина были открыты. На ночь оставил ноут включенным с открытыми вкладками после аналогичного глюка. Утром обнаружил, что хром упал, потерял все вкладки - восстановиться не предложил. Зато открыл новую вкладку после автоматического обновления Viber. Что послужило причиной ночного падения - не знаю. Во всяком случае, прокси разблокировался и пока не падал. Продолжаю наблюдение :) Кстати, когда прокси не блочится, отключить проксирование из меню расширения получается без ошибки. 
3. Винда 10 х64 с последними обновлениями.

**Comment by ilyaigpetrov** [comment]
Вы используете PAC-скрипт "Антизапрет" или "Антицензорити"? Какие-то другие настройки, отличные от стандартных?

У меня не выходит воспроизвести поведение с помощью вкладок https://www.rosegal.com.

**Comment by ilyaigpetrov** [comment]
Попытался убрать ошибку _"Cannot read property 'conduct' of undefined"_ в версии 0.0.1.21.
Сообщите, если не убрал.
Как обновиться: https://rebrand.ly/ac-update

**Comment by zalessky** [comment]
Антицензорити. 
обновился. спасибо. буду продолжать наблюдение. При рецидивах сообщу

**Comment by zalessky** [comment]
Очередной рецидив. Симптомы те же: процесс "Утилита: Прокси сервер V8" потребляет более 100% ресурсов , ни одна страница не открывается, зато теперь можно отключить прокси из окошка расширения и все лечится. Вот какие две одновременно ссылки привели к такому:
[https://m.rosegal.com/m-app_h5-a-app_download.htm?actiontype=3&url=2115885&name=Waterproof Long Lasting Mascara Liquid Eyeliner Eyebrow Pencil Set&source=sharelink&lang=ru](url)
[https://m.rosegal.com/m-app_h5-a-app_download.htm?actiontype=3&url=2072371&name=Hollow Out Metal Full Frame Sun Shades Sunglasses&source=sharelink&lang=ru](url)

Из доменного имени https://m.rosegal.com/  пропадает 'm', получается: https://.rosegal.com/, а далее бесконечная загрузка

**Comment by ilyaigpetrov** [comment]
Никто на такую проблему более не жаловался. Закрываю, т.к. проблема уже может быть неактуальна. Откройте, если вам всё ещё нужна помощь -- желательно привести шаги воспроизведения проблемы.

**Comment by Magicanum** [comment]
Приветствую!
Вышеописанная ситуация произошла у меня на PC. Windows 7 x64, Chrome 76.0.3809.132. Ни одна страница из интернета не запускается, бесконечная попытка коннекта со строкой внизу браузера: "определение прокси-сервера...".
Первый раз произошло при работе с 35-40 вкладками примерно. Через командную консоль адреса инета пинговались, Pale Moon запустил - всё сайты открывал (расширения там этого нет, даже не уверен, что можно установить). Отключил прокси в Хроме через меню расширения "Обход блокировок Рунета" - результата ноль. В Хроме отключил все расширения, что были запущены (OneTab, AdBlock Plus, uMatrix, Tampermonkey, ImTranslator, Extensity, JustBlock Security, AutoPageres, PageExpand, Pushbullet, WebScrapBook, VKOpt, TabsBook, Roboform, DarkReader), в том числе и "Обход блокировок Рунета" - результат тот же. Отключил "Утилита: Прокси сервер V8" в диспетчере задач Хрома, процесс перезагрузился и всё заработало.
Второй раз (3 дня назад) произошло, когда были открыты две вкладки (Гугл и блог со страницей о телевизорах Samsung), расширений тоже было мало запущено. Мне тогда было не до разбора полётов, просто снова сбросил вышеуказанную утилиту. А сегодня решил написать сюда, не знаю точно связано ли это точно с этим расширением или причина в чём-то другом...

**Comment by ValdikSS** [comment]
Перезапуск браузера помогает в этом случае?

**Comment by Magicanum** [comment]
Когда произошла ошибка во второй раз, я не перезагружал, просто сбросил процесс. А в первый раз я не помню (где-то неделю назад было), перезагружал ли я. Но у меня некоторые процессы остаются в системе после закрытия браузера...

**Comment by ilyaigpetrov** [comment]
@Magicanum, предполагаю, что у вас тоже используется PAC-скрипт «Антизапрет». Сообщите, если я ошибаюсь.

@ValdikSS, звучит, как бесконечный цикл или что-то подобное.

**Comment by ValdikSS** [comment]
PAC-файл антизапрета раздаётся через шлюз распределенной файловой системы IPFS.
Иногда скачивание файла через IPFS может начинаться после длительного ожидания в 2-3 минуты.
Моё предположение — вы пытаетесь обновить PAC-файл в расширении в момент, когда PAC-файл только что обновился и ещё не успел закешироваться на шлюзе, из-за чего и возникает эта проблема.

**Comment by ilyaigpetrov** [comment]
PAC-скрипт обновляется в несколько шагов:

1) Скачивание (идёт параллельно с работой старого PAC-скрипта). Может
занимать минуты из-за IPFS, но всё это время будет работать старый скрипт.
2) Установка после полного скачивания (занимает секунды).

**Comment by Magicanum** [comment]
Я использую антицензорити с локальным прокси ТОР, но запускается он только из этого расширения. В случае отключения расширения, работает PAC антизапрета, прописанный в сетевых настройках. Может, в этом косяк?

**Comment by ilyaigpetrov** [comment]
Настройки ОС не должны отслеживаться в Хроме и не должны отображаться в
статусе "определение прокси-сервера...".
Тем более настройки ОС не должны быть связаны с процессом "Утилита: Прокси
сервер V8".
В случае зависания Хрома, Pale Moon должен был открывать заблокированные
сайты, т.к. PAC-скрипт в ОС должен был работать корректно.

Когда у вас активны сразу два PAC-скрипта, то я затрудняюсь сказать, какой
из них имеет больший приоритет в Хроме.

**Comment by ilyaigpetrov** [comment]
Отметьте все три галочки на вкладке "Уведомления" в расширении.
Если зависания будут повторяться, можно попробовать снять галочку
"Проксируй или умри!" на вкладке "Модификаторы" в расширении, но тогда
PAC-скрипт может начать временами сбоить.
Предположительно, "Проксируй или умри" может вызывать отказы какому-то
настойчивому процессу, который впадает в вечный цикл синхронных
http-запросов, если они вообще всё ещё поддерживаются в современном Хроме.

**Comment by Magicanum** [comment]
Спасибо за ответ. Поставил все галочки буду наблюдать. Попробую как Вы предложили, если не поможет, уберу из сетевых настроек системы адрес PAC скрипта антизапрета. Отпишусь сюда позже.

**Comment by ilyaigpetrov** [comment]
В PAC-скрипте «Антицензорити» была обнаружена ошибка, при которой в случае запроса к домену, начинающемуся с точки, скрипт впадал в вечный цикл. Только что исправлено, обновите PAC-скрипт через: иконка синей ленты -> нажать [обновить].

**Comment by ilyaigpetrov** [comment]
Также исправлен случай, когда точек в начале имени хоста может быть несколько. Обновите ещё раз, пожалуйста.

**Comment by capricornusx** [comment]
> 

можно помочь с раздачей этого файла?

**Comment by capricornusx** [comment]
> PAC-файл антизапрета раздаётся через шлюз распределенной файловой системы IPFS...

@ValdikSS, можно помочь с раздачей этого файла через IPFS?

**Comment by ValdikSS** [comment]
> > PAC-файл антизапрета раздаётся через шлюз распределенной файловой системы IPFS...
> 
> @ValdikSS, можно помочь с раздачей этого файла через IPFS?

Для этого используются шлюзы cloudflare, ipfs.io, еще через парочку других прогружается. Файлы меняются раз в 6 часов, недостатка кеширования нет, так что не виду смысла.

Почему вы спрашиваете? У вас что-то не так работает?

**Comment by capricornusx** [comment]
> Почему вы спрашиваете? У вас что-то не так работает?

Всё работает, было просто интересно поучастовать со стороны ipfs :)
