### ISSUE TITLE
Не работают запароленные прокси на Https

### ISSUE THREAD

**Issue by McAshesha** [anticensority/runet-censorship-bypass#296]
В вики прочитал, что работают запароленные прокси https, но у меня не грузит ни один сайт. Работает только запароленный Proxy/Http, но мне для нужен конкретно https. Также при добавлении Https (или Proxy/Http) добавляется мой введенный прокси и второй пустой. Приходится его удалять, чтобы применить настройки и посмотреть на результат

**Comment by ilyaigpetrov** [comment]
Некоторые VPN-провайдеры утверждают, что предоставляют доступ через HTTPS-прокси, которые на деле оказываются обыкновенными HTTP/PROXY.

Проверьте ваш прокси с помощью curl:
```sh-session
curl --proxy "<тип>://<логин>:<пароль>@<адрес>:<порт>" "https://meduza.io"
```

**Comment by McAshesha** [comment]
> Некоторые VPN-провайдеры утверждают, что предоставляют доступ через HTTPS-прокси, которые на деле оказываются обыкновенными HTTP/PROXY.
> 
> Проверьте ваш прокси с помощью curl:
> 
> ```
> curl --proxy "<тип>://<логин>:<пароль>@<адрес>:<порт>" "https://meduza.io"
> ```

Да, вы правы. Почти все продают http прокси под видом https. Могли бы порекомендовать какие нибудь платформы с действительными https прокси?

**Comment by ilyaigpetrov** [comment]
Не могу порекомендовать, т.к. сам такими платформами не пользуюсь.
Я лишь слышал о https://proxy-seller.io -- вы можете спросить у их консультанта или в поддержке в действительности ли предоставляемые ими HTTPS-прокси доступны по httpS (не путать с доступом к httpS-сайтам).
