### ISSUE TITLE
Перегрузка серверов: проблема с PAC-скриптом и заблокированными сайтами

### ISSUE THREAD

**Issue by electrifying** [anticensority/runet-censorship-bypass#30]
Здравствуйте. Я знаю, что тут присутствуют разработчик pac листа антизапрета и поэтому у меня к нему вопрос. В хроме Версия 3.2.4.23 (Официальная сборка), (64 бит) (Chromium 64.0.3282.140)
Недавно заблокированные сайты начали загружаться очень долго. Иногда такое тоже происходило, но автор сообщал что это было из-за запросов mail.ru в pac-листе. Так вот, не могли бы вы сообщить в чем снова проблема. Незаблокированные сайты загружаться быстро.

**Comment by electrifying** [comment]
Вот тут аналогичная проблема.

https://github.com/anticensority/runet-censorship-bypass/issues/25

**Comment by electrifying** [comment]
Перед этим подключение и скачивание прокси сервера шло около минуты

https://d.radikal.ru/d13/1804/ce/ec2ed3601e06.png

**Comment by ilyaigpetrov** [comment]
Потому что наши серверы перегружены. Ждём новостей от @ValdikSS.

**Comment by ValdikSS** [comment]
Добавил отдельные серверы для заблокированных недавно сегментов. Должно тормозить не хуже обычного.

**Comment by electrifying** [comment]
@ValdikSS
Здравствуйте, спасибо за комментарий но, кажется, вы еще хуже сделали теперь бывает что заблокированные сайты моментально грузит, а после пары перезагрузок страницы/рестарта браузера он может их снова по минуте грузить и так по разному.

**Comment by ValdikSS** [comment]
Попробуйте через 10 минут, напишите, есть ли эта проблема.

**Comment by electrifying** [comment]
Было все хорошо, но теперь снова долго.

**Comment by ValdikSS** [comment]
Один из прокси-серверов находится в теперь уже заблокированном диапазоне. Как только вы на него попадаете, браузер ждет ответа какое-то количество времени. Придется менять, сделаю завтра.

**Comment by ValdikSS** [comment]
Добавил новые серверы, убрал заблокированный.
