### ISSUE TITLE
%x в счётчике

### ISSUE THREAD

**Issue by aolko** [anticensority/runet-censorship-bypass#31]
кажется кто-то передал не ту переменную или не заменил шаблон счётчика
![](https://i.imgur.com/x7yAUDb.png)

**Comment by ilyaigpetrov** [comment]
%1 означает, что:

1) проксируется один адрес (1),
2) сама открытая страница не проксируется, но проксируются её подзапросы (%).

Так может быть, к примеру, если страница не проксируется, а расположенная на ней картинка разблокируется и потому проксируется.

**Comment by ilyaigpetrov** [comment]
https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%A7%D1%82%D0%BE-%D0%BE%D0%B7%D0%BD%D0%B0%D1%87%D0%B0%D0%B5%D1%82-%25x-%D0%BD%D0%B0-%D0%B1%D0%B5%D0%B9%D0%B4%D0%B6%D0%B8%D0%BA%D0%B5%3F
