### ISSUE TITLE
Google Chrome просит у меня удалить расширение Antizapret

### ISSUE THREAD

**Issue by WhyD1dY0uB4nn3dM3** [anticensority/runet-censorship-bypass#317]
Гугл лично просит у меня удаления данного расширения, так как она уже не может помочь с ней как-то помочь. Я при такой возможности, **отказался**. Потому что... Ну зачем именно его сейчас удалять, если единственные аналоги это только те VPN, которые взламывают ваши данные? Если автор обещал сделать обновление для такого браузера как гугл, то он обязательно обновит это. Скажите пожалуйста, тут я неправ?

**Comment by ilyaigpetrov** [comment]
Должно быть, я просто делился планами написать новую версию на новом API (Manifest V3), но вряд ли обещал.
Если я не успею выпустить MV3-версию и текущая версия будет удалена из магазгинов, то какое-то время можно пользоваться вручную установленной версией отсюда: https://github.com/anticensority/runet-censorship-bypass/releases.

**Comment by Fan4eGGG** [comment]
я сижу на новой Opera One и она останется работать на втором манифесте судя по обещаниям, тк куча полезных расширений для меня улетят :(
