### ISSUE TITLE
Странный домен 

### ISSUE THREAD

**Issue by constantin-online** [anticensority/runet-censorship-bypass#322]
Привет. В хроме у меня на странице скачивания, если нажать на расширение, выдает домен, который я никогда в жизни не посещал. Почему так?
![image](https://github.com/user-attachments/assets/0480fb0f-7d43-4804-95ee-6363d1b41914)

**Comment by ilyaigpetrov** [comment]
Это пример. Он серый, а не чёрный.
Какой-то адрес мне туда нужно было вписать.

**Comment by ilyaigpetrov** [comment]
Offtopic: Для концентрации мне нравится слушать Mirror's Edge 1&2 OST.
