### ISSUE TITLE
Как настроить Антизапрет, дабы он работал как Fastproxy? 

### ISSUE THREAD

**Issue by c4sua11** [anticensority/runet-censorship-bypass#325]
Сразу скажу, в этом вопросе не разбираюсь от слова совсем. До того, как наткнулся на статью о том, что Fastproxy вредоносное расширение, пользовался им и бед не знал, однако после прочтения сразу же снёс его и пожаловался. Но увы, проксирует оно кратно больше сайтов. Попытался поставить свой прокси от Hidemyname - к сожалению ничего не вышло, ERR_PROXY_CONNECTION_FAILED. Хотелось бы такой же функционал, как у вредоносного конкурента, как это можно реализовать?

**Comment by ilyaigpetrov** [comment]
В данное время могут с перебоями работать социальные сети (facebook, x.com, instagram).
Если интересующий вас сайт не из этого списка, то см. https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.

**Comment by Verity-Freedom** [comment]
@ilyaigpetrov в последнее время автор Антизапрета починил проксирование, не было ни одного сбоя где-то всю неделю или даже дольше.

Мне кажется issue в очередной раз отсылается к отсутствию функционала расширения временно завернуть весь трафик в свои прокси. Как дела обстоят в Fastproxy не знаю, не пользовался. Очень хочу в новой версии расширения получить этот режим - вместо того чтобы запихивать в проксируемые исключения например все адреса Спотифая, просто взять и галочкой переключить режим. В последнее время пришлось слезать с Обхода на Омегу, а Обходом пользуюсь как чекером, ибо только он показывает все адреса, проксируемые через localhost. Хочется чтобы Обход был не хуже по функционалу чем старая Омега.

**Comment by c4sua11** [comment]
@Verity-Freedom вся соль в том, что Fast Proxy использует сервера Антизапрета (во всяком случае использовал). Я вообще скорее за добавление функционала проксирования собственных адресов, через их сервера, но это уже кучу раз оговорено и невозможно

**Comment by Verity-Freedom** [comment]
> через их сервера, но это уже кучу раз оговорено и невозможно

Используйте базово Тор, через расширение. Для такого (если следовать этим формулировкам в точности) даже Омега не понадобится. Сегодня Тор был обновлён с разделением версий для вин 7 и всего того что выше.
