### ISSUE TITLE
Не работает YouTube и Discord 07.11.2024

### ISSUE THREAD

**Issue by DontiMonti** [anticensority/runet-censorship-bypass#326]
Как я понял, он должен давать доступ к youtube, но мне хотелось бы и доступ к discord, однако при включении расширения эти сайты так-же не работают. Если кто может, то помогите пожалуйста

**Comment by ilyaigpetrov** [comment]
Мы не проксируем ни youtube, ни голос в discord.
Наши решения работают по [реестру](https://reestr.rublacklist.net) РКН.
Если адреса нет в реестре, то он не проксируется.
См. также: https://github.com/anticensority/runet-censorship-bypass/wiki/Как-добавить-свой-сайт%3F.

**Comment by DontiMonti** [comment]
Дискорд есть в реестре ркн, но всё равно спасибо

**Comment by ilyaigpetrov** [comment]
> Дискорд есть в реестре ркн

Не могу найти: см. https://reestr.rublacklist.net/ru/?q=discord.com.

**Comment by Verity-Freedom** [comment]
Тор даёт доступ в дискорд, но не к голосовым чатам. Антизапрет к голосовым чатам доступ тоже не даст (никогда, технической возможности нет). Базы данных не обновлялись с начала октября из-за переполнения. Для Ютуба тоже нужен Тор.
