### ISSUE TITLE
Ошибка при включении WARP из-за удаления SOCKS5 в версии 2024.9.346.0

### ISSUE THREAD

**Issue by belext** [anticensority/runet-censorship-bypass#329]
**Проблема**:
При включении "Использовать WARP как прокси" сайты выдают ошибку `ERR_PROXY_CONNECTION_FAILED`

**Решение**:
Отключить галку "Использовать WARP как прокси", включить "Использовать СВОИ прокси" и добавить SOCKS**4**-прокси `127.0.0.1:40000` (не SOCKS5, а именно 4)

**Подробности**:
Пользуюсь расширением в Chromium 126 в режиме "только свои сайты и прокси", чтобы разблокировать до десятка нужных сайтов.
В Беларуси пока не заблокирован WARP, поэтому в качестве прокси использую его по [инструкции](https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%98%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D1%81-CloudFlare-WARP).

Около месяца назад с включенной галкой "Использовать WARP как прокси" внезапно стали появляться ошибки `ERR_PROXY_CONNECTION_FAILED` на заблокированных сайтах.
Быстрое решение найти не смог, поэтому расширение отключил.

Но сегодня снова решил разобраться и нашел причину: обновился сам WARP до версии 2024.9.346.0
В ней, как оказалось, либо удалили, либо сломали поддержку SOCKS5:
- https://community.cloudflare.com/t/cloudflare-warp-version-2024-9-346-0-proxy-mode-issue/720751
- https://community.cloudflare.com/t/cloudflare-warp-version-2024-9-346-0-proxy-mode-issue/734315

И действительно, если снять галку "Использовать WARP как прокси", поставить "Использовать СВОИ прокси" и добавить вручную SOCKS5-прокси `127.0.0.1:40000`, то ошибка поменяется на `ERR_SOCKS_CONNECTION_FAILED`.
А если удалить SOCKS5 и добавить SOCKS4-прокси с тем же адресом, то ошибки уходят.

Решил глянуть код, вижу там помимо SOCKS5 есть вариант HTTPS:
https://github.com/anticensority/runet-censorship-bypass/blob/d86cf384af42219a74317e12809541c4e783fe0e/extensions/chromium/runet-censorship-bypass/src/extension-common/35-pac-kitchen-api.js#L255-L258

Если прописать свой HTTPS-прокси `127.0.0.1:40000`, то тоже ошибка: `ERR_PROXY_CONNECTION_FAILED`.
Возможно, стоит добавить SOCKS4-вариант в этот массив как альтернативный.

**Comment by ilyaigpetrov** [comment]
Спасибо за качественную обратную связь!

К сожалению, я не добавляю новый функционал и не развиваю существующее расширение.
Первостепенной задачей данного проекта на текущий момент является миграция на новые требования WebStore в виде Manifest V3. 
Последние усилия с моей стороны, направленные на достижение этой цели, датируются 22 августом 2024.
Если вы хотите поучаствовать -- задавайте вопросы, изучайте [код](https://github.com/anticensority/runet-censorship-bypass/tree/migration-to-mv3-30-07-2024), присылайте PR.

**Comment by belext** [comment]
Cloudflare WARP обновился для версии 2024.11.309.0, проблема ушла.
SOCKS5-прокси снова работают, так что и галка "Использовать WARP как прокси" - тоже.
Закрываю ишью, спасибо за работу!
P.S. Сам сижу сборке Chromium, где не будут убирать поддержку V3 ([Supermium](https://github.com/win32ss/supermium)). Так что расширение должно радовать еще долгие годы 🙂
