### ISSUE TITLE
PAC-скрипт «Антицензорити» перестал работать без своих прокси

### ISSUE THREAD

**Issue by iSpid3r** [anticensority/runet-censorship-bypass#33]
Скрипт обновлен, но сайты не открываются (как минимум, rutracker, nnm-club и telegram.org).

**Comment by ilyaigpetrov** [comment]
Какой PAC-скрипт вы используете: "Антицензорити" или "Антизапрет"?
На "Антизапрете" всё должно открываться.
А "Антицензорити" теперь работает только на своих прокси, вот [новость](https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-387436191).

**Comment by IceArms** [comment]
Илья, а не подскажете, какой конкретно pac-скрипт сейчас наиболее актуален? А то из новости не понял. Если можно, дайте ссылку, пожалуйста.

**Comment by ilyaigpetrov** [comment]
@IceArms 
Используйте "Антизапрет", если у вас нет своих прокси. Этот PAC-скрипт покрывает не все случаи блокировок, но зато не нужно иметь своих прокси.

Используйте "Антицензорити", если ваш гадкий провайдер блочит слишком много (блочит все сайты на одном IP). Однако этот PAC-скрипт теперь требует своих прокси или локальный Тор.

**Comment by IceArms** [comment]
@ilyaigpetrov 
Спасибо за разъяснение, теперь всё ясно!
А есть где-нибудь поблизости инструкция, как самому создать прокси для использования с "Антицензорити"? Или нужен VPN для этого?

**Comment by ilyaigpetrov** [comment]
VPN для этого не нужно, нужно иметь некоторые познания, желательно в Linux, и иметь свой сервер (VPS) в какой-нибудь более либеральной стране.
Легче будет не поднимать свои прокси, а использовать Tor, есть инструкция: https://git.io/ac-tor

**Comment by ilyaigpetrov** [comment]
Проверить гадкий ли у вас провайдер в данный момент можно на http://mp3-muzon.com (IP = 91.234.32.16). Если блочится, то гадкий. Метод будет работать, пока mp3-muzon.com не сменит IP.

**Comment by IceArms** [comment]
@ilyaigpetrov 
Большущее спасибо за ответы! И за инструкцию по Тору отдельная благодарность!

**Comment by ilyaigpetrov** [comment]
@iSpid3r, простите за оффтопик.
Ваша проблема была в том, что вас не перекинуло на "Антизапрет" автоматом?
Сейчас проблема решена?

**Comment by iSpid3r** [comment]
Да, после вашего первого сообщения вставил в Firefox ссылку на «Антизапрет» и все отлично заработало, спасибо. Просто не был в курсе новости.
