### ISSUE TITLE
facebook.com не работает из-за сбоя АнтиЗапрета 07.12.2024

### ISSUE THREAD

**Issue by Amrusy** [anticensority/runet-censorship-bypass#332]

**Comment by ilyaigpetrov** [comment]
Hi.
We have some temporary problems.
Follow the news / следите за новостями: https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-2524588989.

**Comment by ilyaigpetrov** [comment]
Сейчас должно работать / Now it should work.
