### ISSUE TITLE
не работает белый список

### ISSUE THREAD

**Issue by Alexandr-sudo** [anticensority/runet-censorship-bypass#333]
Я использую свой прокси и добавил сайт в белый список.
![Снимок1](https://github.com/user-attachments/assets/057cd840-111e-4693-a3f4-79e75871eeef)
Однако он не проскируется через прокси, а идет напрямую. 
![image](https://github.com/user-attachments/assets/6fc278a3-2bb4-46ff-a83b-26b7bddb102c)
Например animego.online
Это видно через wireshark
![image](https://github.com/user-attachments/assets/5760facc-5cb2-4189-8402-0379258f2266)

Можно это как-то поправить, кстати instagramm точно также себя ведет. Ощущение, что есть некий блок с вашей стороны на ряд доменов (jut.su проксируется).
Если это так, то можно как-то при использование своего прокси убрать ограничение.

Проблема не на одном пк, а на нескольких разных.

**Comment by NAVIGATOR19** [comment]
![image](https://github.com/user-attachments/assets/db54ea09-915c-4c5f-b4be-7d27b8cb5899)
Вот так сделай

**Comment by Alexandr-sudo** [comment]
Да, помогло.
Спасибо

Жаль что нет возможности комбинировать белый список с Антизапрет(

**Comment by NAVIGATOR19** [comment]
> Да, помогло. Спасибо
> 
> Жаль что нет возможности комбинировать белый список с Антизапрет(

Да можно, просто антизапрет не работает, это временное решение
