### ISSUE TITLE
Не обновляет pac-скрипт. Ошибка `Can't access dead object`

### ISSUE THREAD

**Issue by Mix444** [anticensority/runet-censorship-bypass#338]
В моменте поставил вместо антизапрета антицензорити. После расширение 
перестало работать. Переключится обратно помогло только сброс к 
начальным настройкам, но обновление не проходит.
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0",
  "platform": "Win32",
  "version": "0.0.1.66",
  "ext-error": {
![Новый точечный рисунок](https://github.com/user-attachments/assets/75a180ee-0ae0-4129-8107-f509cce0de26)

    "message": "TypeError: can't access dead object",
    "filename": "moz-extension://d514dd2d-9445-4126-8748-9a87ee561e0d/37-sync-pac-script-with-pac-provider-api.js",
    "lineno": 57,
    "colno": 9,
    "error": {
      "fileName": "moz-extension://d514dd2d-9445-4126-8748-9a87ee561e0d/37-sync-pac-script-with-pac-provider-api.js",
      "lineNumber": 57,
      "columnNumber": 9,
      "message": "can't access dead object",
      "name": "TypeError"
    },
    "type": "error"
  }
}
Браузер: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
ОС: Win32
Версия расширения: 0.0.1.66

**Comment by jbionic2016** [comment]
Та же фигня

Non-critical error. Don't worry: it works.
✘ Couldn't find OWN proxies. This PAC-script works only with [OWN proxies](https://git.io/ac-own-proxy) (by default local [Tor](https://git.io/ac-tor) will be used).



> 
> 
> <html>
> <body>
> 
> омер | Хост | Ошибка | Все
> -- | -- | -- | --
> 0 | antizapret.prostovpn.org | net::ERR_TUNNEL_CONNECTION_FAILED |  
> 1 | antizapret.prostovpn.org | net::ERR_TUNNEL_CONNECTION_FAILED |  
> 2 | e.cen.rodeo | net::ERR_TUNNEL_CONNECTION_FAILED |  
> 3 | antizapret.prostovpn.org | net::ERR_TUNNEL_CONNECTION_FAILED |  
> 4 | antizapret.prostovpn.org | net::ERR_TUNNEL_CONNECTION_FAILED |  
> 5 | e.cen.rodeo | net::ERR_TUNNEL_CONNECTION_FAILED |  
> 6 | ipfs.io | net::ERR_SSL_PROTOCOL_ERROR |  
> 7 | antizapret.prostovpn.org | net::ERR_CONNECTION_RESET |  
> 8 | ipfs.io | net::ERR_CONNECTION_RESET |  
> 9 | ipfs.io | net::ERR_SSL_PROTOCOL_ERROR |  
> 10 | ipfs.io | net::ERR_SSL_PROTOCOL_ERROR |  
> 11 | antizapret.prostovpn.org | net::ERR_CONNECTION_RESET |  
> 12 | ipfs.io | net::ERR_SSL_PROTOCOL_ERROR
> 
> 
> </body>
> </html>омер	Хост	Ошибка	[Все](chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/errors-to-exc/index.html)
> 0	antizapret.prostovpn.org	net::ERR_TUNNEL_CONNECTION_FAILED	
> 1	antizapret.prostovpn.org	net::ERR_TUNNEL_CONNECTION_FAILED	
> 2	e.cen.rodeo	net::ERR_TUNNEL_CONNECTION_FAILED	
> 3	antizapret.prostovpn.org	net::ERR_TUNNEL_CONNECTION_FAILED	
> 4	antizapret.prostovpn.org	net::ERR_TUNNEL_CONNECTION_FAILED	
> 5	e.cen.rodeo	net::ERR_TUNNEL_CONNECTION_FAILED	
> 6	ipfs.io	net::ERR_SSL_PROTOCOL_ERROR	
> 7	antizapret.prostovpn.org	net::ERR_CONNECTION_RESET	
> 8	ipfs.io	net::ERR_CONNECTION_RESET	
> 9	ipfs.io	net::ERR_SSL_PROTOCOL_ERROR	
> 10	ipfs.io	net::ERR_SSL_PROTOCOL_ERROR	
> 11	antizapret.prostovpn.org	net::ERR_CONNECTION_RESET	
> 12	ipfs.io	net::ERR_SSL_PROTOCOL_ERROR

**Comment by ilyaigpetrov** [comment]
@Mix444, были проблемы на нашей стороне, сейчас должно обновляться без ошибок.
Про ошибку см. https://github.com/anticensority/runet-censorship-bypass/issues/91#issuecomment-784951001.

**Comment by ilyaigpetrov** [comment]
@jbionic2016, у вас же какая-то другая ошибка -- создайте новое обсуждение и предоставьте больше данных.
