### ISSUE TITLE
PAC-скрипт «Антизапрет» не работает без расширения в Хром

### ISSUE THREAD

**Issue by electrifying** [anticensority/runet-censorship-bypass#34]
win 10 1803
chrome x64
Pac лист от антизапрет перестал пускать на заблокированные сайты в чем проблема? Спасибо за ответы.

В расширении Обход блокировок Рунета pac лист работает, если без расширения просто прописать вручную, доступ к сайтам заблокирован.

**Comment by ValdikSS** [comment]
PAC-лист стал размером больше 1 мегабайта, из-за чего Chrome считает его слишком большим и не применяет.
Напишите, что вам нужна поддержка файлов больше 1 мегабайта на багтрекере Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=678022

**Comment by ValdikSS** [comment]
Я убрал некоторые домены из листа, теперь он чуть меньше мегабайта, но как только что-то изменится, все опять сломается.

**Comment by electrifying** [comment]
@ValdikSS,здравствуйте. Я так понимаю pac лист снова больше 1 мегабайта стал?

**Comment by ValdikSS** [comment]
@electrifying да. Пытаюсь его уменьшить.

**Comment by electrifying** [comment]
@ValdikSS И снова здравствуйте. Pac лист снова испытывает проблемы? Очень долго идет получение ответа от pac листа из-за чего любые сайты не грузятся, отключение pac листа исправляет проблему. Спасибо.

**Comment by ValdikSS** [comment]
Не вижу проблемы, но вы не первый, кто жалуется. У меня все в порядке во всех браузерах.

**Comment by electrifying** [comment]
@ValdikSS на моменте написания прошлого сообщения pac лист не функционировал в хроме, в едже работал. Потом снова все стало в порядке.

**Comment by electrifying** [comment]
@ValdikSS Здравствуйте, в хроме снова перестал работать pac лист.

**Comment by ValdikSS** [comment]
Это потому что он стал пустым. На Sourceforge технические работы, поэтому обновление листа сделало его пустым. Обновится в течение часа.

**Comment by electrifying** [comment]
@ValdikSS Pac лист снова перестал работать в хроме.

**Comment by ValdikSS** [comment]
Добавил новые оптимизации для уменьшения размера.

**Comment by electrifying** [comment]
@ValdikSS Cайт RUTOR.INFO почему-то перестал работать, с остальными сайтами все в порядке.

**Comment by ValdikSS** [comment]
Исправил.

**Comment by electrifying** [comment]
@ValdikSS Здравствуйте. Pac лист снова прекратил свою работу.

**Comment by ValdikSS** [comment]
@electrifying, используйте расширение.

**Comment by electrifying** [comment]
@ValdikSS  А что теперь просто список не будет работать?

**Comment by ValdikSS** [comment]
Я не знаю, как его можно еще оптимизировать.

**Comment by ValdikSS** [comment]
Можете написать напрямую разработчикам Chrome, что вам нужна поддержка листов более 1 МБ: https://bugs.chromium.org/p/chromium/issues/detail?id=678022

**Comment by ValdikSS** [comment]
Оптимизировал еще, должно помочь на какое-то время.

**Comment by prog-it** [comment]
Можно еще оптимизировать, добавив под замену: website и pro. На символы: < и >. У себя так сделал.
На всякий случай, прикрепляю топ доменов.
[top.txt](https://github.com/anticensority/runet-censorship-bypass/files/2100347/top.txt)

**Comment by favorart** [comment]
Снова не работает, ни в IE, ни в vivaldi

**Comment by ValdikSS** [comment]
У меня работает во всех браузерах.

**Comment by electrifying** [comment]
@ValdikSS Здравствуйте, подтверждаю pac лист снова перестал работать.  Расширение работает, видимо, лист снова стал больше 1 мб и нужна оптимизация.

**Comment by ValdikSS** [comment]
Я только что проверил в Firefox, Chromium и Edge — везде работает. Попробуйте выяснить причину неработоспособности самостоятельно.

**Comment by SagePtr** [comment]
Отвалился список адресов внутри pac-скрипта, выглядит вот так:
```
d_ad = "\
archive( \
".split(" ");

d_eh = "\
\
".split(" ");

d_il = "\
lostfilm.tv \
".split(" ");

d_mp = "\
nnm-club.ws \
".split(" ");

d_qt = "\
\
".split(" ");

d_uz = "\
\
".split(" ");

d_other = "\
\
".split(" ");

d_ipaddr = "\
\
".match(/.{8}/g);
```
Соответственно, использовать его невозможно

**Comment by electrifying** [comment]
Да, pac лист снова не работает. Ждем уважаемого @ValdikSS для решения проблемы.

**Comment by electrifying** [comment]
@ValdikSS Pac лист снова не функционирует.

**Comment by electrifying** [comment]
@ValdikSS Pac лист вновь не работает.

**Comment by ValdikSS** [comment]
У меня PAC-лист работает. Не вижу проблем.
Это репозиторий расширения «Обход блокировок Рунета», не пишите сюда о проблемах антизапрета.

**Comment by ghost** [comment]
Никогда не смогу обновить его по клику в меню расширения, потому что 
https://antizapret.prostovpn.org/proxy.pac перехватывает наш сисадмин :) 
Подскажите, как всё-таки им воспользоваться?
Наличие урла антицензорити никак в таком случае не помогает, у меня просто срабатывает редирект...

**Comment by ilyaigpetrov** [comment]
> Это репозиторий расширения «Обход блокировок Рунета», не пишите сюда о проблемах антизапрета.

Адрес для проблем с «Антизапретом» находится в подвале https://antizapret.prostovpn.org.
Также можно написать в нашу гугл-группу (публично или приватно): https://groups.google.com/forum/#!forum/anticensority

**Comment by adadskiy** [comment]
Уменьшить PAC можно удалив всякие Казино и им подобные Фонбеты

**Comment by ValdikSS** [comment]
Это уже делается и так: https://bitbucket.org/anticensority/antizapret-pac-generator-light/src/master/config/exclude-regexp-dist.awk

**Comment by adadskiy** [comment]
https://gateway.ipfs.io/ipns/pacipfs2.antizapret.prostovpn.org/proxy-ssl.js     а это что

**Comment by Adalantares** [comment]
Видимо PAC снова за 1мб убежал, уже 2-3 дня отказывается в Chrome работать, в Firefox все работает хорошо.
