### ISSUE TITLE
портативный тор

### ISSUE THREAD

**Issue by Hotduder** [anticensority/runet-censorship-bypass#340]
По какой причине удалили портативный тор, где еще antitor.exe был, кто-нибудь знает ? Добавил его как прокси к расширению  антизапрета в режиме антицензорити

**Comment by Yastreb1333** [comment]
поддерживаю. зачем выпилили Verity-Freedom ?

копия страницы сохраненная яндексом уже потерлась )

https://yandexwebcache.net/yandbtm?fmode=inject&tm=1734018397&tld=ru&lang=en&la=1733263744&text=%D0%B0%D0%BD%D1%82%D0%B8%D1%82%D0%BE%D1%80&url=https%3A//github.com/Verity-Freedom/Tor-Portable&l10n=ru&mime=html&sign=ffc3d74c3f26df2bac2f5d567a196f8c&keyno=0

**Comment by d1mulka** [comment]
Тоже тор не находит

**Comment by d1mulka** [comment]
404 page

**Comment by Yastreb1333** [comment]
самая последняя версия от 9.12.2024 , автор Verity-Freedom  https://disk.yandex.ru/d/gzQ5FOokK0ddiQ

**Comment by Yastreb1333** [comment]
инструкция которая была на главной странице 

https://disk.yandex.ru/d/eVgPOOHVRtrbcw

**Comment by Eikinskjaldi89** [comment]
Вроде сейчас всё на месте. Пару часов назад тоже было 404.

**Comment by Yastreb1333** [comment]
да заработало

**Comment by Verity-Freedom** [comment]
@Yastreb1333 мой аккаунт флагнули как подозрительный по неизвестным причинам (могу только подозревать что это или из-за частого использования 2FA кодов восстановления для входа или из-за 20 фоллспозитивов из 70 на AntiTor.exe на Вирустотале, притом что исходный код в виде AntiTor.cmd чистый), я надеюсь что в поддержке поняли что решение было ошибочным и подобный цирк не продолжится.

**Comment by Yastreb1333** [comment]
> мой аккаунт флагнули

капец. надеюсь больше такого не повторится

**Comment by Verity-Freedom** [comment]
> > мой аккаунт флагнули
> 
> капец. надеюсь больше такого не повторится

Если свиньи будут меня репортами закидывать на то что вирустотал показал одну реакцию из 100, то повторится и восстановить не получится, я вообще удивлён что так быстро восстановили всё. Я воспользовался кодом аутентификации из 2FA расширения и создал сразу запрос в поддержку, а сейчас ещё и второй email добавил для восстановления.

**Comment by Yastreb1333** [comment]
надо какой то резервный вариант, хотя бы на яндексе или гугле копию всего что выкладывалось )

**Comment by Yastreb1333** [comment]
или 4pda или рутрекер или еще хрен знает куда выложить. а лучше везде )

**Comment by Verity-Freedom** [comment]
> надо какой то резервный вариант, хотя бы на яндексе или гугле копию всего что выкладывалось )

Есть куча ссылок на Я.Диск. Просто если мужик в костюме клоуна подойдёт к тебе на улице и пырнёт ножом безумно смеясь, от такого никто не застрахован. Когда Аннушка уже разлила масло, человек не просто смертен, а внезапно смертен. На уже установленную программу это благо не влияет никаким образом.

**Comment by Yastreb1333** [comment]
> Есть куча ссылок на Я.Диск.

может и есть, но вот просто взять и найти какую либо информацию по данному вопросу просто невозможно. ее просто нет. все что находило было выпилено.

**Comment by Verity-Freedom** [comment]
> > Есть куча ссылок на Я.Диск.
> 
> может и есть, но вот просто взять и найти какую либо информацию по данному вопросу просто невозможно. ее просто нет. все что находило было выпилено.

Может персонально до меня делала запрос российская власть к Гитхабу. Я не знаю ничего. На почту мне не приходило информации. Но тема портативный тор (не от разработчиков расширения) содержит ссылку на Я.Диск. Это ещё и моя репутация, если меня выпиливает Гитхаб, то многие могут подумать, что не по хорошей причине. Инструкция написана в markdown с кучей изображений которую так просто не найти. Много минусов и я это ничем конечно не заслужил.

**Comment by Verity-Freedom** [comment]
Кстати может и мои темы были какое-то время не видны пока специалисты Гитхаба по кибербезопасности проверяли legit я или не legit, если подобное повторится, то они официально свиньи-клоуны жиреющие.

**Comment by Yastreb1333** [comment]
> Кстати может и мои темы были какое-то время не видны

пока ты был в блоке я пытался найти хоть что то в яндексе. было несколько ссылок которые вели на 404 и было несколько сохраненных страниц яндексом. через короткое время и эти копии пропали ))

**Comment by Eikinskjaldi89** [comment]
> Кстати может и мои темы были какое-то время не видны пока специалисты Гитхаба по кибербезопасности проверяли legit я или не legit, если подобное повторится, то они официально свиньи-клоуны жиреющие.

Темы были не видны 100%. Утром тут было 120+ open issues, потом после блокировки аккаунта стало 114, а теперь снова 125.

**Comment by Verity-Freedom** [comment]
> > Кстати может и мои темы были какое-то время не видны пока специалисты Гитхаба по кибербезопасности проверяли legit я или не legit, если подобное повторится, то они официально свиньи-клоуны жиреющие.
> 
> Темы были не видны 100%. Утром тут было 120+ open issues, потом после блокировки аккаунта стало 114, а теперь снова 125.

Я тебе кстати по поводу Антицензорити ответил примерно в это же время возможно ты пропустил.

**Comment by Verity-Freedom** [comment]
Вижу что ты разобрался полчаса назад ответ был, да.

**Comment by Verity-Freedom** [comment]
Поступили объяснения от Гитхаба. Прекрасный человек из саппорта извинился, сказал что я попал под автоматический скрипт, почему-то посчитавший меня за спамера, который флагнул меня. С меня сняли флаг и тема была закрыта. Большое всем спасибо за моральную поддержку.
