### ISSUE TITLE
Runet censorship doesn't work

### ISSUE THREAD

**Issue by jbionic2016** [anticensority/runet-censorship-bypass#341]
В продолжение обсуждения, начатого тут:
https://github.com/anticensority/runet-censorship-bypass/issues/338#issuecomment-2539536635

прикрепляю видео для демонстрации проблемы
https://youtu.be/yQ0NatZTrAI

Пытался переустановить расширение - не помогло.

Удалил.

**Comment by ilyaigpetrov** [comment]
Если видео записано до 12.12.2024, то сейчас должно быть исправлено.

**Comment by jbionic2016** [comment]
> Если видео записано до 12.12.2024, то сейчас должно быть исправлено.

видео записано за 2 минуты до опубликования issue.
Вы долго ещё собираетесь фантазировать вокруг "уже исправлено"?

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Частые-проблемы#не-удалось-скачать-pac-скрипт-с-адресов--httpsantizapretprostovpnorgproxypac%2D.

**Comment by jbionic2016** [comment]
Удалил расширение. Благодарю за внимание.
