### ISSUE TITLE
На YouTube нельзя пользоваться блокировщиками рекламы

### ISSUE THREAD

**Issue by ilyaigpetrov** [anticensority/runet-censorship-bypass#346]
@Yastreb1333 пишет:

> а мне вот такое сейчас выдало
>
>![Ютуб](https://github.com/user-attachments/assets/58e0adbe-f394-4fef-bf92-54309ac2c620)

**Comment by ilyaigpetrov** [comment]
Вероятно, какой-то единичный адрес в трафике к youtube (аватврки, например) проксируется расширением, а Google думает, что это делает блокировщик.
Нужно выявить адрес этого ресурса и добавить его в исключения: Иконка синей ленты -> "Exceptions / Исключения" -> Вбить адрес -> Выбрать "No / Нет" (не проксировать).

**Comment by Verity-Freedom** [comment]
> @Yastreb1333 пишет:
> 
> > а мне вот такое сейчас выдало
> > ![Ютуб](https://private-user-images.githubusercontent.com/185175948/397855649-58e0adbe-f394-4fef-bf92-54309ac2c620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDg3NjgsIm5iZiI6MTczNDgwODQ2OCwicGF0aCI6Ii8xODUxNzU5NDgvMzk3ODU1NjQ5LTU4ZTBhZGJlLWYzOTQtNGZlZi1iZjkyLTU0MzA5YWMyYzYyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxOTE0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTAwMDczYzRlNDM1YzM0MzVjN2FkNzI5N2E4NDhlZGY5NTczYzU4ZmQ0MGY2YmY1NTYwZjg0YmI4Yjc5OTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VIa5xjJc344YiHMLrFRBCVy2hU2vucKLJFz8fvEhWiQ)

@Yastreb1333 юзает портативный Тор и вероятно Ublock Origin. К Обходу блокировок рунета очень вряд ли описанное имеет отношение.

**Comment by Verity-Freedom** [comment]
Я у себя его очень часто вижу.

**Comment by Verity-Freedom** [comment]
Антизапрет по умолчанию Ютуб не проксирует. У меня проксируется всего несколько домёнов но они множество поддомёнов захватывают.

**Comment by Yastreb1333** [comment]
> Вероятно, какой-то единичный адрес в трафике к youtube (аватврки, например) проксируется расширением, а Google думает, что это делает блокировщик.
> Нужно выявить адрес этого ресурса и добавить его в исключения: Иконка синей ленты -> "Exceptions / Исключения" -> Вбить адрес -> Выбрать "No / Нет" (не проксировать).

извините за этот скриншот. к вашему приложению он не имеет никакого отношения. вообще.
