### ISSUE TITLE
Расширение открывает не все сайты

### ISSUE THREAD

**Issue by DStrifer** [anticensority/runet-censorship-bypass#35]
Пришлось вернуться на Фригат! 
Это расширение перестало открывать нужные сайты. Дошло даже до идиотизма, он перестал открывать даже сайт http://modthesims.info/ и множество других игровых мод сайтов. 
Но при этом октрывает всякие руторы, ннм и прочие торрент-сайты.

**Comment by ilyaigpetrov** [comment]
Закрываю обращение как слишком старое. Если проблема всё ещё актуальна -- напишите.
