### ISSUE TITLE
Проблема с Pornhub.com

### ISSUE THREAD

**Issue by electrifying** [anticensority/runet-censorship-bypass#36]
Здравствуйте, я уже писал авторам поддерживающим расширение "обход блокировок рунета" о том, что при использовании pac листа сайт pornhub.com выдает сообщение IS UNDERGOING MAINTENANCE
 и даже после множественных перезагрузок не дает войти на сайт.  Илья Петров, отправил сообщение web мастерам pornhub но, видимо, исправлять проблему они не собираются. Поэтому возможно ли исключить сайт pornhub из pac листа ибо его Русская и интернациональная версия работают без pac листа.

**Comment by ilyaigpetrov** [comment]
Если вы пользуетесь расширением, то вкладка "Исключения" -> ввести *.
pornhub.com -> выбрать "нет" (не проксировать).
Если вы не пользуетесь расширением, то сообщите нам об этом и автор
PAC-скрипта "Антизапрет" примет решение.

P.S. Я не отправлял сообщение разработчикам pornhub.com, но это делал
другой разработчик.

2018-07-16 18:02 GMT+05:00 electrifying <notifications@github.com>:

**Comment by electrifying** [comment]
@ilyaigpetrov Здравствуйте, расширением не пользуюсь с ним-то все понятно. Писал сообщение на эту почту antizapret@prostovpn.org

**Comment by amazhara** [comment]
Leave Ph in upper intermidiate ❤️

**Comment by ilyaigpetrov** [comment]
Мы исключили PornHub из проксирования. Если ваш провайдер его не блокирует, то вам остаётся лишь обойти авторизацию вК (см. https://ntc.party/t/vk-pornhub/52/1).
