### ISSUE TITLE
Не работает в Хром + "Другое расширение контролирует настройки прокси!"

### ISSUE THREAD

**Issue by tinbka** [anticensority/runet-censorship-bypass#38]
```
{
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36",
  "platform": "Linux x86_64",
  "version": "0.0.1.29",
  "pac-error": "net::ERR_PAC_SCRIPT_FAILED\nline: 68: Uncaught TypeError: Cannot read property 'length' of null"
}
```

**Comment by ilyaigpetrov** [comment]
Мы уже исправили эту ошибку, попробуйте просто обновить PAC-скрипт:
иконка синей ленты -> нажать [обновить] (рядом с "Антизапрет").

**Comment by tinbka** [comment]
Теперь у меня вот такая проблема:
```
{
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36",
  "platform": "Linux x86_64",
  "version": "0.0.1.29",
  "pup-ext-err": {
    "stack": "Error: Другое расширение контролирует настройки прокси! <a href=\"chrome://settings/?search=прокси\">\n            Какое?\n          </a>\n    at handlers.updateControlState (chrome-extension://gnknjnebjldmkpmlhjipalimhjofpgho/37-sync-pac-script-with-pac-provider-api.js:75:13)\n    at chrome.proxy.settings.get.timeouted (chrome-extension://gnknjnebjldmkpmlhjipalimhjofpgho/11-error-handlers-api.js:163:13)\n    at setTimeout (chrome-extension://gnknjnebjldmkpmlhjipalimhjofpgho/00-init-apis.js:58:44)",
    "message": "Другое расширение контролирует настройки прокси! <a href=\"chrome://settings/?search=прокси\">\n            Какое?\n          </a>",
    "name": "Error"
  }
}
```
А тем временем chrome://settings/?search=прокси показывает, что ничто другое их не контролирует:
![image](https://user-images.githubusercontent.com/378869/45045767-b55cef00-b07c-11e8-9908-ae66efbc2102.png)

В Яндекс браузере почему-то такой проблемы нет.

**Comment by ilyaigpetrov** [comment]
иконка синей ленты -> Проблемы? -> Отладка PAC-скрипта -> READ.
Если результат похож на наш PAC-скрипт (особенно если есть строка:
`%#@@@@@@ PAC_KITCHEN_STARTS @@@@@@#%`), то попробуйте:

1. Удалить расширение.
2. Перезапустить браузер.
3. Установить расширение заново.

Если же результат похож на что-то другое, то постарайтесь найти и отключить расширение, контролирующее прокси.

**Comment by tinbka** [comment]
Ага, PAC_KITCHEN_STARTS есть. Удалил, убил хром, поставил заново. Больше не ругается на потерю контроля. Спасибо!

**Comment by ilyaigpetrov** [comment]
В будущем можно попробовать такой подход:

1. Иконка синей ленты -> отключить.
2. Иконка синей ленты -> включить "Антизапрет".
