### ISSUE TITLE
Ошибка `line: 68: Uncaught TypeError: Cannot read property 'length' of null"`

### ISSUE THREAD

**Issue by maximelkin** [anticensority/runet-censorship-bypass#39]
https://anticensority.github.io/error/0.0.0.17/?json=%7B%22pac-error%22%3A%22net%3A%3AERR_PAC_SCRIPT_FAILED%5Cnline%3A%2068%3A%20Uncaught%20TypeError%3A%20Cannot%20read%20property%20%27length%27%20of%20null%22%7D&type=pac-error&version=0.0.1.29&useragent=Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F69.0.3497.100%20Safari%2F537.36&platform=Linux%20x86_64

**Comment by ilyaigpetrov** [comment]
Исправлено.

**Comment by ilyaigpetrov** [comment]
Для обновления PAC-скрипта: иконка синей ленты -> нажать [обновить] (рядом с "Антизапретом").
