### ISSUE TITLE
Не удалось скачать PAC-скрипт с адресов antizapret.prostovpn.org (наши IP попали в блок)

### ISSUE THREAD

**Issue by franchesko1437** [anticensority/runet-censorship-bypass#40]
https://vk.cc/8yB9LJ
И выдает ошибку при обновлении пак скрипта: 🔥 Ошибка!
Не удалось скачать PAC-скрипт с адресов: [ https://antizapret.prostovpn.org/proxy.pac ]. > Что-то не так с сетью, проверьте соединение. > Failed to fetch [Техн.детали]

**Comment by franchesko1437** [comment]
Решил проблему. Спасибо за помощь очень помогла (нет).
У вас заблокирован доступ к сайту, на котором находится скрипт.
https://azpac.top/proxy-ssl.js
Пришлось включить другой впн, обновить скрипт, и включить уже скрипт без впн.

**Comment by ilyaigpetrov** [comment]
Не все провайдеры блокируют https://azpac.top/proxy-ssl.js.  
Автор PAC-скрипта "Антизапрет" в курсе проблемы и занимается её решением.  
Ответа от нас не было, т.к. я не хотел отвечать, пока проблема не будет решена и рассчитывал на быстрое решение.

**Comment by franchesko1437** [comment]
Могли бы и написать, что проблему можно было решить подобным способом, но нет.

**Comment by ilyaigpetrov** [comment]
Проблема решена, теперь PAC-скрипт должен обновляться без VPN.  
Простите за задержку.

**Comment by ilyaigpetrov** [comment]
Проблема будет периодически случаться. В данный момент, похоже, снова IP попал в реестр РКН. Мы снова сменим IP.

**Comment by franchesko1437** [comment]
Прикрутите загрузку файла допустим к облаку мейла, тогда наверное блокироваться не будет.

**Comment by BearWild** [comment]
После включение WireGuard, PAC скрипт обновляет. Но после отключения WireGuard, обход блокировки рунет не работает хотя скрипт подгружен

**Comment by Yaroos** [comment]
да, тоже перестал работать обход блокировки

**Comment by ilyaigpetrov** [comment]
Заглядывайте в новости проекта при поломках: см. https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-1501501105.

**Comment by D1zg** [comment]
Тоже попал на "Не удалось скачать PAC-скрипт с адресов". Включение VPN не помогло обновить.

**Comment by ilyaigpetrov** [comment]
@D1zg, пробовали отключать антивирус и блокировщики рекламы?
Какую ошибку выдаёт браузер при попытке открыть https://e.cen.rodeo:8443/proxy.pac?
Можно прислать скриншотом.

**Comment by D1zg** [comment]
@ilyaigpetrov дело в том, что как раз открывается. Есть вот такая ссылка на ошибку, полагаю полезно может быть?

https://anticensority.github.io/error/0.0.0.17/?json=%7B%22pup-ext-err%22%3A%7B%22message%22%3A%22%D0%9D%D0%B5%20%D1%83%D0%B4%D0%B0%D0%BB%D0%BE%D1%81%D1%8C%20%D1%81%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C%20PAC-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%20%D1%81%20%D0%B0%D0%B4%D1%80%D0%B5%D1%81%D0%BE%D0%B2%3A%20%5B%20https%3A%2F%2Fe.cen.rodeo%3A8443%2Fproxy.pac%20%2C%20https%3A%2F%2Fantizapret.prostovpn.org%3A8443%2Fproxy.pac%20%2C%20https%3A%2F%2Fantizapret.prostovpn.org%3A18443%2Fproxy.pac%20%2C%20https%3A%2F%2Fantizapret.prostovpn.org%2Fproxy.pac%20%5D.%22%2C%22wrapped%22%3A%7B%22message%22%3A%22%D0%A7%D1%82%D0%BE-%D1%82%D0%BE%20%D0%BD%D0%B5%20%D1%82%D0%B0%D0%BA%20%D1%81%20%D1%81%D0%B5%D1%82%D1%8C%D1%8E%2C%20%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D1%8C%D1%82%D0%B5%20%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5.%22%2C%22wrapped%22%3A%7B%22stack%22%3A%22TypeError%3A%20Failed%20to%20fetch%5Cn%20%20%20%20at%20Object.get%20(chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F13-http-lib.js%3A45%3A7)%5Cn%20%20%20%20at%20chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F37-sync-pac-script-with-pac-provider-api.js%3A221%3A44%5Cn%20%20%20%20at%20new%20Promise%20(%3Canonymous%3E)%5Cn%20%20%20%20at%20chrome-extension%3A%2F%2Fnpgcnondjocldhldegnakemclmfkngch%2F37-sync-pac-script-with-pac-provider-api.js%3A220%3A19%22%2C%22message%22%3A%22Failed%20to%20fetch%22%2C%22name%22%3A%22TypeError%22%7D%7D%7D%7D&type=pup-ext-err&version=0.0.1.63&useragent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F126.0.0.0%20Safari%2F537.36&platform=Win32

**Comment by D1zg** [comment]
ап

**Comment by ilyaigpetrov** [comment]
@D1zg,  https://github.com/anticensority/runet-censorship-bypass/wiki/Как-прочитать-логи%3F-%28для-продвинутых%29.
