### ISSUE TITLE
Антифишинг

### ISSUE THREAD

**Issue by MarisKori** [anticensority/runet-censorship-bypass#41]
Предлагаю добавить в расширение предупреждение о фишинговых сайтах, которые игнорируют практически все средства (антивирусы, днсы яндекса, гугла и прочие).

Это, прежде всего, левые зеркала rutracker.org и rutor.info - их очень много. И в силу того, что оригинальные сайты вообще не показываются в выдаче, ни на первом, ни на последнем месте, то зеркала часто посещают. Причём, они зачастую даже не заблокированы РКН.

По сути это должен быть небольшой список левых зеркал из первых страниц выдачи гугла и яндекса. Всё.

В идеале, конечно, можно сделать ещё и перенаправление на оригинальный сайт. Делается это легко. Я бы сделал так: в настройках две галочки: 1) предупреждать о фишинговых торрент-трекерах (включена по умолчанию) 2) перенаправлять на оригинальные сайты (выключена по умолчанию).

**Comment by ilyaigpetrov** [comment]
Думаю, это идея для отдельного расширения.  
Будет постоянно сидеть в памяти и есть дополнительные мегабайт 30.  

> Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".
[Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)

**Comment by ilyaigpetrov** [comment]
Найдите заинтересованного разработчика и дерзайте, идею можно абстрагировать или нарочно оставить упрощённой.
