### ISSUE TITLE
В Windows 10 слетает переключатель "Использовать сценарий настройки"

### ISSUE THREAD

**Issue by baursak** [anticensority/runet-censorship-bypass#42]
После переустановки Windows 10 (повторилось уже на 2-х разных компьютерах) через 2-3 недели слутает переключатель Пуск - Параметры - Сеть и Интернет - Прокси-сервер - Автоматическая настройка прокси-сервера - Использовать сценарий настройки.
Снова его включаю, забиваю туда адрес https://antizapret.prostovpn.org/proxy.pac и сохраняюсь
Проходит минут 10-15 - в уже открытом браузере перестают открываться ресурсы, запрещенные РКН
Попробовал в Авасте прописать этот URL как исключение в разделе Меню - Настройки - Компоненты - Веб защита - Настройки - Исключения сценариев - никакого эффекта.
Что это может быть?
В период с момента работы скрипта и отказа работы скрипта я вижу, автообновлялись такие программные компоненты: Голосовой помощник Алиса (от Яндекса), Old calculator for Windows 10. - Обновления виндовые никакие в этот период не ставились

**Comment by ValdikSS** [comment]
Это баг-трекер расширения «обход блокировок Рунета». Возможно, какая-то сторонняя программа периодически изменяет настройки прокси-сервера. Попробуйте поискать в интернете или обратиться в поддержку Microsoft.
