### ISSUE TITLE
Android, не работает Маркет, ВК

### ISSUE THREAD

**Issue by andrewalexeich** [anticensority/runet-censorship-bypass#43]
Здравствуйте! Не работает Маркет и ВК (не загружает медиа) на Андроиде, если прописывать в настройках WiFi .pac-скрипт. Спасибо!

**Comment by ValdikSS** [comment]
Это баг-трекер расширения «обход блокировок Рунета». В Android поддержка PAC-файлов забагована, что приводит к подобному поведению. Используйте способ с VPN.
