### ISSUE TITLE
[FIXED] Открываем .onion через Тор

### ISSUE THREAD

**Issue by sergeevabc** [anticensority/runet-censorship-bypass#44]
Подключил Антицензорити.PAC в Firefox при включённом Торе (```SOCKS5 127.0.0.1:9050```).
Обычные блокированные адреса открываются, а ```*.onion``` адреса почему-то нет.
Пробовал ```network.proxy.socks_remote_dns = true``` и ```network.dns.blockDotOnion = false``` — не помогло.
А вот беру Антизапретовский PAC и допиливаю его следующим образом:
```
...
function FindProxyForURL(url, host) {

  if (dnsDomainIs(host, ".onion")) {return "SOCKS5 127.0.0.1:9050;";}
...
```
то ```*.onion``` начинают открываться. В поисках решения попробовал допилить так же Антицензорити PAC, но луковые адреса по-прежнему не открываются. Что посоветуете?

**Comment by ilyaigpetrov** [comment]
Добавил проксирование всех `*.onion` сайтов в Антицензорити.
Далее `network.proxy.socks_remote_dns = true` и `network.dns.blockDotOnion = false`.
Стал открываться http://www.flibustahezeous3.onion, но не другие сайты.

**Comment by ilyaigpetrov** [comment]
У вас что-то изменилось после добавления `*.onion` в проксируемые? Работает ли http://www.flibustahezeous3.onion и другие сайты? В какой-то момент у меня перестала работать и флибуста.

**Comment by ilyaigpetrov** [comment]
Решено с помощью добавления отдельной проверки .onion в PAC-скрипте "Антицензорити": https://github.com/anticensority/pac-script-generator/blob/production/src/generator.js#L368-L370:
```js
    if (host.endsWith('.onion')) {
      return true;
    }
```

**Comment by sergeevabc** [comment]
Заработало, спасибо.

P.S. Подскажите, а замена фрагмента ```SOCKKS5 localhost:9150; SOCKS5 localhost:9050;``` на ```SOCKS5 127.0.0.1:9050;``` позволяет выиграть несколько миллисекунд, верно?

**Comment by ilyaigpetrov** [comment]
Не эксперт по внутренностям ОС, но если в ОС не используется захаркоденные значения для localhost, то да, при каждом разрешении имени происходит обращение к файлу на жёстком диске, который для производительности постоянно загружен в область оперативной памяти, т.е. при каждом разрешении адреса вы тратите одно обращение к RAM. Как-то так, думаю. Спасибо за идею использовать IP вместо имени.

**Comment by sergeevabc** [comment]
Через несколько дней понял, что ваше предложение по ```*.onion``` это не совсем то. Сейчас идёт бинарная проверка: либо завернуть запрос на проксю, либо пропустить (direct). Хочется гибче: заблокированные сайты на _быструю_ проксю (например, на свой socks5), onion на _очевидно медленную_ тор-проксю (тот самый 127.0.0.1:9050), остальное пропустить (direct). Поможете?

P.S. Допиленный описанным образом Антизапрет [выглядит так][1], а с Антицензорити сложнее…

[1]: https://linx.li/selif/ytqnflur.pac

**Comment by ilyaigpetrov** [comment]
Если `PROXY_STRING` потом заменяется на быстрый прокси, то можно примерно так:
```js
function FindProxyForURL(url, host) {

  let ifByHost = false;
  let ifByMaskedIp = false;
  // Remove last dot.
  if (host[host.length - 1] === '.') {
    host = host.substring(0, host.length - 1);
  }

  return
    host.endsWith('.onion')
    ? 'SOCKS5 localhost:9150; SOCKS5 localhost:9050; DIRECT'
    : (
        (function isCensored(){

          ifByHost = areSubsCensored(host);
          if (ifByHost) {
            return true;
          }

          const ip = dnsResolve(host);
          if (ip) {
            if (ifFoundByBinaryInString(ips[ip.length] || '', ip)) {
              return true;
            }
            ifByMaskedIp = isCensoredByMaskedIp(ip);
            if (ifByMaskedIp) {
              return true;
            };
          }

          return false;

        })() ? PROXY_STRING : 'DIRECT'
    );
}
```
К сожалению у меня в ближайший месяц почти нет возможности работать над скриптом, нет времени внести изменения и тщательно их протестировать, потому я просто оставлю вам данный кусок кода в качестве возможного решения. Если вы оставите комментарий, то, возможно, я смогу ответить. Сообщите, подходит ли вам приведённое решение.

**Comment by sergeevabc** [comment]
Надо поднять ```host.endsWith('.onion')``` на уровень ```return```, тогда работает. Спасибо!

**Comment by ilyaigpetrov** [comment]
Я поднял `host.endsWith('.onion')` на уровень `return` в PAC-скрипте "Антицензорити".

**Comment by sergeevabc** [comment]
Вместо `host.endsWith (".onion")` уместнее использовать `dnsDomainIs (host, ".onion")`, [ибо][1]…

![2]

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#Browser_compatibility
[2]: https://i6.imageban.ru/out/2019/04/12/358fde5424483034eb2d1bc8c8af4e09.png

**Comment by ilyaigpetrov** [comment]
Да, исправил.
Только я старый IE не хотел поддерживать, т.к. он плохо кеширует PAC-скрипт.
Я даже добавил особую строчку, но возможно, что она не срабатывает для старых IE:
```js
if (/*@cc_on!@*/!1) {
  throw new TypeError('https://rebrand.ly/ac-anticensority');
}
```

**Comment by sergeevabc** [comment]
Решил попробовать ваше расширение для Firefox, чтобы
* открывать заблокированные ресурсы через Antizapret
* открывать .onion через локальный Tor на 9050 порту

Однако, как ни настраиваю расширение, второй пункт не работает.

**Comment by ilyaigpetrov** [comment]
1. Иконка синей ленты -> свои прокси -> Использовать свой локальный Тор.
2. Иконка синей ленты -> свои прокси -> Проксировать .onion.

Обе галочки стоят? Тор установлен и запущен (браузер или консольное приложение)?
![firefox-onion](https://user-images.githubusercontent.com/1090811/111068530-073e2580-84c1-11eb-88a5-8dfc6c4e1b05.png)

**Comment by ilyaigpetrov** [comment]
https://rebrand.ly/ac-tor:
> Тор-браузер использует порт 9150, просто Тор использует порт 9050.

**Comment by sergeevabc** [comment]
![](https://i3.imageban.ru/out/2021/03/14/316ea064fd368b6bdb9808e7d6cb71e4.png) ![](https://i3.imageban.ru/out/2021/03/14/dfaec51a7411422d8ef4c0728d18bba3.png)

![](https://i5.imageban.ru/out/2021/03/14/d71c8fb7198c1cd6a7da3965ee29e87d.png) **либо** ![](https://i4.imageban.ru/out/2021/03/14/3672b41bbd07870cbe210f9fc5c21610.png)

```
Mar 14 17:24:19.954 [notice] Tor 0.4.5.2-alpha (git-135b8eea36edd992) running on Windows 7
Mar 14 17:24:35.577 [notice] Opening Socks listener on 127.0.0.1:9050
Mar 14 17:24:40.000 [notice] Bootstrapped 100% (done): Done
```

Другие расширения для выборочного проксирования типа MM3-ProxySwitch или SmartProxy работают.
Либо опять же скачиваю antizapret.pac, добавляю [строчку][1], прописываю путь в настройки прокси Fireefox — работает.

[1]: https://github.com/anticensority/runet-censorship-bypass/issues/44#issue-388934481

**Comment by ilyaigpetrov** [comment]
Проверьте логи расширения и логи браузера (Browser Console) -- есть ли там
какие-либо ошибки?
Попробуйте поставить ещё один фаерфокс (бету или nightly) и проверить на
чистом браузере.

**Comment by ilyaigpetrov** [comment]
Включите все 3 типа уведомлений.
Можно посмотреть на код модифицированного PAC-скрипта: иконка синей ленты -> Проблемы? -> Отладка PAC-скрипта -> READ.
