### ISSUE TITLE
Расширение для Firefox

### ISSUE THREAD

**Issue by rakleed** [anticensority/runet-censorship-bypass#45]
Сделайте, пожалуйста, расширение для браузера Firefox.

**Comment by ilyaigpetrov** [comment]
https://github.com/anticensority/runet-censorship-bypass/issues/18#issuecomment-445739472

Либо делать отдельное расширение, которое идёт со встроенным генератором (напрягает процессор раз в несколько часов), либо автоматически публиковать новое расширение каждые N часов. Оба варианта требуют времени и не выглядят как оптимальное решение.

Чем вам не нравится установка PAC-скрипта через настройки FireFox?

**Comment by rakleed** [comment]
Просто расширение упрощает некоторые моменты: например, при переустановке браузера не надо устанавливать PAC-скрипт, т. к. расширение бы автоматически установилось после входа в аккаунт Firefox, также можно легко отключить для определённого сайта или вообще отключить прокси, если есть с ним какие-то проблемы.

**Comment by ilyaigpetrov** [comment]
Билет закрывается как дубликат https://github.com/anticensority/runet-censorship-bypass/issues/18.
