### ISSUE TITLE
Как мне проксировать .onion и .i2p но не opennic?

### ISSUE THREAD

**Issue by kotenok2000** [anticensority/runet-censorship-bypass#46]

**Comment by ilyaigpetrov** [comment]
Отдельные домены можно попробовать добавить на вкладке "исключения", но функции отключения всех TLD-ов OpenNIC разом не предусмотрено. Как сильно это вам мешает? В любом случае было бы полезно добавить такую функцию, спасибо за предложение.

**Comment by ilyaigpetrov** [comment]
Пожалуйста, опишите почему эта функция вам нужна: я слабо себе представляю сценарий, в котором OpenNIC домены как-либо мешают работе.
