### ISSUE TITLE
Новый Chrome не позволяет использовать `--proxy-pac-url='file://` (локальный PAC-скрипт из файловой системы)

### ISSUE THREAD

**Issue by ghost** [anticensority/runet-censorship-bypass#47]
Здравствуйте!
Для обхода заблокированных сайтов использую pac-файл, который лежит в документах. Путь к нему указал через свойства браузера. В самом pac-файле всего несколько адресов. Пользовался таким решением очень долго. В Chrome 72 перестало работать такое решение. Chrome прокси вообще не видит. Однако если указан https-адрес, все нормально. Полагаю это из-за изменений https://bugs.chromium.org/p/chromium/issues/detail?id=912553
Есть еще способы указать свой pac-файл?

**Comment by ilyaigpetrov** [comment]
Благодарю за интересную новость.
> Disables support by default for PAC script file URLs when network
service is enabled. This is in preparation for sandboxing the network
service which won't have access to the file system anymore.
Eventually we'll disable it without the network service.

https://bugs.chromium.org/p/chromium/issues/detail?id=839566

Там же обсуждаются и временные способы обхода ограничения.
Я думаю, что наиболее удобно будет использовать расширение, которое позволяет скопипастить PAC-скрипт в себя и установить его в браузере. Ведь, насколько я понял, вы не часто меняете содержимое PAC-скрипта.

Я не в курсе какое расширение позволяет такое, но можете проверить SwitchyOmega или https://chrome.google.com/webstore/detail/proxy-switcher-and-manage/onnfghpihccifgojkpnnncpagjcdbjod. Сам никогда не пользовался.

**Comment by ghost** [comment]
Спасибо за правильный issue, там точная информация. Буду изучать. Хотя пока закинул свой pac в сеть и указал путь к нему.
