### ISSUE TITLE
Перестал работать PAC-скрипт «Антицензорити» в Хроме до v73

### ISSUE THREAD

**Issue by kotenok2000** [anticensority/runet-censorship-bypass#48]
Я использую скрипт anticenzority с локальным tor. 
Сайты перестали блокироваться.
Через скрипт antizapret всё работает.

**Comment by ilyaigpetrov** [comment]
У меня работает, только почему-то перестал работать индикатор проксирования на синей ленте.

1) Как вы используете PAC-скрипт: через расширение для Хрома, через флаг для Хрома или через настройки FireFox?
2) Убедитесь, что не разблокируются все сайты, а не какие-то отдельные. http://kasparov.ru и http://grani.ru, к примеру, работают?
3) Перенаправление с адреса сайта на провайдерскую страницу может закешироваться в браузере. Попробуйте так: https://stackoverflow.com/a/27175511/521957.
4) Перезапустите службу Тора на всякий случай.
5) Какая у вас версия браузера (если используется Хром)?

**Comment by Scaryman** [comment]
У меня тоже перестал работать скрипт антицензорити. Использовал его вместе со своим прокси сервером. Скрипт использовал через расширения хрома.
Произошло это после обновления хрома до версии 72.
Теперь при переходе на заблокированные сайты выдается ошибка ERR_CONNECTION_RESET

**Comment by ilyaigpetrov** [comment]
6. Включите в расширении уведомления, все три галочки. Если поймаете ошибку, пришлите её сюда.
7. Загляните в логи: https://rebrand.ly/ac-logs. Если есть что-то подозрительное (ошибки), то присылайте.
8. Будет интересно узнать, на какой ОС у вас перестал работать "Антицензорити".
9. Попробуйте установить PAC-скрипт в [настройках FireFox](https://github.com/anticensority/runet-censorship-bypass/wiki/PAC-скрипт-«Антицензорити»-для-FireFox-и-Chrome#firefox) -- будет ли он так работать.

**Comment by Scaryman** [comment]
Все 3 галочки не дают ни каких ошибок.
В логах вроде ничего криминального нет: https://prntscr.com/mlutve
Перестало работать как на macOS так и на Windows 10. Перестает работать именно после обновления на версию хрома 72.
Ошибки выдает разные, видимо от провайдера зависит. Например Онлайм выдает ошибку ERR_CONNECTION_RESET, Билайн выдает ERR_CONNECTION_CLOSED, на работе выдает ERR_SSL_PROTOCOL_ERROR

**Comment by ilyaigpetrov** [comment]
Пришлите мне точные версии ваших браузеров (Хром). Версию можно узнать на chrome://settings/help

**Comment by ilyaigpetrov** [comment]
Ну и версии ОС на всякий случай ещё.

**Comment by ilyaigpetrov** [comment]
Создал билет в багтрекере Хрома. Подписаться на него можно, поставив звёздочку здесь:
https://bugs.chromium.org/p/chromium/issues/detail?id=932907
Там же можно оставить комментарий, указав в какой версии Хрома у вас проявляется эта ошибка (если об этой версии никто другой не докладывал, я доложил о версиях 73 и 74 под Линукс, в 72 у меня этой проблемы нет).

**Comment by ilyaigpetrov** [comment]
Пока что я не склонен к тому, чтобы прибегать к сжатию PAC-скрипта "Антицензорити", т.к. это замедлит его работу в том числе и под FireFox, в котором всё прекрасно работает и без сжатия.
Можно было бы начать распространять выпуск "Антицензорити" специально под Хром, но это требует работы ~и всё по причине того, что в Google решили выпилить с рынка блокировщики рекламы~ (похоже, что я ошибался в этом предположении).

**Comment by Scaryman** [comment]
Т.е. решения проблемы не будет?

**Comment by Trof72** [comment]
Привет други!
Подскажите как найти это же приложение под Firefox/ что не могу не как !!! пока вопрос решается на хроме!!! Заранее благодарен

**Comment by AfterDeath-2525** [comment]
Сначала перестал работать антицензорити несколько дней назад, сегодня перестал работать и антизапрет тоже, при чём ещё несколько часов назад всё работало, а щас не зайти уже ни на nnmclub.to, ни на rutracker.org
браузер Google Chrome
Версия 72.0.3626.109 (Официальная сборка), (64 бит)
служба Tor Win32 Service работает

**Comment by ilyaigpetrov** [comment]
> Т.е. решения проблемы не будет?

Нужно посмотреть на реакцию разработчиков Хрома -- станут ли они это исправлять. Если не станут, то я подумаю.

> Сначала перестал работать антицензорити несколько дней назад, сегодня перестал работать и антизапрет тоже...

Да, мы в курсе, я написал об этом в новостях: https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-465207396

**Comment by ilyaigpetrov** [comment]
> и всё по причине того, что в Google решили выпилить с рынка блокировщики рекламы.

Похоже, что я ошибался в этом предположении и ограничение не связано с блокировщиками рекламы, по крайней мере не прямо. Приношу извинения за недостоверную информацию.

Также сообщаю, что если разработчики исправят ошибку, то придётся подождать, пока исправление не будет опубликовано в стабильной версии Хрома. В худшем случае это около месяца, но может быть и более оперативно.

**Comment by ilyaigpetrov** [comment]
Разработчики Хрома считают, что ошибка появилась в версии 73.
Если у вас не работает "Антицензорити" в расширении на Хроме версии 72, то помогите нам в следующем:

1) Скачайте и распакуйте расширение из [этого сообщения](https://bugs.chromium.org/p/chromium/issues/detail?id=932907#c7) (test-ext.zip).
2) Установите расширение в вашем Хроме версии 72 (chrome://extensions -> режим разработчика -> загрузить распакованное расширение). После загрузки в текущей вкладке браузера должен открыться сайт google.com/ncr. Если он не открывается (возникает ошибка `ERR_PROXY_CONNECTION_FAILED`), то установленное расширение работает корректно и у вас не работает "Антицензорити" по каким-то другим причинам, не по причине обсуждаемой в билете проблемы.
3) Сообщите нам точную версию Хрома, вашей ОС (ищите на chrome://version) и результат шага 2 (открывается ли google.com/ncr без ошибок или с ошибкой и какой). Если вы продвинутый пользователь, то можете сообщить о воспроизведении проблемы (т.е. google.com/ncr открывается без ошибок) на 72ой версии в приведённый выше билет багтрекера Хрома.

**Comment by Scaryman** [comment]
Версия 72.0.3626.109 (Официальная сборка), (64 бит)
macOS Mojave 10.14.3
после включения плагина страница google.com/ncr открывается без ошибок и перекидывает на www.google.com

Версия 72.0.3626.109 (Официальная сборка), (64 бит)
Windows 10 Домашняя для одного пользователя, версия 1803, сборка 17134.590
после включения плагина страница google.com/ncr открывается без ошибок и перекидывает на www.google.com

Версия 72.0.3626.109 (Официальная сборка), (64 бит)
Windows 10 Pro, версия 1809, сборка 17763.316
после включения плагина страница google.com/ncr открывается без ошибок и перекидывает на www.google.com

**Comment by AfterDeath-2525** [comment]
Версия 72.0.3626.109 (Официальная сборка), (64 бит)
Windows 7 Home Premium  
после включения плагина открывается страница google.com без ошибок

**Comment by ilyaigpetrov** [comment]
Попробуйте отключить этот флаг и сообщите, помогло ли и в какой версии Хрома и на какой ОС: chrome://flags/#network-service

**Comment by AfterDeath-2525** [comment]
после отключения chrome://flags/#network-service Антицензорити вновь работает! 
Версия 72.0.3626.109 (Официальная сборка), (64 бит)
Windows 7 Home Premium (SP1)

**Comment by Scaryman** [comment]
> Попробуйте отключить этот флаг и сообщите, помогло ли и в какой версии Хрома и на какой ОС: chrome://flags/#network-service

После отключения флага все заработало.

**Comment by krutena** [comment]
Chrome version: 72.0.3626.**119** (Official Build) (64-bit),
Edition: Windows 10 Pro, Version: 1809, OS build 17763.316

Antizapret работает. Открывает: nnmclub.to, rutracker.org, flibusta.is
Антицензорити не работает. Установил расширение test-ext - открылся google.com без ошибок.
Отключение флага не помогло. 

*У меня хром последнее обновление подтянул только что. Работает только Antizapret.

**Comment by ilyaigpetrov** [comment]
@krutena, обновился и протестировал на 72.0.3626.119 -- работает. Флаг мог сброситься после обновления -- убедитесь, что он всё ещё отключен. Не забудьте перезапустить Хром после изменения флага. И если test-ext всё ещё открывает страницу гугла, напишите в билет багтрекера самостоятельно, чтобы мне не быть между вами переводчиком. Как-нибудь так:

> I was able to reproduce the issue with test-ext.zip from #7 on:
Chrome version: 72.0.3626.119 (Official Build) (64-bit),
Edition: Windows 10 Pro, Version: 1809, OS build 17763.316
Disabling chrome://flags/#network-service doesn't help.
Is there anything I can do with it?
>
> Thanks.

**Comment by ilyaigpetrov** [comment]
Если кто-то ещё не видел сообщения в билете:
1) Исправление планируется доставить в 73ей стабильной версии где-то 12 марта.
2) Протестировать можно в Хром 74.0.3714.0, который сейчас только в Canary версии, скоро и в dev.

**Comment by sergeevabc** [comment]
@ilyaigpetrov, по соседству [выпиливают][1] загрузку PAC с локального диска по аналогии с Internet Explorer 11 и Edge. Из-за этого на 72-м Хроме ключ ```--proxy-pac-url="file:///C:/anticensority.pac"``` уже не работает сам по себе, требуется прописывать дополнительный ключ ```--disable-features=NetworkService``` или устанавливать расширение. Примечательно, что на Хромиуме 73 и 74 это изменение (временно?) откатили (но тему ещё не закрыли, что тревожит).  

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=839566

**Comment by ilyaigpetrov** [comment]
Только что обновился до стабильной версии 73, включил флаг chrome://flags/#network-service обратно и перезапустил -- PAC-скрипт "Антицензорити" снова работает. Если после обновления до 73 у вас не работает с включенным флагом -- пришлите точную версию Хрома, ОС, положение флага (enabled, disabled, default) и другие важные детали. Билет будет закрыт, если у всех всё работает.

**Comment by BuIlDaLiBlE** [comment]
У меня сразу же после апдейта до 73 пару недель назад перестал работать этот PAC. Пытался и с включенным флагом, и с дефолтным, и с выключенным - без толку.
Билд Chrome: 73.0.3683.86
OS: Windows 10 64-bit 1809 (Build 17763.379)
Также проверил на macOS Mojave 10.14.3 (18D109) - такой же результат.

**Comment by ilyaigpetrov** [comment]
@BuIlDaLiBlE, давайте убедимся в тривиальных вещах:
1. "Антицензорити" требует запущенного Тора (браузера или службы) -- убедитесь, что Тор работает, а системное время выставлено правильно. Либо у вас должны быть настроены свои рабочие прокси -- проверьте тогда их.
2. В Хроме PAC-скрипт работает только через наше расширение, другие способы (через флаг исполняемого файла) имеют ограничения (на размер файла в 1MB, на `file:///`), с которыми придётся как-то "шаманить". Сообщите, если вы __не__ используете расширение.
3. Тестировать следует после обновления PAC-скрипта в расширении и на __нескольких__ сайтах, которые более менее распространены (http://kasparov.ru, http://grani.ru).
4. Включите все уведомления в расширении и сообщите о возникающих сообщениях, если они есть.

Сообщите, как именно не работает PAC-скрипт -- вылазит ли "заглушка" провайдера или другая ошибка (какая? Скриншот будет полезен, если неясно на чьей стороне ошибка).

После проверки простых вещей, проверьте работу тестового расширения по шагам из https://github.com/anticensority/runet-censorship-bypass/issues/48#issuecomment-465987833 выше. Если тестовое расширение работает корректно (гугл-нкр блокируется и не грузится), то загляните в [логи расширения](http://rebrand.ly/ac-logs). Если там ничего подозрительного нет, и вы немного разбираетесь в JavaScript, то можно открыть PAC-отладчик (`иконка синей ленты -> Проблемы? -> отладка PAC-скрипта -> load`) и навставлять проброску исключений с информативными сообщениями в нужные места.

**Comment by BuIlDaLiBlE** [comment]
> @BuIlDaLiBlE, давайте убедимся в тривиальных вещах:
> 
> 1. "Антицензорити" требует запущенного Тора (браузера или службы) -- убедитесь, что Тор работает, а системное время выставлено правильно. Либо у вас должны быть настроены свои рабочие прокси -- проверьте тогда их.

Действительно, после запуска Тора всё работает. Но ведь до этого работало и без него, даже после изменений про "свои прокси". Значит косяк с самим браузером Chrome?

**Comment by ilyaigpetrov** [comment]
@BuIlDaLiBlE, вы второй пользователь, который заявляет, что у него "Антицензорити" работал до этого без Тора и своих прокси. Уже год, как этот PAC-скрипт перешёл со встроенных прокси на Тор, и я не понимаю, как такое возможно. Может быть, служба тора была установлена в систему ранее и о ней просто забыли до того, как она сломалась. Или расширение перестало обновляться из-за ошибки, и использовался очень старый PAC-скрипт. Или расширение, как и задумывалось, переключилось с "Антицензорити" на "Антизпрет" у всех пользователей с настойками по умолчанию, и вы этого не замечали целый год.

По поводу настройки Тора для расширения будет полезна эта статья: https://git.io/ac-tor.

**Comment by BuIlDaLiBlE** [comment]
Буквально час назад запустил компьютер с macOS и версией Chrome 72 - там действительно стоял "Антизапрет", даже после переключения на "Антицензорити" всё работало просто так, но как только я обновил до 73 - перестало работать. Не знаю с чем это связано.
А по Вашему мнению, какой PAC лучше использовать? "Антизапрет" лично мне кажется быстрее (во всяком случае Тор конечно же куда медленнее).

**Comment by ilyaigpetrov** [comment]
@BuIlDaLiBlE я не замечаю особой разницы в скорости до тех пор, пока не наткнусь на что-нибудь тяжёлое. Тут зависит от вашего доверия своих данных прокси-серверам https://antizapret.prostovpn.org или узлам Тора (для которых как бы должно быть сложнее ассоциировать ваши незашифрованные http-пакеты и ваш IP). Также "Антицензорити" лучше, если вы хотите проксировать свои сайты, или если провайдер блочит доисторическими методами по IP-адресу сайта.

**Comment by sergeevabc** [comment]
Сейчас прописал Антицензорити в разных браузерах, не ставя официальное расширение, и попробовал открыть пару заблокированных ресурсов. Справились: FF 63 и Palemoon 28. Сдались: Chrome 70+ (через флаг или прокси-расширение TunnelSwitch), Opera (через расширение SimpleProxy), Kmeleon 76 и IE11. Тут стоит похвалить Антизапрет за поиски всё лучшего сжатия списка заблокированных ресурсов, что позволяет удерживать PAC в рамках 1 Мб и работать с ним из любого современного браузера.

**Comment by ilyaigpetrov** [comment]
@sergeevabc, я не хочу делать из "Антицензорити" клон "Антизапрета", лучше когда есть разнообразие в выборе с учётом недостатков и достоинств одного перед другим. Сжатие имеет свою цену: "Антизапрет" проксирует меньше IP и меньше доменов, расжатие структур данных влияет на производительность, выше сложность кода, вероятность его поломки и стоимость поддержки. Поддержка старых браузеров мне мало интересна, а в других расширениях (TunnelSwitch, SimpleProxy) не работать может из-за ограничений на размер в способе установки PAC через URL или из-за обсуждаемого в этом билете бага.

**Comment by Neografic** [comment]
Здравствуйте. Перестал открываться сайт http://seasonvar.ru/ все остальные сайты открываются.

**Comment by ilyaigpetrov** [comment]
@Neografic, прошу не писать сообщения, не относящиеся к заявленной в билете теме. Ваше сообщение получают все участники обсуждения данного билета, и они могут быть не заинтересованы в работоспособности seasonvar. Либо создайте новый билет на GitHub, но предпочтительно -- в Google-группе https://rebrand.ly/ac-contact. Спасибо. Мы уже получили сообщения от пользователей о проблемах seasonvar, автор PAC-скрипта "Антизапрет" проинформирован. Для получения более подробной информации в дальнейшем -- создайте публичное обсуждение в Google-группе.

**Comment by Neografic** [comment]
> @Neografic, прошу не писать сообщения, не относящиеся к заявленной в билете теме. Ваше сообщение получают все участники обсуждения данного билета, и они могут быть не заинтересованы в работоспособности seasonvar. Либо создайте новый билет на GitHub, но предпочтительно -- в Google-группе https://rebrand.ly/ac-contact. Спасибо. Мы уже получили сообщения от пользователей о проблемах seasonvar, автор PAC-скрипта "Антизапрет" проинформирован. Для получения более подробной информации в дальнейшем -- создайте публичное обсуждение в Google-группе.

Хорошо. Спасибо.

**Comment by sergeevabc** [comment]
> Для получения информации в дальнейшем -- создайте публичное обсуждение в Google-группе.

@ilyaigpetrov, выступать против наблюдения и цензуры, но при этом подталкивать людей в сторону Google это, мягко говоря, странно. Рассмотрите возможность общаться на менее замаравшихся площадках. Ведь есть аналоги вроде Spectrum.chat ([пример][1]), Zulipchat.com ([пример][2]), Groups.io ([пример][3]), Agorakit.org ([пример][4]), есть чато-подобные Discordapp.com и Gitter.im или даже reddit-подобный Deza.to ([пример][5]).

[1]: https://spectrum.chat/codepen?tab=posts
[2]: https://invidiou.sh/watch?v=TuHN8CLocE8
[3]: https://groups.io/g/UK-Rail
[4]: https://app.agorakit.org/groups/526
[5]: https://deza.to/x/announcements/hot

**Comment by ilyaigpetrov** [comment]
@sergeevabc:
1) Насколько мне известно, создать обсуждение в Googe-группе можно, не имея Google-аккаунта, -- достаточно просто написать на anticensority@googlegroups.com (но сам не тестировал).
2) Речь идёт о публичном обсуждении, email-адрес отправителя обрезается для приватности как [здесь](https://groups.google.com/forum/#!topic/anticensority/QZwhEfxuqVo). Потому вопрос наблюдения, думаю, отпадает. Когда-то давно можно было также зарегистрироваться в Google со своим почтовым адресом для использования их сервисов -- в этом случае вместо обрезанного почтового адреса можно использовать псевдоним, уникальный то ли для групп, то ли для отдельной группы.
3) О цензуре. Если не исползьовать какие-нибудь крипто-анархические платформы, то неизбежно приходится кому-то доверять, будь это Google или spectrum.chat. Напишите, пожалуйста, мне на [почту](https://github.com/ilyaigpetrov) аргементы против Google, но в пользу, к примеру, spectrum.chat. Или можно создать отдельный билет в этом репозитории «Аргументы против использования Google-группы».

Спасибо за вашу конструктивную критику и предложенные альтернативы. Жаль, что не все на русском языке. Я обязательно протестирую хотя бы sptctrum.chat. Gitter-комнуту когда-то создавали, как и irc-комнату на Freenode, но посетителей не было, несмотря на упоминение в подвале wiki данного репозитория.
