### ISSUE TITLE
Безопасен ли FriGate?

### ISSUE THREAD

**Issue by qTorrent** [anticensority/runet-censorship-bypass#49]
Здравствуйте!

Заранее извиняюсь, если вопрос неуместный. В Wiki у вас есть страница под названием: [**Альтернативы нашему расширению**](https://github.com/anticensority/runet-censorship-bypass/wiki/Альтернативы-нашему-расширению). Там приведён список альтернатив, но в нём нет расширения [**friGate CDN**](https://chrome.google.com/webstore/detail/frigate-cdn-smooth-access/mbacbcfdfaapbcnlnbmciiaakomhkbkb). Учитывая, что расширение довольно популярное, автор расширения [**Обход блокировок Рунета**](https://chrome.google.com/webstore/detail/обход-блокировок-рунета/npgcnondjocldhldegnakemclmfkngch) наверняка о нём слышал.

Что-то подумалось, что **friGate CDN** нет в списке альтернатив неспроста... Подозрения усиливаются из-за абсолютного игнорирования любых вопросов саппортом расширения.

1. Может **friGate CDN** вредоносное или опасное расширение, а я не в курсе? Этим объясняется отсутствие данного расширения в списке альтернатив?

2. И ещё, некоторые сайты из списка Антизапрет у меня открываются и без прокси. Умеет ли расширение **Обход блокировок Рунета** само определять нужно ли проксировать сайт, или оно проксирует все сайты из списка вне зависимости от их доступности.

**Comment by ilyaigpetrov** [comment]
1. Расширения friGate нет в списке, так как я сам его не тестировал и не изучал его код.  
Из опасных альтернатив -- постарайтесь избегать fastProxy и realProxy, т.к. они разрешают функцию `eval`, благодаря которой можно в браузере исполнять произвольный код, приходящий с сервера и заранее неизвестный (и потому заранее не проверенный на вирусы).
2. Расширение не умеет само определять нужно ли проксировать сайт. Можно исключать сайты, которые ваш провайдер не блокирует, из списка проскируемых (`иконка синей ленты -> исключения -> вписать адрес` и выбрать "нет", т.е. не проксировать). Если важных для вас сайтов совсем немного, то можно попробовать выбрать в PAC-скриптах "Только свои сайты и свои прокси", а на вкладке "Исключения" воспользоваться режимом импорта/экспорта (иконка со стрелками в разные стороны), но это для продвинутых пользователей, т.к. сайт может использовать много доменов, и их все придётся путём проб и ошибок узнавать.

**Comment by qTorrent** [comment]
Спасибо за ответы!
> 1. Из опасных альтернатив -- постарайтесь избегать fastProxy и realProxy, т.к. они разрешают функцию `eval`, благодаря которой можно в браузере исполнять произвольный код, приходящий с сервера и заранее неизвестный (и потому заранее не проверенный на вирусы).

А **friGate CDN** не разрешает функцию `eval`? Или надо расширение ковырять, чтобы узнать наверняка?

У **friGate** есть два функционально одинаковых расширения  [**friGate CDN**](https://chrome.google.com/webstore/detail/frigate-cdn-smooth-access/mbacbcfdfaapbcnlnbmciiaakomhkbkb) и  [**friGate Lite**](https://chrome.google.com/webstore/detail/frigate-light/mdnmhbnbebabimcjggckeoibchhckemm). Внешне отличаются только иконками, а в остальном — абсолютно однотипные. При этом **Lite-версия** весит вдвое больше и при запуске сильнее грузит процессор. Все попытки узнать чем отличаются расширения игнорируются саппортом, в сети информации об этом ноль. Может вам что-то известно про отличия этих расширений (а вдруг 😃)?

> 2. Если важных для вас сайтов совсем немного, то можно попробовать выбрать в PAC-скриптах "Только свои сайты и свои прокси", а на вкладке "Исключения" воспользоваться режимом импорта/экспорта (иконка со стрелками в разные стороны), но это для продвинутых пользователей, т.к. сайт может использовать много доменов, и их все придётся путём проб и ошибок узнавать.

Если я пропишу свой прокси в расширение, то он будет использоваться для всех сайтов из списка Антизапрет, или только для сайтов, которые я добавил вручную?

**Comment by ilyaigpetrov** [comment]
#### [FriGate CDN](https://chrome.google.com/webstore/detail/frigate-cdn-smooth-access/mbacbcfdfaapbcnlnbmciiaakomhkbkb)
Манифест содержит строчку:
```
"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",
```
`unsafe-eval` разрешает расширению использовать `eval`.

[FriGate Lite](https://chrome.google.com/webstore/detail/frigate-light/mdnmhbnbebabimcjggckeoibchhckemm) содержит такую же строчку.

Для проверки разрешений самостоятельно можно изучить [этот гист](https://gist.github.com/ilyaigpetrov/084ce6d706ec317b62ff99830454f443) на английском.

> Если я пропишу свой прокси в расширение, то он будет использоваться для всех сайтов из списка Антизапрет, или только для сайтов, которые я добавил вручную?

Свои прокси имеют наибольший приоритет и будут использоваться для всех проксируемых сайтов. Прокси "Антизапрет" будут иметь меньший приоритет и их можно отключить, если вы им не доверяете. Если вы хотите использовать свои прокси для своих сайтов, а для сайтов из PAC-скрипта -- встроенные в PAC-скрипт прокси, то дайте мне знать, я подумаю над реализацией.

**Comment by qTorrent** [comment]
> `unsafe-eval` разрешает расширению использовать `eval`.

Так и знал, что с расширением что-то нечисто. Спасибо за ответ.

> Для проверки разрешений самостоятельно можно изучить [этот гист](https://gist.github.com/ilyaigpetrov/084ce6d706ec317b62ff99830454f443) на английском.

Попробую осилить.

>Если вы хотите использовать свои прокси для своих сайтов, а для сайтов из PAC-скрипта -- встроенные в PAC-скрипт прокси, то дайте мне знать, я подумаю над реализацией.

Даю знать 😃. Именно на это я и намекал.

**И ещё:** не задумывались над полноценной страницей настроек для расширения? Чтобы на кнопке расширения оставить только необходимые для повседневного использования опции, а остальное вынести в настройки.

**Comment by qTorrent** [comment]
Возник вопрос насчёт опции **Проксируй или умри!**. Эта настройка касается только добавленных вручную прокси или прокси Антизапрета тоже?

Допустим, я отключу **Проксируй или умри!**, будет ли страница загружаться напрямую без прокси, если с прокси вылезает такая ошибка?

![image](https://user-images.githubusercontent.com/20108196/57242535-68328200-703c-11e9-9d4f-3f7030547b81.png)

Или это вообще не взаимосвязано и меня понесло не в ту степь?

![image](https://user-images.githubusercontent.com/20108196/57243022-b5632380-703d-11e9-9892-85ed7ddc0b83.png)

**Comment by ilyaigpetrov** [comment]
Эта настройка касается всех прокси-серверов.

Хром не считает показ такой страницы ошибкой прокси, и потому этот параметр на такие страницы не влияет. Однако не ясно, какие вообще ошибки прокси учитывает этот параметр. Я думал, что, может, `ERR_TUNNEL_CONNECTION_FAILED` при доступе к сайту по HTTPS будет учитываться, но простой тест показал, что нет.

Параметр был создан, когда при использовании прокси Тор отказывал в запросах со страниц по типу what's my ip. При этом Хром считал такие отказы за ошибки прокси и заносил его в чёрный список. Таким образом после посещения страниц what's my ip прокси Тора переставали работать на некоторое время. Удаление варианта `DIRECT` из возвращаемых PAC-скриптом прокси-серверов решало эту проблему, именно это и делает опция.
