### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ... в Chrome 58

### ISSUE THREAD

**Issue by girod2033** [anticensority/runet-censorship-bypass#51]
Если расширение отключить, а затем включить в настройках браузера, то выходит ошибка:
{
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.898",
  "platform": "Win32",
  "version": "0.0.1.32",
  "ext-error": {
    "message": "Uncaught SyntaxError: Unexpected token ...",
    "filename": "chrome-extension://npgcnondjocldhldegnakemclmfkngch/20-ip-to-host-api.js",
    "lineno": 81,
    "colno": 35,
    "error": {
      "stack": "SyntaxError: Unexpected token ...",
      "message": "Unexpected token ...",
      "name": "SyntaxError"
    },
    "type": "error"
  }
}

**Comment by ilyaigpetrov** [comment]
Это потому что вы используете старый Хром версии 58.0.3029.110.
У вас есть какие-то причины не обновлять Хром?
Я могу выпустить версию для старых браузеров, если вы меня убедите.

**Comment by girod2033** [comment]
Тут всё просто, сижу на Опере 45.0.2552.898 (PGO) потому что разработчик с выходом новых версий вырезает всё больше и больше нужных флагов для настройки браузера.

**Comment by ilyaigpetrov** [comment]
Погоняйте, пожалуйста, денёк другой следующую сборку:
[runet-censorship-bypass-0.0.1.33-full-rc1.zip](https://github.com/anticensority/runet-censorship-bypass/files/3194145/runet-censorship-bypass-0.0.1.33-full-rc1.zip)
Если будут проблемы с установкой или с самим расширением -- пишите.

**Comment by girod2033** [comment]
Установил, включил режим разработчика и собирать ошибки.
https://www56.zippyshare.com/v/tAriHrSy/file.html

**Comment by ilyaigpetrov** [comment]
`console.log` -- это не ошибки, а обычные логи (сообщения, показывающие, что происходит внутри программы).
Старые версии Хрома отображают логи как ошибки.
Вы можете включить все три типа уведомлений в расширении, и, если ошибка действительно произойдёт, то вы узнаете об этом.
Вы можете протестировать, как ваша Опера отображает настоящие ошибки, а не логи. Для этого зайдите в Developer Tools (`error_1.png` из вашего архива), и после `>` вставьте `setTimeout(() => { throw new Error('test') }, 0)` и нажмите `Enter`. Должен появиться призрак с ошибкой, а на вкладке выбора расширения в отличие от `console.log` с вопросительным знаком, вы должны увидеть сообщение с восклицательным знаком.

**Comment by girod2033** [comment]
Ага, теперь увидел: "Script error."

**Comment by ilyaigpetrov** [comment]
Я опубликовал исправленную для данной проблемы версию расширения 0.0.1.33 в WebStore.
Вам нужно переключиться со сборки для тестирования на версию из WebStore.
Если вы не переключитесь, то расширение не будет обновляться в будущем.
Я закрываю данный билет. Если у вас возникнут похожие проблемы или данная проблема не будет решена, то переоткройте билет вновь или создайте новый.
