### ISSUE TITLE
Прокси-сервер отказался обслуживать запрос

### ISSUE THREAD

**Issue by halfas** [anticensority/runet-censorship-bypass#52]
Your proxy blocked the following request:
  * Request was from page: https://play.shikimori.org/
  * To address: https://play.shikimori.org/
  * Used PAC-script: Антизапрет
  * Its Last-Modified HTTP-header: Mon, 20 May 2019 12:25:27 GMT
I think it's a mistake! Could you, please, take action to fix it.
Thank you!

Скрипт упал и не мог обновится. Перенакатил расширение, скрипт обновился, но проблема осталась.

**Comment by ValdikSS** [comment]
https://shikimori.org/forum/site/284415-onlayn-prosmotr
