### ISSUE TITLE
Не разблокирует сайт gidonline.io через СВОИ прокси

### ISSUE THREAD

**Issue by r3sus** [anticensority/runet-censorship-bypass#53]
Добавление своих прокси (различных типов, с бесплатных сайтов) и включение обязательного проксирования сайта не помогает.  
Разблокирует, например, расширение frigate.
Yandex Browser.

**Comment by ilyaigpetrov** [comment]
Во-первых, обновите используемый PAC-скрипт: иконка синей ленты -> [обновить].
После обновления попытайтесь открыть gidonline.io и сообщите нам ошибки, которые выдаёт браузер.

Во-вторых, попробуйте добавить сайт вручную:
1) Иконка синей ленты -> Исключения.
2) Вписать *.gidonline.io, выбрать "да" (проксировать этот сайт).

Похоже, что https://gidonline.io не попал в список "Антизапрет", я сообщу об этом автору.

**Comment by r3sus** [comment]
Q: Во-первых, обновите используемый PAC-скрипт: иконка синей ленты -> [обновить].
"После обновления попытайтесь открыть gidonline.io и сообщите нам ошибки, которые выдаёт браузер."
A: Что-то вроде: "Скрипт уже последней версии."
Q: Во-вторых, попробуйте добавить сайт вручную: Иконка синей ленты -> Исключения. 
Вписать *.gidonline.io, выбрать "да" (проксировать этот сайт).
A: Ошибка: требуются свои прокси.Добавление своих прокси (бесплатных) не помогает: то прокси не работают, то не обходит. Периодически браузер сообщает о проблемах безопасности (вроде связано с https). "Всё равно открыть сайт" не помогает.
Сейчас перешёл на frigate proxy helper: добавил сайт вручную и всё работает.

**Comment by ilyaigpetrov** [comment]
Возможно, вы забываете нажать кнопку "Сохранить" после добавления прокси посредством кнопки "+".

**Comment by r3sus** [comment]
Конечно же нет.

**Comment by ilyaigpetrov** [comment]
Возможно, что происходит следующее:
1) Вы добавили прокси, работающие по нешифрованнным протоколам (не HTTPS).
2) У вас выставлена галочка: иконка синей ленты -> Модификаторы -> Только шифорванная связь с прокси.

Поскольку вы требуете шифрованной связи, а прокси её предоставить не могут, то выходит такая ошибка, что прокси нет.

P.S. Посмотрите, как отображаются ваши письма на ГитХабе, -- довольно сложно читать. Так же они отображаются и у меня в почте.

**Comment by r3sus** [comment]
Извините за формат, учту.
**Ответы:**

1. Добавлял разные: и HTTP, и HTTPS, SOCKS, SOCKS4, SOCKS5.
2. Нет, такой галочки не ставил, настройки стоят стандартные. (правда, стоит "Проксируй или умр")

Прочитал файл самопомощи: через Google Translate открывает. ссылка по добавлению в РКС не работает (403).
**Дополнительная информация:**
При заходе на сайт без прокси "Ошибка шифрования", с прокси "Что-то не так с прокси". 
Думаю, всё же, проблема именно в прокси. или браузере, хотя frigate отлично справляется.
**Вопрос к вам:**
Скажите, у вас удалось запустить сайт? Если да, то можете прислать прокси (в личку), если оно бесплатное? Таким образом, можно будет убедиться, что проблема в браузере или настройках расширения.
**Баг-репорт:**
При добавлении прокси через "+" иногда добавляет ещё одно пустое прокси, которое приходится удалять (т.к. иначе выдаёт ошибку). 

**Спасибо за ваши оперативные ответы!**

**Comment by ilyaigpetrov** [comment]
> Скажите, у вас удалось запустить сайт?

Могу прислать прокси "Антизапрет", но они работают только с сайтами из реестра. gidonline.io в реестре, но почему-то "Антизапрет" его не проксирует, о чём я написал автору "Антизапрета".

gidonline.io мне удалось запустить через расширение только через "Антицензорити" и Тор (https://git.io/ac-tor).

Я подумаю, с чем может быть проблема.

**Comment by ilyaigpetrov** [comment]
Следуйте шагам из https://rebrand.ly/ac-logs.
Только вместо снимка экрана сделайте следующее.
1. На вкладке Console внизу найдите "приглашение" в виде символа `>`.
2. В поле после этого символа вставьте и нажите ввод: `JSON.stringify(window.apis.pacKitchen.getOrderedConfigs(), null, 2)`.
3. Скопируйте вывод этой команды и пришлите мне на email, адрес найдёте на https://github.com/ilyaigpetrov.

**Comment by r3sus** [comment]
Отправлено

**Comment by ValdikSS** [comment]
>gidonline.io в реестре, но почему-то "Антизапрет" его не проксирует, о чём я написал автору "Антизапрета".

У него много мусорных зеркал, и я его исключил из добавления в файл.

**Comment by ValdikSS** [comment]
Убрал "gidonline" из исключений. Попробуйте открыть сайт через 12 часов, когда обновится лист. Переоткройте это сообщение об ошибке, если проблема всё ещё будет наблюдаться через 12 часов.
