### ISSUE TITLE
значок на иконке отображает только строку-шаблон

### ISSUE THREAD

**Issue by kambala-decapitator** [anticensority/runet-censorship-bypass#54]
это иконка расширения в тулбаре хрома, в тот момент отображались некоторые «новости» при нажатии на иконку, насколько я понял:
![Screen Shot 2019-06-04 at 10 11 39](https://user-images.githubusercontent.com/1557784/58936961-b5a82900-8779-11e9-882c-2f010de11726.png)

**Comment by ilyaigpetrov** [comment]
Это не шаблон. Посмотрите [здесь](https://github.com/anticensority/runet-censorship-bypass/wiki/%D0%A7%D1%82%D0%BE-%D0%BE%D0%B7%D0%BD%D0%B0%D1%87%D0%B0%D0%B5%D1%82-%25x-%D0%BD%D0%B0-%D0%B1%D0%B5%D0%B9%D0%B4%D0%B6%D0%B8%D0%BA%D0%B5%3F). Если эта статься прояснит ситуацию, то можете закрыть данный билет.

**Comment by kambala-decapitator** [comment]
теперь понятно, спасибо!

**Comment by ilyaigpetrov** [comment]
Я не понял, при чём здесь "новости". Наверное, после появления значка вы кликали по ленте и видели "новости" расширения. Чтобы понять, что конкретно проксируется, нужно навести указатель на иконку и дождаться появления всплывающей подсказки (tooltip).

**Comment by kambala-decapitator** [comment]
> Наверное, после появления значка вы кликали по ленте и видели "новости" расширения

да, всё верно
