### ISSUE TITLE
Свои прокси только для своих сайтов, для сайтов PAC-скрипта — прокси PAC-скипта

### ISSUE THREAD

**Issue by ilyaigpetrov** [anticensority/runet-censorship-bypass#55]
Из #49:
> Если вы хотите использовать свои прокси для своих сайтов, а для сайтов из PAC-скрипта -- встроенные в PAC-скрипт прокси, то дайте мне знать, я подумаю над реализацией.

**Comment by gentlemesh** [comment]
На самом деле, вещь очень нужная!

Типичная ситуация, для чего это может понадобиться — есть некоторый ряд сайтов, которые настроены так, что либо на весь сайт, либо в админку можно зайти только с опредённого адреса/определённой подсети. Соответственно, при удалённой работе используется прокси-сервер для захода на такие сайты. Но когда этот прокси активен в настройках расширения, то, согласно текущей логике работы расширения, именно через него пытаются открываться сайты из запретного списка, и, естественно, не открываются. Приходится постоянно включать/отключать свой прокси в настройках расширения, чтобы нормально посещать все сайты. Но, во-первых, это неудобно. Во-вторых, если забыть отключить свой рабочий прокси, браузер, пытаясь выполнить запрос к сайту из запретного списка, даёт ненужную нагрузку на канал, за что уже в некоторых случаях к некоторым коллегам были претензии со стороны админов корпоративной сети.

Как это могло бы быть реализовано в расширении?
Во-первых, можно добавить соответствующую настройку во вкладку «свои прокси»: «Использовать СВОИ прокси только для СВОИХ сайтов».
Во-вторых, учитывать эту настройку в коде расширения таким образом: Если false, то всё работает как сейчас, иначе проверяется домен, и если он входит в список СВОИХ сайтов, то опять же выполняется та же ветка кода, иначе запрос выполняется как будто никакого своего прокси нет, в соответствии с дальнейшими условиями.

Для начала этого было бы более чем достаточно.

В дальнейшем, возможно, было бы неплохо сделать так, чтобы можно было задавать соответствие СВОЕГО сайта одному из СВОИХ прокси, ну, например, как-то так:

```
# ПРОКСИРОВАТЬ:
internal.site.local@corp.proxy.net:8080 # в настройках СВОИХ прокси должен быть прокси с этим доменом и портом, если такого нет, всё что после знака @ игнорируется
some.other.site # прокси не указан, поэтому либо через первый из СВОИХ прокси, либо игнор прокси полностью, в зависимости от настроек расширения
```

Тут уже логика получается более сложной, есть над чем подумать. Но самый простой вариант без сопоставлений своих сайтов и прокси, наверное, можно реализовать без особых сложностей :)

**Comment by kotenok2000** [comment]
Я за

**Comment by ilyaigpetrov** [comment]
Потестируйте, пожалуйста:
[runet-censorship-bypass-0.0.1.42-full-test1.zip](https://github.com/anticensority/runet-censorship-bypass/files/5321976/runet-censorship-bypass-0.0.1.42-full-test1.zip)

**Comment by ilyaigpetrov** [comment]
Реализовано и опубликовано в версии 0.0.1.42.
Публикация для Microsoft Edge запаздывает.
Поддержать: https://rebrand.ly/ac-donate.
