### ISSUE TITLE
Нет ни одного прокси, удовлетворяющего вашим требованиям!

### ISSUE THREAD

**Issue by alexdyukov** [anticensority/runet-censorship-bypass#56]
Собственно сабж. При попытке установки своих прокси расширение вываливает ошибку:
🔥 Error!
Нет ни одного прокси, удовлетворяющего вашим требованиям!

Хотя curl всё хавает:
```
$ curl -x socks5://195.28.182.219:443 http://binfalse.de
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
$ curl -x socks4://195.28.182.219:443 http://binfalse.de
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
$ curl -x http://195.28.182.219:8888 http://binfalse.de
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
```

Chrome 75.0.3770.100
OS: windows
ext version: 0.0.1.33

**Comment by ilyaigpetrov** [comment]
Эта ошибка возникает, когда прокси не прописаны совсем (пользователь забыл сохранить изменения, к примеру) или когда прокси прописаны вместе с какими-то требованиями (например, "только шифрованная связь с прокси", а прописанные прокси идут с нешифрованным протоколом). Эта ошибка возникает до того, как делается какое-либо соединение с прокси сервером. Проверьте, пожалуйста, все настройки (требования к прокси).

Если вам всё кажется разумным, то отправьте мне [на почту](https://github.com/ilyaigpetrov/) результат команды `window.apis.pacKitchen.getOrderedConfigs()` (следовать https://rebrand.ly/ac-logs, но вместо скриншота вставить команду в поле ввода после `>`. нажать ввод, развернуть и скопировать вывод команды).

**Comment by alexdyukov** [comment]
@ilyaigpetrov вы правы, значение в config false:
```
category: "general"
dflt: ""
key: "customProxyStringRaw"
label: "использовать СВОИ прокси"
order: 7
url: "https://rebrand.ly/ac-own-proxy"
value: false
```
да только расширение НЕ позволяет установит свой прокси, который точно рабочий
<img width="960" alt="proxy" src="https://user-images.githubusercontent.com/21895986/59967816-6bc09080-9538-11e9-9daf-7b5669ebe7a7.png">

**Comment by ilyaigpetrov** [comment]
Приведите весь вывод команды, можно здесь, можно на почту для приватности. Надеюсь, кнопку "Применить" нажать не забываете.
Если вы запомнили или знаете шаги, которые позволяют воспроизвести проблему, то также приведите их.

**Comment by alexdyukov** [comment]
@ilyaigpetrov Видео с воспроизведением проблемы скину на почту. Вот содержание JSON объекта, как вы просили:
```
[{"dflt":false,"label":"проксировать только HTTP<em>S</em>-сайты","desc":"Проксировать только сайты, доступные по шифрованному протоколу HTTP<em>S</em>. Прокси и провайдер смогут видеть только адреса проксируемых HTTP<em>S</em>-сайтов, но не их содержимое. Используйте, если вы не доверяете прокси-серверам ваш HTTP-трафик. Разумеется, что с этой опцией разблокировка HTTP-сайтов работать не будет.","order":0,"value":false,"key":"ifProxyHttpsUrlsOnly","category":"general"},{"dflt":false,"label":"только шифрованная связь с прокси","desc":"Шифровать соединение до прокси от провайдера, используя только прокси типа HTTPS или локальный Tor. Провайдер всё же сможет видеть адреса (но не содержимое) проксируемых ресурсов из протокола DNS (даже с Tor). Опция вряд ли может быть вам полезна, т.к. шифруется не весь трафик, а лишь разблокируемые ресурсы.","order":1,"value":false,"key":"ifUseSecureProxiesOnly","category":"general"},{"dflt":false,"label":"запретить опредление по IP/DNS","desc":"Пытается запретить скрипту использовать DNS, без которого определение блокировки по IP работать не будет (т.е. будет разблокироваться меньше сайтов). Используйте, чтобы получить прирост в производительности или если вам кажется, что мы проксируем слишком много сайтов. Запрет действует только для скрипта, браузер и др.программы продолжат использование DNS.","order":2,"value":false,"key":"ifProhibitDns","category":"general"},{"dflt":true,"ifDfltMods":true,"label":"проксируй или умри!","desc":"Запрещает соединение с сайтами напрямую без прокси в случаях, когда все прокси отказывают. Например, если все ВАШИ прокси вдруг недоступны, то добавленные вручную сайты открываться не будут совсем. Однако смысл опции в том, что она препятствует занесению прокси в чёрные списки Хрома. Рекомендуется не отключать.","order":3,"value":true,"key":"ifProxyOrDie","category":"general"},{"dflt":true,"category":"general","label":"использовать прокси PAC-скрипта","desc":"Использовать прокси-сервера от авторов PAC-скрипта.","order":4,"value":true,"key":"ifUsePacScriptProxies"},{"dflt":false,"category":"general","label":"использовать СВОЙ локальный Tor","desc":"Установите <a href=\"https://rebrand.ly/ac-tor\">Tor</a> на свой компьютер и используйте его как прокси-сервер. <a href=\"https://rebrand.ly/ac-tor\">ВАЖНО</a>","order":5,"value":false,"key":"ifUseLocalTor"},{"dflt":true,"category":"general","label":"учитывать исключения","desc":"Учитывать сайты, добавленные вручную. Только для своих прокси-серверов! Без своих прокси работать не будет.","order":6,"value":true,"key":"ifMindExceptions"},{"dflt":"","category":"general","label":"использовать СВОИ прокси","url":"https://rebrand.ly/ac-own-proxy","order":7,"value":false,"key":"customProxyStringRaw"},{"ifDisabled":true,"dflt":false,"category":"general","label":"проксировать .onion, .i2p и <a href=\"https://en.wikipedia.org/wiki/OpenNIC#OpenNIC_TLDs\">OpenNIC</a>","desc":"Проксировать особые домены. Необходима поддержка со стороны СВОИХ прокси.","order":8,"value":false,"key":"ifProxyMoreDomains"}]
```

**Comment by ilyaigpetrov** [comment]
Перед нажатием "Применить", нажмите "+".
Если это решение разрешает проблему, то не закрывайте этот билет -- просто сообщите, что разрешает.

**Comment by alexdyukov** [comment]
Да, это решает проблему

**Comment by ilyaigpetrov** [comment]
Заголовок билета сменился, постарайтесь придерживаться заявленной в нём темы.
Если у вас возникнут проблемы не по теме -- откройте новый билет.
Здесь же посоветуйте, пожалуйста, что и как я могу изменить в интерфейсе, чтобы пользователям было проще.

**Comment by ilyaigpetrov** [comment]
Закрыто, т.к. проблема решена. Предложить изменения неинтуитивного интерфейса можно в #57.

**Comment by alexdyukov** [comment]
Импорт/экспорт вынести на уровень кнопки "Применить".
Вместо кнопки экспорта оставить + (добавление строки).
Вместо "+" на каждой строке поставить "х" для её удаления.

Текущий вариант имеет место быть. Если прокси поля будут доступны для редактирования, то при клике на "применить" можно проверять поля на изменения. По крайней мере я ожидал данного поведения.
