### ISSUE TITLE
Chrome extension appears to be dead

### ISSUE THREAD

**Issue by vanyasem** [anticensority/runet-censorship-bypass#61]
The link to the Chrome Web Store is dead: https://chrome.google.com/webstore/detail/npgcnondjocldhldegnakemclmfkngch

<img width="505" alt="ded" src="https://user-images.githubusercontent.com/13350458/63654449-1183bc00-c783-11e9-9b45-8be86e8be12b.png">

**Comment by vanyasem** [comment]
Oh, I found an explanation by looking at the description: https://github.com/anticensority/runet-censorship-bypass/issues/10#issuecomment-524615051

I guess it's worth pinning this issue, as it was not obvious for me to look at the description and I immediately went to issues and saw nothing there.

**Comment by ilyaigpetrov** [comment]
Pinned, thank you.

**Comment by ilyaigpetrov** [comment]
Good news, our extension was restored in the WebStore.
