### ISSUE TITLE
Работа с выходом в Интернет через прокси

### ISSUE THREAD

**Issue by Safety1st** [anticensority/runet-censorship-bypass#62]
Как использовать расширение на ПК, доступ в Интернет которому обеспечивает прокси-сервер в локальной сети? Прямой доступ к прокси, прописанными в PAC-файле, открыт, но трафик на обычные сайты Chrome направляет без прокси, который прописан в настройках ОС.

**Comment by ilyaigpetrov** [comment]
В данный момент такая функциональность не реализована. Нужно как-то позволить использовать свои прокси для всех сайтов, для которых PAC-скрипт прокси не возвращает (т.е. возвращает "DIRECT").

**Comment by ilyaigpetrov** [comment]
Реализовал в этом тесте опцию "Подменить DIRECT" на вкладке "Свои прокси". Синтаксис должен соответствовать возвращаемым значениям PAC-скрипта. Если вы не программист, то дайте мне знать, но выпущу ли я эту опцию для обычных пользователей, я не могу сказать.

[runet-censorship-bypass-0.0.1.37-full-beta.zip](https://github.com/anticensority/runet-censorship-bypass/files/3617611/runet-censorship-bypass-0.0.1.37-full-beta.zip)

**Comment by Safety1st** [comment]
Я закинул все файлы вместо оригинальных. Edge детектит дополнение как повреждённое:
![image](https://user-images.githubusercontent.com/1483401/65036519-41724980-d954-11e9-9932-97a7e737af19.png)

**Comment by ilyaigpetrov** [comment]
Вот [здесь](https://www.guidingtech.com/install-chrome-extensions-microsoft-edge/) нужно найти фразу "Load unpacked button". Расширение должно быть предварительно распаковано в папку, по крайней мере в Хроме.

Про формат прописывания прокси см. https://github.com/anticensority/runet-censorship-bypass/wiki/Свои-прокси-в-расширении#Формат.

**Comment by ilyaigpetrov** [comment]
В инструкции, на которую я дал ссылку, всё как-то слишком хитро. Обычно заходишь на вкладку расширений, включаешь режим разработчика и жмёшь "load unpacked".

**Comment by Safety1st** [comment]
Всё работает!

**Comment by Safety1st** [comment]
Всё-таки не весь необходимый функционал есть: в системе настраиваются исключения, например, для адресов в сети 10.0.0.0/8...

**Comment by ilyaigpetrov** [comment]
1. В каком формате прописываются исключения? Это тоже PAC-скрипт или как-то по-другому?
2. Просто любопытно: зачем вам заблокированные сайты проксировать через один прокси, а все остальные -- через другой?

Вряд ли я смогу реализовать исключения из проксирования так, как вы хотите, но сделаю заметку на неопределённое будущее.

**Comment by Safety1st** [comment]
1. Это обычные настройки системного прокси:
![image](https://user-images.githubusercontent.com/1483401/65163037-f2571200-da42-11e9-92d5-1d4633943ffb.png)
2. В организации доступ в Интернет осуществляется через прокси-сервер.

**Comment by ilyaigpetrov** [comment]
Чтобы реализовать исключения, о которых вы просите, расширение придётся либо уродливо изменить, либо значительно переработать. Я пока не готов к таким изменениям. Устроит ли вас текущее решение, нужно ли оставить эту реализованную функциональность в следующей версии расширения?

**Comment by Safety1st** [comment]
Оставьте, пожалуйста: так я смогу просто выключить расширение, если мне нужно зайти на локальный ресурс, что приходится делать относительно редко.

**Comment by ilyaigpetrov** [comment]
Возможно, я смогу добавить вшитые исключения для локальных IP-адресов, ведь они у вас довольно стандартные. Это должно быть удобно, я не знаю случаев, когда кому-то может понадобиться проксировать стандартные локальные диапазоны.

**Comment by ilyaigpetrov** [comment]
Добавил исключения для стандартных адресов. Протестируйте, пожалуйста:
[runet-censorship-bypass-0.0.1.37-full-beta2.zip](https://github.com/anticensority/runet-censorship-bypass/files/3631102/runet-censorship-bypass-0.0.1.37-full-beta2.zip)

**Comment by Safety1st** [comment]
Тестирую...

**Comment by ilyaigpetrov** [comment]
Ну как?

**Comment by Safety1st** [comment]
Обрезает он мою настройку: ставлю PROXY n7700-sys015:8080, после повторного открытия опций − PROXY n7700-sys015. Соответственно, Интернета на ПК нет.

**Comment by ilyaigpetrov** [comment]
У меня не выходит воспроизвести. На второй бете я делаю следующее:

1. Открываю вкладку "Свои прокси" через иконку расширения.
2. Отмечаю галочкой "Подменять DIRECT на", вставляю в поле "n7700-sys015:8080".
3. Обязательно нажимаю "Применить" и закрываю окно.
4. Открываю настройку заново и вижу, что ":8080" присутствует.

Проверьте, пожалуйста, пункт 3: нажимаете ли вы "Применить" после изменений в поле?

**Comment by Safety1st** [comment]
Нажимаю, ведь hostname у меня сохраняется :) Завтра переустановлю плагин и попробую снова. Поначалу да, я без проблем вбил с портом и чуток поюзал.

**Comment by Safety1st** [comment]
Всё норм!
Единственное, надо как-то линк на [гайд](https://github.com/anticensority/runet-censorship-bypass/wiki/Свои-прокси-в-расширении#Формат) добавить. На иконку (i) наводишь мышкой −подсказка появляется, но кликнуть ссылку в ней невозможно :)

**Comment by ilyaigpetrov** [comment]
А, ясно: подсказка пропадает при попытке навести на курсор на ссылку в случае, если галочка отмечена.

**Comment by ilyaigpetrov** [comment]
Опубликовал версию 0.0.1.37 в WebStore. Вам следует переключиться на версию из WebStore, т.к. иначе вы не получите обновления в случае выхода новой версии расширения (получать обновления PAC-скрипта вы будете).

Я благодарен вам за тестирование и участие в добавлении новой функциональности. Ещё более благодарен я буду, если вы также оставите нам пожертвование: https://rebrand.ly/ac-donate.

Спасибо!
