### ISSUE TITLE
Постоянно отключается

### ISSUE THREAD

**Issue by o1o1o3** [anticensority/runet-censorship-bypass#64]
Иногда запускаю браузер, а extension выключен. То есть надо зайти в Manage extesions и включить (ползунок, аля radiobutton).

Кто-то сталкивался?

macOS: latest
Google Chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by ilyaigpetrov** [comment]
Переустановка браузера или расширения помогает? Мини версия или полная?
