### ISSUE TITLE
Неофициальный AUR пакет для Archlinux (требует ручного добавления расширения в Хромиум)

### ISSUE THREAD

**Issue by vanyasem** [anticensority/runet-censorship-bypass#66]
Запаковал пакет с хромиум расширением для Arch. Позволяет обновлять из исходников (без WebStore) через менеджер пакетов. https://aur.archlinux.org/packages/chromium-extension-runet-censorship-bypass/

**Comment by ilyaigpetrov** [comment]
Интересно.
Насколько мне известно, в Хромиум есть защита от модификаций в файловой
системе -- этот пакет делает что-то большее, чем модификации в ФС?
Или нужно из Хрома вручную добавить распакованное расширение?
Какие действия от пользователя вообще требуются при установке?

**Comment by vanyasem** [comment]
@ilyaigpetrov да, этот вручную нужно добавлять. вся суть в том, что есть хромиум отвязанный от гугла полностью. и дополнения из магазина туда не встают. этот пакет так же даёт возможность пользователю самому решать когда обновлять и обновлять ли вообще дополнение

возможность сделать автоматическую установку через магазин так же есть, но тогда теряется весь смысл

**Comment by ilyaigpetrov** [comment]
Спасибо, что создали пакет и поделились им.
Я думаю, более подходящее место для такой новости -- это наш форум https://ntc.party/c/community-software/runet-censorship-bypass-extension.
Закрываю этот билет.
