### ISSUE TITLE
Не работает с прокси-сервером Squid

### ISSUE THREAD

**Issue by positron48** [anticensority/runet-censorship-bypass#67]
1. Поднял на VPS (Centos 6) прокси сервер Squid, настройки дефолтные
2. Указал в расширении параметры сервера, получаю ошибку ERR_PROXY_CONNECTION_FAILED
3. Если при этом параметры прокси указывать в системе (W10), то все работает корректно

В логе сервере при этом видно 400 ошибки (некорректный запрос):
`1580151288.896      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151289.128      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151294.245      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151437.565      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151448.362      0 213.59.158.112 NONE/400 3718  %0F%AF%F3%DA%87y?tT%85%F8d%7E-I%CB%C0$+%90%BC8%02%C58Jmj%C4%9B%CC! - NONE/- text/html
1580151448.613      0 213.59.158.112 NONE/400 3606  %ADR%EB%D7%ED%8E%99%D7%C3%23%C2 - NONE/- text/html
1580151451.208      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151451.825      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151452.338      0 213.59.158.112 NONE/400 3778  %5Cmq%84%F0%F4:Kk%18%98%D0%D9%AE%7D%AF%AD%EE%B5%14@%A3%16%E6%60%C7%9F%84%A4%F4$%9D - NONE/- text/html
1580151452.840      0 213.59.158.112 NONE/400 3664  %07%CC&%86)%08%E3%CE,%91%18%7E%DC%01OnDf%8E - NONE/- text/html
1580151453.372      0 213.59.158.112 NONE/400 3728  %02Unk+%C7%84g%D7%FBD%CB%CE%84@wtk%04O%FDi%8D%DB%1D%CFDM%B7%E8%12k - NONE/- text/html
1580151453.931      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151454.355      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151454.778      0 213.59.158.112 NONE/400 3748  %D0%FAh%9D%8B%1B%08%16%5DM%CCh%EE%%DE%89.O%CC%5Cs%11%A3%C6=%E0%BE%D6y%950 - NONE/- text/html
1580151455.129      0 213.59.158.112 NONE/400 3798  %97%D2!%94%7F%B5%E5%7F%CD%A1%DC%D2V%DC%E80%D1%EA,%96%1B8m%DAJ%1B%EBG%B3%C8%03%AB - NONE/- text/html
1580151455.509      0 213.59.158.112 NONE/400 3750  %BE%F4%D6%85%CB%5C%7B%F4%5C%1FzN%3E%06J%86Q%1B%7E%7F%EA%93B%3E%E9%08i%60%B0%AA%D8U - NONE/- text/html
1580151455.853      0 213.59.158.112 NONE/400 3784  %3CL%A9%5C%B7%F8%8E%7F3%08%E6%9C%DB%82%DB%1B%AA%F7%8D%F0%BF%5D%9F%19x%B4%B30G%F3K%5E - NONE/- text/html
1580151456.203      0 213.59.158.112 NONE/400 3532  ?0%AD%9E*%3E - NONE/- text/html
1580151456.505      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151456.850      0 213.59.158.112 NONE/400 3754  f%D4%CDDa%F9Z%BA%5E%3Cm%A8%B7%5E%1FaX%E5%BB%BA%B1i%C7%C5%F7D%C1%BF%07@%A9%EA - NONE/- text/html
1580151457.155      0 213.59.158.112 NONE/400 3788  %F7f%F2%B3_%EA%F4%9F%8E%F8%D9T%DD%8Cu%BE%E8M%B3/%18%DB%99m%D9%CE%D5%C0%96P%9E/ - NONE/- text/html
1580151457.433      0 213.59.158.112 NONE/400 3724  %B2%A6=-%DE%E9%BF%FD%3EG%B6_%C9/%8FP%C4@Q+%8Ca%AEw%D4:;%B8R%B8%17%5B - NONE/- text/html
1580151457.745      0 213.59.158.112 NONE/400 3594  %E4%9A%84%03%80%86%60%04)%8E - NONE/- text/html
1580151458.051      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151458.345      0 213.59.158.112 NONE/400 3738  bx%9D%DCk%EF%BB%D1.%1A%01%60U%82%17D%DCl%96zx?w%98%A2i%D0%87%93%81%81 - NONE/- text/html
1580151458.663      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
1580151458.945      0 213.59.158.112 NONE/400 3622  %5D%D5%9A%DB%10%91%5B%84%D8j%AC(%16 - NONE/- text/html
1580151464.068      0 213.59.158.112 NONE/400 4015 NONE error:invalid-request - NONE/- text/html
`

При этом часть при обновлении страницы меняется строка, при настройках прокси в системе логи вполне читаемые с конкретными урлами

**Comment by ilyaigpetrov** [comment]
На прокси выставлен какой-либо пароль? Может, в расширении нужно пароль конвертировать в процент-кодировку.

**Comment by positron48** [comment]
Нет, доступ ограничен только по IP, но эта проверка проходит корректно

**Comment by ilyaigpetrov** [comment]
Не смог воспроизвести проблему, но, возможно, этот алгоритм поможет вам:
1. Поставил сквид через apt.
2. Проверил, что порт выставлен как 3128.
3. `http_access allow all`.
4. Добавил в расширении как прокси типа PROXY на порту 3128. Нажал «__Применить__».
5. Отключил встроенный в пак-скрипт прокси и отметил галочкой свои прокси (один).
6.
```sh-session
sudo tail /var/log/squid/access.log
580392261.019    435 127.0.0.1 TCP_TUNNEL/200 39 CONNECT www.kasparov.ru:443 -
HIER_DIRECT/34.194.73.87 -
1580392261.925    328 127.0.0.1 TCP_TUNNEL/200 39 CONNECT www.kasparov.ru:443 -
HIER_DIRECT/34.194.73.87 -
1580392267.341    326 127.0.0.1 TCP_TUNNEL/200 39 CONNECT www.kasparov.ru:443 -
HIER_DIRECT/34.194.73.87 -
```
Незаблоченные сайты открываются, заблоченные  выдают ERR_CONNECTION_CLOSED.
Поскольку мой провайдер блочит kasparov.ru, то всё работает так, как и ожидается.

**Comment by positron48** [comment]
Ок, попробую вечером, если не получится детальнее отпишу с версиями

на сервере стоит Centos 6, с плагином SwitchyOmega работает корректно

**Comment by ilyaigpetrov** [comment]
Можно попробовать сравнить PAC-скрипт SwitchyOmega с нашим PAC-скриптом. Интересно будет узнать, отличаются ли возвращаемые директивы из функции FindProxyForURL.
Чтобы открыть установленный в Хром PAC-скрипт: иконка синей ленты -> Проблемы? -> Отладка PAC-скрипта -> READ (должно считывать скрипт и от SwitchyOmega [пак-скрипт должен при этом быть выставлен в положение "Отключить"]).
Если вы сами не увидите ничего подозрительного при сравнении скриптов, то можете поделиться ими здесь -- мы посмотрим.

**Comment by positron48** [comment]
Слушайте, да, мое упущение. 

SwitchyOmega возвращал "PROXY ip:port", а в вашем плагине по умолчанию стоял тип HTTPS ("HTTPS ip:port; " соответственно), логично что зашифрованный трафик сервер не смог распознать и выводил в лог кракозябры...

Благодарю за помощь!
