### ISSUE TITLE
Отправлять DNS запросы через свои прокси

### ISSUE THREAD

**Issue by opiums9** [anticensority/runet-censorship-bypass#69]
Здравствуйте! Можно ли как то реализовать отправку DNS запросов через указанный прокси, как это умеет мозилла?
![image](https://user-images.githubusercontent.com/25082773/84973725-f9cf5700-b14b-11ea-9857-b84be2902365.png)
Без данной возможности я не смогу пользоваться расширением. А с текущими настройками, которые я уже все перепробовал я получаю только DNS_PROBE_FINISHED_BAD_CONFIG.
![image](https://user-images.githubusercontent.com/25082773/84973942-782bf900-b14c-11ea-93a6-bcdd4685482d.png)

Я получу примерно ту же ошибку, если уберу галочку в мозилле. Но мне хотелось бы использовать прокси для определённых сайтов, а не для всех. Расширение очень удобное и мне нравится, но я не могу его использовать в текущей корпоративной сети без данной настройки.

**Comment by ilyaigpetrov** [comment]
В [API chrome.proxy](https://developer.chrome.com/extensions/proxy) такой опции нет. Но раньше мне казалось, что ~DNS-запросы~ (доменные имена) автоматически передаются прокси-серверу, хотя бы потому, что мы получали от пользователей такие ошибки:

![ac-dns-error](https://user-images.githubusercontent.com/1090811/85029032-6017a200-b16b-11ea-8990-161607fb3db0.png)

**Comment by opiums9** [comment]
Странно, значит такое возможно сделать только в мозилле?

**Comment by ilyaigpetrov** [comment]
Мне кажется, что проблема на вашей стороне.
Сделайте домшнее задание -- попробуйте изучить опыт других пользователей Хрома:
1) https://stackoverflow.com/a/34103057/521957 (тут подтверждается, что доменное имя передаётся прокси-серверу).
2) https://bugs.chromium.org/p/chromium/issues/detail?id=29914 (тут предлагают попробовать отключить DNS prefetching).
3) https://www.chromium.org/developers/design-documents/network-stack/socks-proxy (опять говорится о DNS prefetching).

**Comment by opiums9** [comment]
Я поизучал всю информацию по ссылкам выше, рассказываю. Да, DNS запросы передаются после запуска хрома в режиме прокси с флагом --proxy-server="socks5://localhost:9150", тем самым я оказываюсь в сети тор, но само собой локальные ресурсы мне не доступны больше, так же опция --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost" работает только с указанным флагом прокси.

Я нашёл ещё вот такой флаг запуска --dns-prefetch-disable, но он не несёт никакого смысла с расширением, с ним оно так же не работает, да и вообще я не заметил особой разницы как работает интернет с этим флагом. Следовательно DNS запросы не передаются через расширение. Остаётся или использовать мозиллу, в которой можно на ходу переключать прокси, или флаг для запуска хрома (хром должен быть перед запуском выключен, иначе откроется новая вкладка). Так же я использую не хром, а Хромиум Версия 80.0.3987.149 (Официальная сборка), (64 бит), он мне больше нравится.

Теперь более подробно о сети в которой я нахожусь. Моя сеть работает через прокси сервер, который разрешает мне подключаться только по 80 и 443 порту, тор трафик блокируется. Поэтому я использую SSH туннель до дома с локальным прокси на порту 8119, но тут тоже проблема - домашний провайдер блокирует запрещённые сайты... Далее я развернул локально тор и направил его в свой SSH туннель. Всё бы хорошо, но для использования обычных и заблокированных сайтов мне приходится прыгать то в обычную сеть, то в прокси. Поэтому я и решил воспользоваться расширением, которое бы включало в нужный момент прокси сервер и упростило задачу переключения прокси на автоматическую. Но беда видимо, что DNS запросы не бегают через расширение...

**Comment by ilyaigpetrov** [comment]
Возможно, для ваших целей подойдёт расширение SwitchyOmega, но у него тоже проблемы с socks5: https://github.com/feliscatus/switchyomega/issues/572.

**Comment by opiums9** [comment]
Оо, спасибо! В этом расширении нет никаких проблем с DNS, правда мне пришлось добавить 2й HTTP прокси своей сети чтобы нормально работать, тем не менее там всё работает. Ещё пока не проверял PAC, но настроенные вручную правила уже работают. Может будет какая то возможность в вашем расширении, в будущем, сделать нечто подобное?

**Comment by ilyaigpetrov** [comment]
1) Возможно ли, что в SwitchyOmega не применяются PAC-скрипты для вашей текущей настройки?
2) Проверьте, пожалуйста, есть ли в SwitchyOmega проблемы при использовании PAC-скрипта, как в нашем расширении?

Если я пойму, в чём проблема, то смогу поправить это в расширении или открыть билет в баг-трекере Chromium.

**Comment by ilyaigpetrov** [comment]
Чтобы увидеть, что происходит с PAC-скриптом в SwitchyOmega, поставьте PAC-скрипт в нашем расширении в позицию "Отключить", убедитесь, что SwitchyOmega работает и откройте иконку с синей лентой -> Проблемы? -> Отладка PAC-скрипта -> READ.

**Comment by opiums9** [comment]
К сожалению PAC не работает так же в SwitchyOmega.

Вот настройки. Установил прокси сервера и загрузил PAC скрипт.
![image](https://user-images.githubusercontent.com/25082773/85117312-e229c880-b248-11ea-893d-263a1a55220c.png)

Указал правило, где atr - рабочий прокси сервер, в нём должен открываться 2ip.ru, а остальное должно обрабатываться PAC.
![image](https://user-images.githubusercontent.com/25082773/85117448-0f767680-b249-11ea-9571-6757e6eed19d.png)

В итоге:
![image](https://user-images.githubusercontent.com/25082773/85115582-18197d80-b246-11ea-93d7-c0db0600e5ab.png)

А 2ip.ru показал мой рабочий адрес.

PAC Sanbox:
![image](https://user-images.githubusercontent.com/25082773/85117849-b1965e80-b249-11ea-97e9-1a781a26deda.png)
full: https://files.opiums.eu/pub/anticensority.js

Так же PAC очень сильно замедляет работу SwitchyOmega и нагружает ЦП.

Поиск гугл с PAC сказал:
![image](https://user-images.githubusercontent.com/25082773/85118297-57e26400-b24a-11ea-88fc-6775b810eb7a.png)

**Comment by ilyaigpetrov** [comment]
Вы можете составить список шагов для воспроизведения проблемы с нашим расширением?
Например, у меня есть два компьютера.
На первом нужно выполнить:
1) Команда такая-то и там-то.
2) Вторая команда.
3) И т.д.

На втором нужно выполнить:
1), 2), 3)...

**Comment by opiums9** [comment]
Да я в общем даже не знаю какие шаги можно тут описать.
1. Устанавливаю расширение, включаю Антизапрет, при переходе на любой из сайтов (кроме IP) - ошибка DNS_PROBE_FINISHED_BAD_CONFIG
2. Переключаю в режим "Только свои сайты и свои прокси", добавляю список сайтов где будет работать расширение
3. В своих прокси ставлю галочку "Использовать свои прокси" и добавляю свой прокси SOCKS5, через который будет идти трафик, при переходе на любой из сайтов (кроме IP) -  ошибка DNS_PROBE_FINISHED_BAD_CONFIG

При дальнейшем включении/отключении галочек, переключение на Антицензорити и попытки открыть какой-нибудь сайт (снова же кроме IP адреса) я получу ту же  DNS_PROBE_FINISHED_BAD_CONFIG

**Comment by ilyaigpetrov** [comment]
Не нужно копировать PAC-скрипт "Антицензорити" или "АнтиЗапрет" в SwitchyOmega. Поставьте PAC-скрипт в состояние "отключить" в нашем расширении и настройте SwitchyOmega так, чтобы оно работало для вас как нужно. Далее откройте в нашем расширении `Отладка PAC-скрипта -> READ`, скопируйте оттуда текст и перешлите его сюда (должен быть небольшим). Я предполагаю, что SwitchyOmega внутри всё равно использует PAC-скрипт, даже если вы в него добавляете лишь список сайтов и прокси.
