### ISSUE TITLE
Пропал бейджик на кнопке

### ISSUE THREAD

**Issue by artquest** [anticensority/runet-censorship-bypass#70]
Приветствую,
пропал бейджик (разблокированные сайты) на кнопке в тулбаре.
Он убран в новой версии или это на моей стороне?

**Comment by ilyaigpetrov** [comment]
Если бейждик пропал на телеграме, то его просто разблокировали.
На остальных заблокированных сайтах бейждик должен присутствовать.
Проверьте на kasparov.ru, к примеру.
В мини-версии расширения его не должно быть.

**Comment by artquest** [comment]
Да, все верно, на Каспарове есть.
Спасибо.
А что, отстали от Дурова? )

**Comment by ilyaigpetrov** [comment]
Да, см. https://t.me/itsorm/1835.
