### ISSUE TITLE
Вы можете сделать так чтобы сайты, разблокируемые через скрипт проксировались через скрипт, а добавленные вручную проксировались через tor?

### ISSUE THREAD

**Issue by kotenok2000** [anticensority/runet-censorship-bypass#71]
Вы можете сделать так чтобы сайты, разблокируемые через скрипт проксировались через скрипт, а добавленные вручную проксировались через tor?

**Comment by kotenok2000** [comment]
Оказался дубликатом

**Comment by ilyaigpetrov** [comment]
Вот дубликат для справки: https://github.com/anticensority/runet-censorship-bypass/issues/55.
