### ISSUE TITLE
Firefox: Выведение ошибки Missing required argument. Be explicit if you swallow errors.

### ISSUE THREAD

**Issue by graphit0** [anticensority/runet-censorship-bypass#74]
### Description
Данный дефект приводит к выводу текста ошибки, более никаких отклонений в работе не наблюдается. Может раздражать пользователя если наблюдается нестабильное соединение.

### Окружение
используется проводной интернет, Wi-Fi подключение не тестировалось
Браузер: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
ОС: Win32
Версия расширения: 0.0.1.45

последовательность действий:
1. открыть firefox
2. отправить систему в сон 
3. вывести систему из сна

Альтернативная последовательность действий:
1. открыть firefox
2. отключить интернет
3. включить интернет

Ожидаемый результат: продолжение работы без визуального уведомления об ошибке
Реальный результат: сообщение об ошибке "Missing required argument. Be explicit if you swallow errors" 
![image](https://user-images.githubusercontent.com/44114323/97441144-70216880-1939-11eb-85fa-a33c792ce5a2.png)

Severity: trivial
Priority: middle

UPD: [ссылка на информацию об ошибке](https://anticensority.github.io/error/0.0.0.17/?json=%7B%22ext-error%22%3A%7B%22message%22%3A%22TypeError%3A%20Missing%20required%20argument.%20Be%20explicit%20if%20you%20swallow%20errors.%22,%22filename%22%3A%22moz-extension%3A%2F%2Feaafdca7-257d-45c0-aa70-3e0740d3a919%2F00-init-apis.js%22,%22lineno%22%3A31,%22colno%22%3A13,%22error%22%3A%7B%22fileName%22%3A%22moz-extension%3A%2F%2Feaafdca7-257d-45c0-aa70-3e0740d3a919%2F00-init-apis.js%22,%22lineNumber%22%3A31,%22columnNumber%22%3A13,%22message%22%3A%22Missing%20required%20argument.%20Be%20explicit%20if%20you%20swallow%20errors.%22,%22name%22%3A%22TypeError%22%7D,%22type%22%3A%22error%22%7D%7D&type=ext-error&version=0.0.1.45&useragent=Mozilla%2F5.0%20(Windows%20NT%206.1;%20Win64;%20x64;%20rv%3A82.0)%20Gecko%2F20100101%20Firefox%2F82.0&platform=Win32)
UPD2: Скрин логов:
![Bootup from sleep_error](https://user-images.githubusercontent.com/44114323/97798596-892b6180-1c38-11eb-81d3-14183e930b2a.PNG)

**Comment by ilyaigpetrov** [comment]
Будет здорово, если вы кликните по ошибке и у вас откроется страница с её
описанием.
Просто пришлите мне URL этой страницы с ошибкой, там присутствует стек,
номер строки и т.п.

**Comment by graphit0** [comment]
[Cсылка на информацию об ошибке](https://anticensority.github.io/error/0.0.0.17/?json=%7B%22ext-error%22%3A%7B%22message%22%3A%22TypeError%3A%20Missing%20required%20argument.%20Be%20explicit%20if%20you%20swallow%20errors.%22,%22filename%22%3A%22moz-extension%3A%2F%2Feaafdca7-257d-45c0-aa70-3e0740d3a919%2F00-init-apis.js%22,%22lineno%22%3A31,%22colno%22%3A13,%22error%22%3A%7B%22fileName%22%3A%22moz-extension%3A%2F%2Feaafdca7-257d-45c0-aa70-3e0740d3a919%2F00-init-apis.js%22,%22lineNumber%22%3A31,%22columnNumber%22%3A13,%22message%22%3A%22Missing%20required%20argument.%20Be%20explicit%20if%20you%20swallow%20errors.%22,%22name%22%3A%22TypeError%22%7D,%22type%22%3A%22error%22%7D%7D&type=ext-error&version=0.0.1.45&useragent=Mozilla%2F5.0%20(Windows%20NT%206.1;%20Win64;%20x64;%20rv%3A82.0)%20Gecko%2F20100101%20Firefox%2F82.0&platform=Win32) 

копия кода на странице об ошибке:
```
{
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0",
  "platform": "Win32",
  "version": "0.0.1.45",
  "ext-error": {
    "message": "TypeError: Missing required argument. Be explicit if you swallow errors.",
    "filename": "moz-extension://eaafdca7-257d-45c0-aa70-3e0740d3a919/00-init-apis.js",
    "lineno": 31,
    "colno": 13,
    "error": {
      "fileName": "moz-extension://eaafdca7-257d-45c0-aa70-3e0740d3a919/00-init-apis.js",
      "lineNumber": 31,
      "columnNumber": 13,
      "message": "Missing required argument. Be explicit if you swallow errors.",
      "name": "TypeError"
    },
    "type": "error"
  }
}
```

**Comment by ilyaigpetrov** [comment]
Странно, но в Firefox'е у ошибки не показан стек.
Попробуйте:
1) Отключить и включить расширение на about:addons.
2) Вызвать ошибку, не выполняя лишних действий.
3) Открыть логи (см. https://rebrand.ly/ac-logs), раскрыть ошибк(y/ки)
(ошибки выделены красным), чтобы были видны все её свойства, сделать
скриншот и выслать мне.
4) Можно дополнительно скопировать логи как текст и приложить
к письму/ответу вместе со скриншотами.

**Comment by graphit0** [comment]
После перезагрузки системы ошибка перестала воспроизводиться, соответственно можно закрывать тему. Если встречусь еще раз с этой ошибкой, пришлю более подробные логи. Спасибо за оперативный ответ.

**Comment by ilyaigpetrov** [comment]
Для открытия консоли с логами в FireFox:
1) Открыть about:debugging#/runtime/this-firefox.
2) Найти наше расширение и нажать "исследовать" (inspect).
3) Открыть вкладку Console/Консоль.

**Comment by graphit0** [comment]
### Логи об ошибке
Ошибка воспроизводилась с помощью выхода системы из сна по шагам из шапки

[Bootup from sleep_error.txt](https://github.com/anticensority/runet-censorship-bypass/files/5470432/Bootup.from.sleep_error.txt)

Скрин логов для удобства чтения:
![Bootup from sleep_error](https://user-images.githubusercontent.com/44114323/97798596-892b6180-1c38-11eb-81d3-14183e930b2a.PNG)

##### Попытка воспроизвести ошибку из исходного состояния Firefox
После перезапуска Firefox ошибка указанная в шапке перестает воспроизводиться (соответственно свежий запуск Firefox без истории и открытых вкладок/лишних действий пока не представился возможным), однако появляется другая: `Error: An unexpected error occurred`

Выполенная последовательность:
0. Закрыть Firefox после воспроизведения ошибки из шапки
1. Открыть Firefox
Result: `Error: An unexpected error occurred`

Логи во вложении: [after restart of Firefox_initial error is gone_new one is up.txt](https://github.com/anticensority/runet-censorship-bypass/files/5470431/after.restart.of.Firefox_initial.error.is.gone_new.one.is.up.txt)
Следующая перезагрузка не приводит к ошибке `Error: An unexpected error occurred` (перестает воспроизводиться).

**Comment by ilyaigpetrov** [comment]
Ошибка возникает при отсутствии подключения к Интернету.
Исправлено в версии 0.0.1.46 -- обновитесь и протестируйте.

Благодарю вас за извещение о баге. Буду также рад, если вы нас поддержите: https://rebrand.ly/rcb-donate.
