### ISSUE TITLE
Some domains are not working in Turkey

### ISSUE THREAD

**Issue by aqaq55aq** [anticensority/runet-censorship-bypass#78]
Hi, thank you for this great extension. I am living in Turkey and we also have a lot of blocked websites. This extension works almost in every website but some of them are still blocked. I hope you can add these domains to the bypass list. They are all the most used websites in Turkey. Thank you in advance!

https://imgur.com/
http://i.imgur.com/
https://i.redd.it/
https://i.imgur.com/
https://i.4cdn.org/
http://i.4cdn.org/
http://is2.4chan.org/
https://is2.4chan.org
http://boards.4chan.org
https://boards.4chan.org
http://boards.4channel.com
https://boards.4channel.org

**Comment by ilyaigpetrov** [comment]
Sorry, but our solutions only work with Russian registry of blocked sites.
Only in very rare exceptional cases we add sites manually.
We won't add the sites you suggested.

However inside the extension you may add your own proxy servers (https://rebrand.ly/ac-own-proxies) or tor (https://git.io/ac-tor) and after that you may manually add to exceptions any sites you want -- they will be proxied via YOUR servers.

If you have difficulties with using Russian interface -- just open a new issue here with texts you want to be translated.
