### ISSUE TITLE
[Firefox] Нет возможности зайти на nnmclub.to

### ISSUE THREAD

**Issue by Quaterberg** [anticensority/runet-censorship-bypass#80]
Собственно суть проблемы в названии темы. Расширение, как и ручная настройка, не дают зайти на сайт.
https://imgur.com/hqpxpnN
При этом в Chrome такой проблемы нет, расширение успешно работает и сайт открывается.
В чем может быть проблема?

**Comment by ilyaigpetrov** [comment]
У вас Интернет-провайдер -- Билайн или какой-либо другой?

**Comment by ilyaigpetrov** [comment]
Если у вас не Билайн, но показывается заглушка от Билайна, то в таком случае блокируется транзитный трафик, идущий через сеть Билайна к хостингу сайта. Поможет лишь смена хостинга на заграничный.

Если у вас Билайн, то нужно попробовать прочистить кеш браузера (не знаю, как это делается в FireFox -- попробуйте найти инструкции самостоятельно).

**Comment by Quaterberg** [comment]
Нет, провайдер не Билайн, а "местный".
Почистил кэш и куки через сtrl+shift+del теперь показывает совершенно другую ошибку - Соединение было сброшено
https://imgur.com/UsUqcOQ
При этом опять же в Chrome все работает.

**Comment by ilyaigpetrov** [comment]
Другие заблокированные сайты открываются?
https://www.kasparov.ru, https://graniru.org?

**Comment by Quaterberg** [comment]
В Файрфоксе нет, в хроме открываются.
Версия ФФ 83.0 (64-битный)

**Comment by ilyaigpetrov** [comment]
1) Откройте about:debugging#/runtime/this-firefox.
2) На плашке с нашим расширением нажмите "исследовать" (inspect).
3) В открывшемся окне выберите вкладку "Консоль" (Console).
4) Вы увидите логи расширения. Самые интересные записи помечены красным -- это ошибки.
5) Сделайте снимок экрана логов или скопируйте их в текстовой форме и пришлите сюда.

**Comment by Quaterberg** [comment]
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. webrequest.js:107
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 8 webrequest.js:107
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 8 webrequest.js:107
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Attempt to postMessage on disconnected port background.js:27
Attempt to postMessage on disconnected port background.js:36
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Unchecked lastError value: Error: Invalid tab ID: 76 firefox.js:77
Unchecked lastError value: Error: Invalid tab ID: 76 recentlyclosed.js:9
Unchecked lastError value: Error: Invalid tab ID: 76 index.js:24
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/js/_external/broadcaster.js:93
broadcaster.js:93:35

**Comment by Quaterberg** [comment]
[console-export-2020-11-26_10-34-23.txt](https://github.com/anticensority/runet-censorship-bypass/files/5601135/console-export-2020-11-26_10-34-23.txt)

**Comment by ilyaigpetrov** [comment]
По логам видно, что ошибка возникает в расширении с идентификатором a73422e2-9155-483f-9e92-5a53f269b6d2.
Попробуйте узнать, что это за расширение (наше ли или другое):
1) Попробуйте найти имя расширения в этом файле: moz-extension://a73422e2-9155-483f-9e92-5a53f269b6d2/manifest.json.
2) На странице about:debugging#/runtime/this-firefox попробуйте найти расширение с упомянутым id.

**Comment by Quaterberg** [comment]
Действительно, проблема возникает с расширением https://addons.mozilla.org/ru/firefox/addon/fvd-speed-dial/
Отключив его, сайт стал доступен.
