### ISSUE TITLE
Поддержка Safari 14+

### ISSUE THREAD

**Issue by rakleed** [anticensority/runet-censorship-bypass#82]
Было бы неплохо, если бы ваше расширение было доступно для Safari. Т. к. начиная с 14 версии появилась поддержка WebExtensions API. Подробнее: https://developer.apple.com/documentation/safariservices/safari_web_extensions

**Comment by ilyaigpetrov** [comment]
Apple не выпускает Safari под Linux, так что я не уверен, что смогу портировать и протестировать наше расширение на этой платформе.

**Comment by rakleed** [comment]
Hackintosh не получится у вас использовать?

**Comment by ilyaigpetrov** [comment]
Слишком много возни с хакинтошем, если честно. Я думаю, оно того не стоит.

**Comment by rakleed** [comment]
Если когда-то всё же будете делать расширение для Safari, то с выходом iOS 15 в Safari для iOS также появится поддержка Safari Web Extensions, соответственно можно будет сделать поддержку и для iOS.

**Comment by ilyaigpetrov** [comment]
Для iOS можно использовать наш бесплатный VPN уже сейчас -- см.
https://antizapret.prostovpn.org.
