### ISSUE TITLE
Проблема с реактором

### ISSUE THREAD

**Issue by ghost** [anticensority/runet-censorship-bypass#84]
Я задолбался уже бесплатные прокси искать на помойках, добавьте реактор под прокси пожалуйста.
reactor.cc

**Comment by ilyaigpetrov** [comment]
1) Сайт не заблокирован. Если вы видите заглушку провайдера при его
посещении, то попробуйте сперва попросить провайдера его разблокировать на
основе того, что его нет реестре.
2) Вы можете использовать PAC-скрипт "Антицензорити" с Тором в качестве
прокси (https://git.io/ac-tor). С недавних пор работает и в расширении для
FireFox. Сообщите нам, если у вас возникнут какие-либо сложности с этим
способом обхода цензуры.

**Comment by ghost** [comment]
Сайт то доступен, однако на некотором контенте стоит заглушка для жителей
России.
Вы можете добавить сайт в свой список, чтобы контент с заглушкой был
доступен именно через ваши стабильные прокси.
Если вы этого не можете сделать, просто проигнорируйте данное сообщение.
Спасибо.

ср, 9 дек. 2020 г. в 14:39, ilyaigpetrov <notifications@github.com>:

> 1) Сайт не заблокирован. Если вы видите заглушку провайдера при его
> посещении, то попробуйте сперва попросить провайдера его разблокировать на
> основе того, что его нет реестре.
> 2) Вы можете использовать PAC-скрипт "Антицензорити" с Тором в качестве
> прокси (https://git.io/ac-tor). С недавних пор работает и в расширении
> для
> FireFox. Сообщите нам, если у вас возникнут какие-либо сложности с этим
> способом обхода цензуры.
>

**Comment by Janitor53** [comment]
Заглушку выводит сам сайт для пользователей с российских IP адресов при запросе запрещённого к показу в РФ контента.
Обход подобных ограничений выходит за рамки предназначения данного расширения.
