### ISSUE TITLE
Changing the license from GPLv3 to Unlicensed (Public Domain) / Смена лицензии на публичный домен (общественное достояние)

### ISSUE THREAD

**Issue by ilyaigpetrov** [anticensority/runet-censorship-bypass#85]
@dchusovitin @lex111 @TemaSM @monkeywithacupcake

Happy holidays, guys.

I want to change the license of this repo from GPLv3 to Unlicensed (Public Domain, http://unlicense.org/).
You are all the contributors to this project, I need your permission for your contributions to be re-licensed.

I'm not a lawyer and I don't know the correct procedure of re-licensing a repo which has contributions.

1) Maybe you or your acquaintances know how to correctly re-license a repo with contributions?
2) Let me know in the comments below if you agree or disagree to give me permission to re-license this repo with your contributions. Please, keep this discussion thread in English and on topic, otherwise contact me via email (see at https://github.com/ilyaigpetrov).

Best regards,
ilyaigpetrov.

**Comment by dchusovitin** [comment]
Hello,
All contributors (except @ilyaigpetrov) have made only 1-2 commits. So I think you can do what you want because you do all work.
This issue is the notice of license changing. I think you can change the license starting from 1 January.

PS. And, thank you for your work :blush:

**Comment by ilyaigpetrov** [comment]
@dchusovitin, thanks for your reply.
Have you consulted with any lawyer or is it just your personal opinion?

**Comment by dchusovitin** [comment]
> @dchusovitin, thanks for your reply.
> Have you consulted with any lawyer or is it just your personal opinion?

Yes, it's just my opinion (answer to part 2 of your question). I had tried to search the answer to the question..., but I'm not a law layer too.

**Comment by ilyaigpetrov** [comment]
I became fine with GPLv3, not migration is planned as of now.
