### ISSUE TITLE
Возможность добавлять исключения без поддоменов: тест v0.0.1.50.

### ISSUE THREAD

**Issue by ilyaigpetrov** [anticensority/runet-censorship-bypass#87]
Раннее обсуждение: https://groups.google.com/g/anticensority/c/zMgFKx5BBSg.

[runet-censorship-bypass-0.0.1.50-full-test0.zip](https://github.com/anticensority/runet-censorship-bypass/files/5826503/runet-censorship-bypass-0.0.1.50-full-test0.zip)
[runet-censorship-bypass-0.0.1.50-full-test1.zip](https://github.com/anticensority/runet-censorship-bypass/files/5830426/runet-censorship-bypass-0.0.1.50-full-test1.zip)
[runet-censorship-bypass-0.0.1.50-full-test2.zip](https://github.com/anticensority/runet-censorship-bypass/files/5830539/runet-censorship-bypass-0.0.1.50-full-test2.zip)

Архив подходит для большинства браузеров (Chromium, FireFox).
Инструкции для хрома:
1) Распаковать архив в папку.
2) Зайти на chrome://extensions, включить режим разработчика.
3) Добавить распакованное расширение.
4) Включить все уведомления об ошибках.
5) Протестировать.

**Comment by ilyaigpetrov** [comment]
Опубликовано для Chromium. Остальные платформы будут позднее.

**Comment by Gagauzino** [comment]
Reply

вс, 24 янв. 2021 г. в 18:25, ilyaigpetrov <notifications@github.com>:
