### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by azazar** [anticensority/runet-censorship-bypass#88]
Вот такую ошибку часто вижу в последнее время:

![Screenshot_2021-01-25_09-52-21 - extension error](https://user-images.githubusercontent.com/2816075/105663163-5e793e00-5ef3-11eb-8b78-6906b8fb2a9a.png)

```json
{
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36",
  "platform": "Linux x86_64",
  "version": "0.0.1.50",
  "ext-error": {
    "message": "Uncaught TypeError: Cannot convert undefined or null to object",
    "filename": "chrome-extension://npgcnondjocldhldegnakemclmfkngch/11-error-handlers-api.js",
    "lineno": 208,
    "colno": 9,
    "error": {
      "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:560:41",
      "message": "Cannot convert undefined or null to object",
      "name": "TypeError"
    },
    "type": "error"
  }
}
```

**Comment by ilyaigpetrov** [comment]
Как часто проявляется эта ошибка?
Вроде, должна лишь один раз появиться.

**Comment by ilyaigpetrov** [comment]
Опубликовал исправление. Публикация может занять до двух недель в худшем случае.
Чтобы не ждать этот срок, вы можете переустановить расширение.

**Comment by ilyaigpetrov** [comment]
Исправление доступно в версии 0.0.1.51.
Просто обновитесь. Для форсирования обновления:
1) Открыть chrome://extensions.
2) Включить режим разработчика (developer mode).
3) Нажать "Обновить" (Update).
4) Проверить там же, что версия расширения изменилась на 0.0.1.51.
