### ISSUE TITLE
`TypeError: Failed to fetch` | Из-за CORS и ограничения доступа расширения к сайтам "При нажатии" ("On click")

### ISSUE THREAD

**Issue by bananakid** [anticensority/runet-censorship-bypass#89]
Часто при автообновлении расширения (особенно заметно было в 0.0.1.50 и 0.0.1.51, появившихся друг за другом в короткий промежуток времени) в Chrome отваливается PAC-скрипт Antizapret целиком. При попытке обновить скрипт ссылкой update внизу вывозится сообщение `Failed to download PAC-script from addresses: [ https://antizapret.prostovpn.org/proxy.pac ]. > Что-то не так с сетью, проверьте соединение. > Failed to fetch`. Переключение в `Disabled` не помогает, т.к. после этого невозможно вернуть радиобаттн на `Antizapret` (при клике по `Antizapret` радиоббатн сбрасывается обратно на `Disabled` и внизу появляется всё та же ошибка фетча PAC-скрипта). Помогает удаление расширения с повтороной установкой из Google Web Store. Галочки в настройках расширения стоят только напротив `Использовать прокси PAC-скрипта`, `Проксируй или умри`. В настройках расширения в Chrome выставлено `Allow this extension to read and change all your data on websites you visit: On click`. Примечательно также, что сама страница скрипта по адресу `https://antizapret.prostovpn.org/proxy.pac` открывается без проблем, несмотря на ошибку. Ниже привожу текст ошибки:
```
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.51",
  "pup-ext-err": {
    "message": "Failed to download PAC-script from addresses: [ https://antizapret.prostovpn.org/proxy.pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  }
}
```

**Comment by ilyaigpetrov** [comment]
Дополняю: если посмотреть в логи расширения (https://rebrand.ly/ac-logs), то при попытке включить PAC-скрипт "АнтиЗапрет" там появляется ошибка CORS:

> Access to fetch at 'https://antizapret.prostovpn.org/proxy.pac' from origin 'chrome-extension://npgcnondjocldhldegnakemclmfkngch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ilyaigpetrov** [comment]
После установки расширения опция `Allow this extension to read and change all your data on websites you visit:` должна быть выставлена в положение `On all sites`.
1) Меняли ли вы эту настройку когда-либо?
2) Что будет, если в случае возникновения этой ошибки, выставить значение `On all sites`? Будет ли этого достаточно для исправления?

**Comment by bananakid** [comment]
1. Да, я контролирую настройки доступа расширений и вручную задал `Allow this extension to read and change all your data on websites you visit: On click`.
2. После задания `Allow this extension to read and change all your data on websites you visit: On all sites` ошибка не возникает, PAC-скритп обновляется без проблем.

Возможно, стоит добавить информацию о `Allow this extension to read and change all your data on websites you visit` в справку и ткнуть носом, где я не прочитал (искал по описанию ошибки из лога прежде чем создать тикет).

**Comment by ilyaigpetrov** [comment]
Задокументировал на https://rebrand.ly/ac-site-access.
Также добавил в https://rebrand.ly/ac-wiki.
Спасибо за то, что сделали расширение чуть лучше.
