### ISSUE TITLE
Автообновление PAC-скрипта не срабатывает после выхода из спячки (ошибка DNS ERR_NAME_NOT_RESOLVE)

### ISSUE THREAD

**Issue by bpgusar1** [anticensority/runet-censorship-bypass#90]
Изза этого прокси не обновляются, и сайты не открываются. Приходится постоянно самому обновлять его.

**Comment by ilyaigpetrov** [comment]
Если в меню расширения вы видите улитку, то у вас полная версия (улитка = открыть информацию о мини версии).
Если в меню расширения вы видите штангиста, то у вас мини версия (штангист = открыть информацию о полной версии).
В любом случае всё должно работать и обновляться автоматически, даже в мини версии.

0) Загляните в логи (https://rebrand.ly/ac-logs) -- если там есть красные сообщения (ошибки), то пришлите снимок.
1) Какой у вас браузер? Из какого магазина установлено расширение (MS Edge add-ons, Firefox add-ons, google webstore)?
2) Есть ли какие либо ошибки при ручном обновлении PAC-скрипта.

**Comment by bpgusar1** [comment]
![image](https://user-images.githubusercontent.com/4145328/107115138-82396e00-687b-11eb-944c-ab15fcb30b18.png)
скрин логов
браузер хром, ставил из магаза гугла
если вручную обновлять ошибок нет

**Comment by ilyaigpetrov** [comment]
В логах видна ошибка `ERR_NAME_NOT_RESOLVE` (для доменного имени какого-то сайта/ресурса не удаётся получить IP-адрес). Эта ошибка при каждом обновлении возникает? Возможно, проблема с https://antizapret.prostovpn.org -- этот сайт у вас в браузере открывается? Заодно проверьте также сайт https://cloudflare-ipfs.com.

Строчка `Periodic PAC update triggered` в логах, я думаю, говорит о том, что таймер (будильник) срабатывает, как и должно, начинается процесс обновления PAC-скрипта, потом возникает ошибка, связанная с DNS.

**Comment by ilyaigpetrov** [comment]
Эта ошибка возникает только после запуска компьютера, когда сеть ещё не совсем поднялась? Или при закрытии-открытии хрома при наличии установившегося соединения тоже возникает?

**Comment by bpgusar1** [comment]
да. когда только включаю комп. точнее из спящего режима включаю. браузер то уже открыт. инэт на компе уже есть в тот момент. пробую открывать рутор например и РСТК пишет "слышь заблокировано".

**Comment by goonis** [comment]
Аналогичная проблема на Chrome 90 на ноутбуке работающем по Wi-fi, подозреваю что после выхода из гибернации триггер Periodic PAC update срабатывает раньше чем восстанавливается сеть.

**Comment by ilyaigpetrov** [comment]
@goonis, у вас такая же ошибка или другая?

**Comment by ilyaigpetrov** [comment]
@goonis, @bpGusar, посмотрите, пожалуйста, после восстановления работы ОС логи расширения (см. https://rebrand.ly/ac-logs).
В логах нужно найти строчку "We are online, checking periodic updates...". Также в логах интересны ошибки (красные записи), возникаютщие около этой строчки.

**Comment by goonis** [comment]
Слепил на коленке весь лог в один png.
![Untitled](https://user-images.githubusercontent.com/8069033/118706295-df9d6d80-b821-11eb-92c6-2d2b60389349.png)

**Comment by ilyaigpetrov** [comment]
По сути, в случае восстановления работы ОС я ожидаю, что браузер вызовет событие "мы подключены к Интернету (online)", но по логам видно, что строчка "We are online, checking periodic updates..." не фигурирует.
@goonis, у вас, я вижу, Windows 7.
@bpGusar -- у вас windows 10?
Интересно, одинаково ли ведут себя в таких случаях разные ОС (win10, Linux).

**Comment by ilyaigpetrov** [comment]
[runet-censorship-bypass-0.0.1.52-full-test3.zip](https://github.com/anticensority/runet-censorship-bypass/files/6534018/runet-censorship-bypass-0.0.1.52-full-test3.zip)

Протестируйте пару деньков, пожалуйста.
В этой версии делается до 4 попыток получить информацию с серверов (pac-скрипт и dns), интервалы попыток: 20с, 40с, 60с.

**Comment by ilyaigpetrov** [comment]
Ну как? Можно публиковать? Стоит менять интервалы между попытками?

**Comment by bpgusar1** [comment]
> Ну как? Можно публиковать? Стоит менять интервалы между попытками?

Я ничего не ставил себе версию из архива но, тем не менее, начало нормально работать. Видимо проблема решена

**Comment by goonis** [comment]
У меня версия из архива ставится, и работает но до первого выключения в Disable, далее при попытке выбрать любые из трех других режимов висит вечное "Installing..." и неактивная кнопка ОК. При выключении/включении или Reload-инге на странице  chrome://extensions/ снова возвращается режим "Disable". 
Для проверки своей проблемы перед hibernate поставлю с нуля и завтра вечером отчитаюсь понадобилось ли передергивать статус после выхода из гибернации.

**Comment by ilyaigpetrov** [comment]
@goonis, исправил -- тестируйте:
[runet-censorship-bypass-0.0.1.52-full-test4.zip](https://github.com/anticensority/runet-censorship-bypass/files/6548391/runet-censorship-bypass-0.0.1.52-full-test4.zip)

**Comment by goonis** [comment]
Выход из гибернации прошел успешно, F5 на ранее открытом сайте из списка РКН успешно открыло его чего не делает версия из  Chrome Web Store

**Comment by ilyaigpetrov** [comment]
Опубликовано в WebStore в версии 0.0.1.52 -- см. https://rebrand.ly/ac-webstore.
Спасибо за идею!
