### ISSUE TITLE
Запароленный socks5 proxy

### ISSUE THREAD

**Issue by koloved** [anticensority/runet-censorship-bypass#92]
не получается использовать nord vpn сокс5 прокси с авторизацией, не могу нажать кнопку применить

прокси - amsterdam.nl.socks.nordhold.net
порт - 1080
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0",
  "platform": "Win32",
  "version": "0.0.1.51",
  "pup-ext-err": {
    "fileName": "moz-extension://d3beb984-2300-4f94-826b-90cddd86ba89/35-pac-kitchen-api.js",
    "lineNumber": 280,
    "columnNumber": 17,
    "message": "Нет ни одного прокси, удовлетворяющего вашим требованиям!",
    "name": "TypeError"
  }
}

**Comment by ilyaigpetrov** [comment]
Нужно нажать на плюсик справа от порта.
В этом у вас проблема?
Предложения по изменению интерфейса принимаются здесь:
https://github.com/anticensority/runet-censorship-bypass/issues/57.

**Comment by koloved** [comment]
Сохранил спасибо, я все время думал что это кнопочка для добавления еще одного сервера и жмякал на кнопку "сохранить"

теперь правда не открываются сайты через этот прокси, окно авторизации не показывается

**Comment by koloved** [comment]
https://prnt.sc/10rjkif

**Comment by ilyaigpetrov** [comment]
Вы прописали логин и пароль для прокси?
По типу ***@***.***, см.
https://github.com/anticensority/runet-censorship-bypass/wiki/Прокси-и-пароль
.

**Comment by koloved** [comment]
Теперь прописал, только не работает так же, прописал именно в таком виде, несколько раз просмотрел, все верно должно быть

**Comment by ilyaigpetrov** [comment]
Можете прислать мне логин, пароль и адрес прокси на email (см. на https://github.com/ilyaigpetrov/)?
Я постараюсь проверить сегодня-завтра.

**Comment by ilyaigpetrov** [comment]
В FoxyProxy для FireFox [используется][1] API [browser.proxy.onRequest][2], который недоступен в Хроме.

[1]: https://github.com/foxyproxy/firefox-extension/blob/6f8c0154e4f2937d93b23d4ddf685fd9f6821438/src/scripts/background.js#L185

[2]: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/onRequest

Скорей всего, я не буду добавлять поддержку запароленных socks только для FireFox (это сломает или усложнит архитектуру).

Запароленные HTTP- и HTTPS-прокси должны поддерживаться на всех платформах.
