### ISSUE TITLE
Борьба с замедлением «Твиттера» в России 

### ISSUE THREAD

**Issue by Twilightssuperb** [anticensority/runet-censorship-bypass#93]
Пока в расширении нет индивидуальных списков проксирования (доступны только через свои прокси), прошу как-то помочь снова нормально пользоваться «Твиттером». Вашему расширению очень доверяю, в отличие от разных там сомнительных бесплатных VPN (забавно, кстати, что некоторые из них нельзя запустить в режиме инкогнито браузера, что выглядит довольно подозрительно; Browsec работает в инкогнито, всякие ноунеймы — нет, Cent Browser, 4.3.9.248, Canvas fingerprint и Web RTC отключены силами браузера). Но тем же Browsec (как и любым VPN-аддоном) невозможно пользоваться на сайтах, где требуется моё текущее местоположение, и вообще привычные сайты ругаются на необычный вход.

Плюс задать исключение, чтобы VPN работал только для определённого домена, можно лишь для одного сайта в большинстве расширений. Был FriGate, и тот себя скомпрометировал.

А отказываться от «Обхода блокировок Рунета» не хочется.

Добавьте, пожалуйста, *.twitter.com в список Антизапрет.

**Comment by MasterPetrik** [comment]
Список Антизапрета никак не связан с автором расширения. Это вам надо им и писать и их просить. 
Милости прошу создать такую тему у них на форуме: https://ntc.party/c/antizapret-prostovpn-org/5
Или в сааамом крайнем случае напишите создателю Антизапрета(но я бы на вашем месте его по таким мелочам не дёргал)

Не думаю что они горят желанием бесплатно проксировать весь траффик незаблокированного сайта из топ10 по мировому траффику только потому что у кого-то он открывается чуть медленнее. Антизапрет это всё таки про список блокировки РКН и про его автоматическое подцепление а не про ручное добавление в список сайтов по заявкам. 

Или просто подождите месяц-два пока твиттер полностью не заблокируют в РФ, тогда он вероятно таки будет доступен через антизапрет.

**Comment by ilyaigpetrov** [comment]
АнтиЗапрет связан с этим расширением. Его автор читает билеты в этом репозитории по моим наводкам.
Касательно твиттера -- он ответил, что собирается ждать даты блокировки (15 мая).

**Comment by koloved** [comment]
Поднимите у себя на компьютере сервис TOR , статьи есть и проксируйте через него

**Comment by ilyaigpetrov** [comment]
Да, тор -- тоже вариант. См. https://rebrand.ly/ac-tor и
https://rebrand.ly/ac-own-proxies.

**Comment by ilyaigpetrov** [comment]
Сегодня замедление с твитера снято РКН.
