### ISSUE TITLE
Аналог белого списка при использовании PAC скрипта Антизапрета

### ISSUE THREAD

**Issue by MasterPetrik** [anticensority/runet-censorship-bypass#94]
Сейчас в плагине есть возможность проксировать скриптом только отдельные сайты только в режиме "Свой прокси". При этом если выбрать режим с прокси Антизапрета, то невозможно указать ему работу только на выбранных сайтах(при том что все выбранные сайты находятся в списке антизапрета, и технически ничего не должно мешать плагину это сделать). 

Была предпринята попытка решить проблему с другой стороны, а именно разрешить плагину доступ только к определённым доменам(а именно домены нужных сайтов +  сайт антизапрета) в стандартных настройках доступа плагинов хрома, но при таком подходе по неизвестной мне причине плагин выдаёт ошибку обновления скрипта: 
![image](https://user-images.githubusercontent.com/22294259/117911501-91024780-b2e6-11eb-8f2b-82b6c03534ad.png)
![image](https://user-images.githubusercontent.com/22294259/117911431-7334e280-b2e6-11eb-8154-8aa5c6db94c9.png)

Зачем вообще всё это надо? Во-первых чтобы не нагонять лишнего траффика ребятам из антизапрета со своей стороны, а во-вторых чтобы не резать скорость доступа(это прокси всё таки, скорость всё равно ниже, хоть ты тресни) к 98% заблокированных сайтов которые отлично открываются и локальными методами не режущими скорость(GoodbyeDPI), а проксировать только те сайты из списка антизапрета, с которыми локальный метод не помогает. 

В связи с чем прошу рассмотреть следующее:

1. Добавление возможности использовать прокси только на выбранных сайтах при использовании прокси Антизапрета(принадлежность введённого/указанного сайта к списку скрипта Антизапрета должна проверяться в момент попытки добавления) 
2. Либо объяснить почему плагин не может обновить скрипт при предоставленном доступе к сайту антизапрета(Возможно какие-то ещё технические домены требуется добавлить в список о которых я не знаю?)

**Comment by ilyaigpetrov** [comment]
> 1. Добавление возможности использовать прокси только на выбранных сайтах при использовании прокси Антизапрета(принадлежность введённого/указанного сайта к списку скрипта Антизапрета должна проверяться в момент попытки добавления) 

Предлагаю такой алгоритм:
1) Проверяем адрес в списке АнтиЗапрета.
2) Если в результате сайт нужно проксировать, то проверяем его на наличие в белом списке.
3) Если сайт в списке, то проксируем, если нет -- то не проксируем (отдаём DIRECT).

> 2. Либо объяснить почему плагин не может обновить скрипт при предоставленном доступе к сайту антизапрета(Возможно какие-то ещё технические домены требуется добавлить в список о которых я не знаю?)

Нужно добавить домен antizapret.prostovpn.org, но не только его, а все домены, на которые перенаправляет исходный домен (в данный момент это cloudflare-ipfs.com, но со временем он может смениться без предупреждения). Тогда ошибка обновления должна уйти. Но есть проблема поважнее: PAC-скрипт игнорирует список сайтов допустимых для расширения (я в этом не уверен, но вы можете проверить самостоятельно).

**Comment by ilyaigpetrov** [comment]
> PAC-скрипт игнорирует список сайтов допустимых для расширения (я в этом не уверен, но вы можете проверить самостоятельно).

Проверил -- игнорирует.

**Comment by ilyaigpetrov** [comment]
1. Проверяем наличие сайта в белом списке (довольно быстро).
2. Если присутствует в списке, то запускаем основной алогритм PAC-скрипта (он самый медленный)
3. Выдаём ответ основного алгоритма PAC-скрипта.
4. Если сайт не присутствует в списке, то отдаём DIRECT (основной алгоритм не запускается).

Этот алгоритм будет быстрее для сайтов не из белого списка.

**Comment by ilyaigpetrov** [comment]
[runet-censorship-bypass-0.0.1.52-full-test2.zip](https://github.com/anticensority/runet-censorship-bypass/files/6495645/runet-censorship-bypass-0.0.1.52-full-test2.zip)

Протестируйте, пожалуйста.
Иконка синей ленты -> Исключения (Exceptions) -> "[x] Ограничиться только белым списком".

**Comment by MasterPetrik** [comment]
Да, протестировал, белый список функционирует как положено! Спасибо.

Хотя сперва пробовал  добавлять по маске `*.address.com/*` и оно не опознавалось, только когда выставлять стал `*.address.com` всё заработало. 

Ещё в попап меню расширения при нажатии на ссылку для редактирование белого списка вкладка с текстовым документом открывается, но фокус на неё не переводится. Думаю логичнее было бы сразу переключаться на эту вкладку при её открытии.

**Comment by ilyaigpetrov** [comment]
Сегодня заметил, что у меня почему-то иконка расширения после вчерашнего включения белого списка стала серой. У вас изменился цвет иконки с синей лентой? Если нет, то потестируйте ещё пару деньков.

**Comment by MasterPetrik** [comment]
Я со своей стороны могу сообщить о следующей закономерности. 
Если установлено и расширение с белым списком(версия 52) и последняя актуальная версия(версия 51) одновременно, то если активна версия 51, и её иконка синяя, то при активации ещё и версии 52 синей становится иконка версии 52 а иконка версии 51 становится серой. Если версию 52 отключить, то иконва версии 51 снова станет синей.
![image](https://user-images.githubusercontent.com/22294259/118673043-5d9d4c80-b801-11eb-8166-24a59896f753.png)

Я лично не вижу в этом поведении чего-то неправильного. Наоборот, очень наглядно становится видно какой из плагинов сейчас обеспечивает проксирование а какой нет. В конце концов при скачивании и обновлении плагина из магазина такая ситуация с двумя разными версиями одного плагина в одном браузере будет по идее невозможна.

**Comment by ilyaigpetrov** [comment]
Да, я спецально сделал так, что иконка теряет цвет, если кто-то другой контролирует настройки прокси в браузере.
Проблема не в этом, а в том, что если открыть окно (popup) расширения с серой иконкой, то в этом окне должно выводиться напоминание, что другое расширение контролирует прокси. См. рисунок:
![rcb-other-controls](https://user-images.githubusercontent.com/1090811/118678644-b8787900-b7ec-11eb-885b-ab75297d0105.png).

Когда же я тестировал сегодня, то иконка была серой, а напоминание отсутствовало.

**Comment by MasterPetrik** [comment]
Я сейчас посмотрел, и у меня во всех случаях активная версия 51 при активной версии 52 всегда в попапе показывает соответствующую плашку. То есть вроде как работает всё как и должно.
![image](https://user-images.githubusercontent.com/22294259/118682854-7d387300-b809-11eb-83b7-134e32a12182.png)

**Comment by ilyaigpetrov** [comment]
Опубликовано в WebStore в версии 0.0.1.52 -- см. https://rebrand.ly/ac-webstore.
Спасибо за идею!

**Comment by ilyaigpetrov** [comment]
Проблемы с контролем над прокси в расширениях возникала потому, что я работал из-под WSL и при перезагрузке машины нужный раздел не монтировался (или не подключался как сетевой диск -- подробностей работы я не знаю).
В итоге, контроль над прокси принадлежал расширению, которого в файловой системе не было.
