### ISSUE TITLE
Требуется ручное обновление после гибернации

### ISSUE THREAD

**Issue by goonis** [anticensority/runet-censorship-bypass#95]
1. обновить вручную Atizapret через Pac-Script /Update
2. увести компьютер в Hibernate более чем на 12 часов
3. включить, компьютер вернется в состояние перед hubernate со всеми запущенными программами в том числе браузерами, НО заблокированные сайты не будут открываться пока вновь вручную не обновить Atizapret через Pac-Script /Update

{
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.51"
}

Сорри, повтор https://github.com/anticensority/runet-censorship-bypass/issues/90

**Comment by ilyaigpetrov** [comment]
Duplicate of #90.

**Comment by ilyaigpetrov** [comment]
Duplicate of #90
